import type { CustomDesign } from './types'

const seed = (
  id: string,
  name: string,
  category: string,
  description: string,
  html: string,
  css: string,
  tags: string[],
): CustomDesign => ({ id, name, category, description, html, css, tags, source: 'seed' })

export const catalogExpansionG: CustomDesign[] = [
  seed(
    'exp3-stone-confirm-modal',
    'Stone Confirm Modal',
    'Modals & Overlays',
    'A restrained confirmation dialog with layered stone surfaces and a soft confirmation pulse.',
    `<div class="g-modal"><span>Archive project?</span><p>This action can be reversed later.</p><div><button>Cancel</button><button class="ok">Archive</button></div></div>`,
    `.g-modal{width:300px;padding:22px;border:1px solid #ffffff12;border-radius:22px;background:linear-gradient(160deg,#191a19,#0e0f0f);box-shadow:0 30px 70px #0008,inset 0 1px #fff1;font-family:Inter,sans-serif;color:#f1f1ed;animation:g-modal-in .45s cubic-bezier(.16,1,.3,1)}.g-modal span{display:block;font-size:18px;font-weight:800}.g-modal p{margin:8px 0 22px;color:#858985;font-size:12px;line-height:1.55}.g-modal div{display:flex;justify-content:flex-end;gap:8px}.g-modal button{height:36px;padding:0 13px;border:1px solid #ffffff12;border-radius:10px;background:#ffffff06;color:#aaa;cursor:pointer}.g-modal .ok{background:#d9d2bf;color:#171716;font-weight:800}.g-modal .ok:hover{box-shadow:0 0 0 4px #d9d2bf12,0 10px 24px #0005;transform:translateY(-1px)}@keyframes g-modal-in{from{opacity:0;transform:translateY(10px) scale(.98)}}`,
    ['modal','dialog','confirm','stone'],
  ),
  seed(
    'exp3-command-palette-overlay',
    'Command Palette Overlay',
    'Modals & Overlays',
    'A compact command palette with highlighted result motion and keyboard hints.',
    `<div class="g-command"><div class="search">⌘ <span>Search commands…</span><kbd>ESC</kbd></div><button><i>↗</i><span>Open workspace</span><kbd>⌘ O</kbd></button><button><i>＋</i><span>Create design</span><kbd>N</kbd></button><button><i>⌕</i><span>Search archive</span><kbd>/</kbd></button></div>`,
    `.g-command{width:330px;padding:9px;border:1px solid #ffffff12;border-radius:18px;background:#111313eF;box-shadow:0 28px 70px #0009;backdrop-filter:blur(18px);font:600 12px Inter,sans-serif;color:#d8dad6}.g-command .search{height:45px;padding:0 11px;display:flex;align-items:center;gap:9px;border-bottom:1px solid #ffffff0d;color:#777}.g-command .search span{flex:1}.g-command kbd{font:700 9px 'JetBrains Mono',monospace;color:#666;background:#ffffff06;border:1px solid #ffffff0c;border-radius:6px;padding:4px 6px}.g-command button{width:100%;height:43px;border:0;border-radius:10px;background:transparent;color:#aaa;display:flex;align-items:center;gap:10px;text-align:left;cursor:pointer;transition:.2s}.g-command button span{flex:1}.g-command button:hover{background:#ffffff08;color:#fff;transform:translateX(3px)}.g-command i{font-style:normal;width:20px;color:#969c96}`,
    ['command palette','overlay','keyboard','search'],
  ),
  seed(
    'exp3-context-popover',
    'Context Popover',
    'Modals & Overlays',
    'A floating context menu with crisp row feedback and a subtle pointer notch.',
    `<div class="g-pop"><i></i><button>Duplicate <kbd>⌘D</kbd></button><button>Move to… <b>›</b></button><button>Share <kbd>⌘⇧S</kbd></button><hr/><button class="danger">Delete</button></div>`,
    `.g-pop{position:relative;width:210px;padding:7px;border:1px solid #ffffff14;border-radius:14px;background:#151616;box-shadow:0 22px 55px #0008;font:600 11px Inter,sans-serif}.g-pop>i{position:absolute;width:10px;height:10px;top:-6px;left:34px;background:#151616;border-left:1px solid #ffffff14;border-top:1px solid #ffffff14;transform:rotate(45deg)}.g-pop button{width:100%;height:36px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:#aaa;display:flex;align-items:center;justify-content:space-between;cursor:pointer}.g-pop button:hover{background:#ffffff08;color:#fff}.g-pop kbd,.g-pop b{color:#616662;font:700 9px 'JetBrains Mono',monospace}.g-pop hr{border:0;border-top:1px solid #ffffff0d;margin:5px}.g-pop .danger:hover{background:#ff5d6910;color:#ff8b93}`,
    ['popover','context menu','overlay'],
  ),
  seed(
    'exp3-bottom-sheet',
    'Mobile Bottom Sheet',
    'Modals & Overlays',
    'A mobile-style bottom sheet with drag handle and layered action rows.',
    `<div class="g-sheet"><i></i><strong>Quick actions</strong><button><span>✦</span> Add to favorites</button><button><span>↗</span> Share component</button><button><span>⌘</span> Open code</button></div>`,
    `.g-sheet{width:300px;padding:10px 14px 16px;border:1px solid #ffffff10;border-radius:24px 24px 15px 15px;background:linear-gradient(180deg,#1b1d1c,#101111);box-shadow:0 28px 70px #0008;font-family:Inter,sans-serif;color:#eee;animation:g-sheet-up .5s cubic-bezier(.16,1,.3,1)}.g-sheet>i{display:block;width:42px;height:4px;border-radius:9px;background:#ffffff20;margin:1px auto 14px}.g-sheet strong{display:block;padding:0 8px 10px;font-size:14px}.g-sheet button{width:100%;height:43px;padding:0 9px;border:0;border-top:1px solid #ffffff0a;background:transparent;color:#aaa;text-align:left;cursor:pointer}.g-sheet button span{display:inline-grid;width:26px}.g-sheet button:hover{color:#fff;background:#ffffff04}@keyframes g-sheet-up{from{opacity:0;transform:translateY(22px)}}`,
    ['sheet','drawer','mobile','overlay'],
  ),
  seed(
    'exp3-info-tooltip',
    'Glass Info Tooltip',
    'Modals & Overlays',
    'A compact informative tooltip with soft glass and breathing status dot.',
    `<div class="g-tip"><i></i><div><strong>Live preview</strong><span>Changes update instantly</span></div></div>`,
    `.g-tip{position:relative;display:flex;align-items:center;gap:10px;padding:11px 13px;border:1px solid #ffffff14;border-radius:13px;background:#171918d9;backdrop-filter:blur(16px);box-shadow:0 18px 40px #0007;font-family:Inter,sans-serif}.g-tip>i{width:8px;height:8px;border-radius:50%;background:#7fd4a3;box-shadow:0 0 0 0 #7fd4a344;animation:g-tip-pulse 2s infinite}.g-tip strong{display:block;color:#eee;font-size:11px}.g-tip span{display:block;margin-top:2px;color:#777;font-size:9px}@keyframes g-tip-pulse{50%{box-shadow:0 0 0 7px #7fd4a300}}`,
    ['tooltip','glass','status','overlay'],
  ),
  seed(
    'exp3-side-drawer',
    'Compact Side Drawer',
    'Modals & Overlays',
    'A slim side drawer with layered rows and a quiet slide-in entrance.',
    `<div class="g-drawer"><header><span>Inspector</span><b>×</b></header><label>Name<input value="Graph Card"/></label><label>Radius<input value="24 px"/></label><button>Apply changes</button></div>`,
    `.g-drawer{width:260px;padding:16px;border:1px solid #ffffff10;border-radius:18px;background:#121414;box-shadow:-22px 30px 70px #0008;font:600 10px Inter,sans-serif;color:#868b87;animation:g-drawer-in .5s cubic-bezier(.16,1,.3,1)}.g-drawer header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;color:#eee;font-size:14px}.g-drawer header b{color:#666}.g-drawer label{display:grid;gap:6px;margin:12px 0}.g-drawer input{height:38px;border:1px solid #ffffff0e;border-radius:9px;background:#0b0c0c;color:#ddd;padding:0 10px;outline:0}.g-drawer input:focus{border-color:#ffffff25}.g-drawer button{width:100%;height:39px;border:0;border-radius:10px;background:#ded9c9;color:#151515;font-weight:800;cursor:pointer}@keyframes g-drawer-in{from{opacity:0;transform:translateX(28px)}}`,
    ['drawer','inspector','form','overlay'],
  ),
  seed(
    'exp3-activity-list',
    'Live Activity List',
    'Tables & Lists',
    'A compact activity list with status dots and animated latest-row emphasis.',
    `<div class="g-list"><header><span>Activity</span><b>LIVE</b></header><div class="new"><i></i><p><strong>Graph Card</strong><small>Updated now</small></p><em>↗</em></div><div><i></i><p><strong>Motion Button</strong><small>Saved 4m ago</small></p><em>↗</em></div><div><i></i><p><strong>Stone Modal</strong><small>Created 12m ago</small></p><em>↗</em></div></div>`,
    `.g-list{width:330px;padding:14px;border:1px solid #ffffff0e;border-radius:18px;background:#101212;font-family:Inter,sans-serif;color:#eee}.g-list header{display:flex;justify-content:space-between;padding:4px 6px 11px;font-size:12px}.g-list header b{font-size:8px;color:#78c99c;letter-spacing:.12em}.g-list>div{height:54px;display:flex;align-items:center;gap:10px;padding:0 8px;border-top:1px solid #ffffff08}.g-list>div>i{width:7px;height:7px;border-radius:50%;background:#555}.g-list .new>i{background:#78c99c;box-shadow:0 0 12px #78c99c66}.g-list p{flex:1;margin:0}.g-list strong,.g-list small{display:block}.g-list strong{font-size:11px}.g-list small{margin-top:3px;color:#666;font-size:9px}.g-list em{color:#555;font-style:normal}.g-list>div:hover{background:#ffffff04}.g-list .new{animation:g-row-in .5s ease}@keyframes g-row-in{from{opacity:0;transform:translateY(-6px)}}`,
    ['list','activity feed','rows'],
  ),
  seed(
    'exp3-project-table',
    'Project Status Table',
    'Tables & Lists',
    'A compact table with status chips, progress values and clean hover rows.',
    `<div class="g-table"><div class="head"><span>Project</span><span>Status</span><span>Done</span></div><div><strong>RED UI</strong><b class="green">Active</b><em>84%</em></div><div><strong>Motion Lab</strong><b class="gold">Review</b><em>61%</em></div><div><strong>Archive</strong><b>Draft</b><em>23%</em></div></div>`,
    `.g-table{width:350px;border:1px solid #ffffff0e;border-radius:16px;overflow:hidden;background:#101212;font:600 10px Inter,sans-serif;color:#aaa}.g-table>div{display:grid;grid-template-columns:1.4fr .8fr .45fr;align-items:center;min-height:46px;padding:0 13px;border-top:1px solid #ffffff08}.g-table .head{min-height:36px;border-top:0;background:#ffffff03;color:#5e635f;font-size:8px;text-transform:uppercase;letter-spacing:.08em}.g-table>div:not(.head):hover{background:#ffffff04}.g-table strong{color:#ddd}.g-table b{justify-self:start;padding:5px 7px;border-radius:999px;background:#ffffff08;color:#777;font-size:8px}.g-table b.green{background:#78c99c12;color:#78c99c}.g-table b.gold{background:#ddb66d12;color:#ddb66d}.g-table em{justify-self:end;font-style:normal;color:#777}`,
    ['table','status','projects'],
  ),
  seed(
    'exp3-kanban-list',
    'Mini Kanban List',
    'Tables & Lists',
    'A narrow kanban column with draggable-looking cards and tactile hover lift.',
    `<div class="g-kanban"><header><span>In progress</span><b>3</b></header><article><small>UI</small><strong>Refine category rail</strong><i>•••</i></article><article><small>MOTION</small><strong>Polish loader states</strong><i>•••</i></article><article><small>DOCS</small><strong>Update examples</strong><i>•••</i></article></div>`,
    `.g-kanban{width:260px;padding:12px;border:1px solid #ffffff0e;border-radius:18px;background:#0e1010;font-family:Inter,sans-serif}.g-kanban header{display:flex;justify-content:space-between;padding:4px 5px 12px;color:#aaa;font-size:11px}.g-kanban header b{color:#666}.g-kanban article{position:relative;margin:8px 0;padding:13px;border:1px solid #ffffff0c;border-radius:12px;background:linear-gradient(155deg,#191b1a,#131414);box-shadow:0 8px 20px #0003;transition:.25s}.g-kanban article:hover{transform:translateY(-3px);border-color:#ffffff18}.g-kanban small{display:block;color:#777;font-size:7px;letter-spacing:.1em}.g-kanban strong{display:block;margin-top:7px;color:#ddd;font-size:11px}.g-kanban i{position:absolute;right:10px;top:9px;color:#555;font-style:normal;font-size:10px}`,
    ['kanban','list','cards','workflow'],
  ),
  seed(
    'exp3-inbox-row-list',
    'Inbox Row List',
    'Tables & Lists',
    'A compact inbox list with unread emphasis and animated row controls.',
    `<div class="g-inbox"><div class="unread"><i>R</i><p><strong>Design review</strong><small>Looks ready for the next pass.</small></p><b>2m</b></div><div><i>M</i><p><strong>Motion notes</strong><small>Three comments added.</small></p><b>18m</b></div><div><i>A</i><p><strong>Archive sync</strong><small>All components indexed.</small></p><b>1h</b></div></div>`,
    `.g-inbox{width:350px;border:1px solid #ffffff0e;border-radius:16px;overflow:hidden;background:#101212;font-family:Inter,sans-serif}.g-inbox>div{height:62px;padding:0 12px;display:flex;align-items:center;gap:10px;border-top:1px solid #ffffff08;color:#777}.g-inbox>div:first-child{border-top:0}.g-inbox>div:hover{background:#ffffff04}.g-inbox>div>i{width:30px;height:30px;border-radius:9px;background:#ffffff07;display:grid;place-items:center;color:#aaa;font-style:normal;font-size:10px}.g-inbox p{flex:1;margin:0}.g-inbox strong,.g-inbox small{display:block}.g-inbox strong{color:#aaa;font-size:10px}.g-inbox small{margin-top:4px;font-size:8px}.g-inbox b{font-size:8px}.g-inbox .unread strong{color:#eee}.g-inbox .unread>i{background:#d9d2bf;color:#171716}`,
    ['inbox','list','rows','messages'],
  ),
  seed(
    'exp3-ranking-table',
    'Ranking Table',
    'Tables & Lists',
    'A dark ranking table with animated score bars and compact numeric hierarchy.',
    `<div class="g-rank"><div><b>01</b><span>Glass Button</span><i style="--v:92%"></i><em>92</em></div><div><b>02</b><span>Graph Card</span><i style="--v:76%"></i><em>76</em></div><div><b>03</b><span>Stone Modal</span><i style="--v:64%"></i><em>64</em></div></div>`,
    `.g-rank{width:340px;padding:10px;border:1px solid #ffffff0e;border-radius:16px;background:#101212;font:600 10px Inter,sans-serif}.g-rank>div{display:grid;grid-template-columns:30px 1fr 90px 28px;align-items:center;gap:8px;height:48px;border-top:1px solid #ffffff08;color:#777}.g-rank>div:first-child{border-top:0}.g-rank b{color:#575c59;font:700 9px 'JetBrains Mono',monospace}.g-rank span{color:#c6c8c5}.g-rank i{height:4px;border-radius:9px;background:linear-gradient(90deg,#c8c1ae var(--v),#ffffff08 var(--v));animation:g-rank-grow .8s ease}.g-rank em{font-style:normal;text-align:right;color:#aaa}@keyframes g-rank-grow{from{opacity:.2;transform:scaleX(.2);transform-origin:left}}`,
    ['table','ranking','data','rows'],
  ),
  seed(
    'exp3-file-list',
    'Compact File List',
    'Tables & Lists',
    'A clean file list with type badges and subtle row motion.',
    `<div class="g-files"><div><i>TS</i><strong>App.tsx</strong><span>8 KB</span></div><div><i>CSS</i><strong>stone-gallery.css</strong><span>13 KB</span></div><div><i>MD</i><strong>README.md</strong><span>4 KB</span></div></div>`,
    `.g-files{width:330px;padding:8px;border:1px solid #ffffff0e;border-radius:16px;background:#101212;font:600 10px Inter,sans-serif}.g-files>div{height:48px;display:flex;align-items:center;gap:10px;padding:0 8px;border-radius:10px;color:#666;transition:.2s}.g-files>div:hover{background:#ffffff05;transform:translateX(3px)}.g-files i{width:32px;height:26px;border-radius:7px;background:#ffffff07;display:grid;place-items:center;color:#8b908c;font-style:normal;font-size:7px}.g-files strong{flex:1;color:#c6c8c5;font-size:10px}.g-files span{font-size:8px}`,
    ['file list','list','files','rows'],
  ),
]
