import type { CustomDesign } from './types'

const seed = (
  id: string,
  name: string,
  category: string,
  description: string,
  html: string,
  css: string,
  tags: string[],
): CustomDesign => ({ id, name, category, description, html, css, tags, source: 'seed' })

export const catalogExpansionI: CustomDesign[] = [
  seed(
    'exp3-otp-input',
    'OTP Code Input',
    'Inputs & Forms',
    'A six-cell verification input with focused cell emphasis.',
    `<div class="i-otp"><input value="4"/><input value="8"/><input value="2"/><input value="1"/><input/><input/></div>`,
    `.i-otp{display:flex;gap:8px}.i-otp input{width:42px;height:50px;border:1px solid #ffffff0e;border-radius:12px;background:#111313;color:#eee;text-align:center;font:700 16px 'JetBrains Mono',monospace;outline:0;transition:.2s}.i-otp input:focus{border-color:#d8d1be55;box-shadow:0 0 0 4px #d8d1be08;transform:translateY(-2px)}`,
    ['input','otp','verification','form'],
  ),
  seed(
    'exp3-date-range-input',
    'Date Range Input',
    'Inputs & Forms',
    'A compact paired date-range field with calendar affordance.',
    `<div class="i-date"><span>◫</span><label><small>From</small><strong>13 Sep 2026</strong></label><i>→</i><label><small>To</small><strong>20 Sep 2026</strong></label></div>`,
    `.i-date{height:62px;padding:0 14px;border:1px solid #ffffff0e;border-radius:15px;background:#111313;display:flex;align-items:center;gap:12px;font-family:Inter,sans-serif}.i-date>span{color:#777}.i-date label{min-width:105px}.i-date small,.i-date strong{display:block}.i-date small{color:#5f645f;font-size:7px;text-transform:uppercase;letter-spacing:.08em}.i-date strong{margin-top:4px;color:#ccc;font-size:10px}.i-date i{color:#555;font-style:normal}.i-date:hover{border-color:#ffffff18}`,
    ['input','date','range','form'],
  ),
  seed(
    'exp3-file-drop-input',
    'File Drop Input',
    'Inputs & Forms',
    'A quiet drag-and-drop input with dashed stone border and hover lift.',
    `<label class="i-drop"><input type="file"/><i>＋</i><strong>Drop files here</strong><span>or click to browse</span></label>`,
    `.i-drop{width:300px;height:150px;border:1px dashed #ffffff1a;border-radius:18px;background:#111313;display:grid;place-items:center;align-content:center;gap:7px;color:#777;font-family:Inter,sans-serif;cursor:pointer;transition:.25s}.i-drop input{display:none}.i-drop i{width:36px;height:36px;border-radius:11px;background:#ffffff07;display:grid;place-items:center;color:#aaa;font-style:normal;font-size:18px}.i-drop strong{color:#c7c9c5;font-size:11px}.i-drop span{font-size:8px}.i-drop:hover{border-color:#d8d1be55;background:#151716;transform:translateY(-2px)}`,
    ['input','file','drop','upload','form'],
  ),
  seed(
    'exp3-segment-navigation',
    'Segment Navigation',
    'Navigation',
    'A compact segmented navigation control with sliding active surface.',
    `<nav class="i-segnav"><button class="active">Overview</button><button>Components</button><button>Motion</button></nav>`,
    `.i-segnav{padding:4px;border:1px solid #ffffff0e;border-radius:13px;background:#0e1010;display:flex;gap:3px;font-family:Inter,sans-serif}.i-segnav button{height:34px;padding:0 13px;border:0;border-radius:9px;background:transparent;color:#6c716d;font-size:9px;font-weight:700;cursor:pointer;transition:.2s}.i-segnav button:hover{color:#bbb}.i-segnav .active{background:#d7d0bd;color:#171716;box-shadow:0 7px 16px #0004}`,
    ['navigation','segments','tabs'],
  ),
  seed(
    'exp3-compact-pagination',
    'Compact Pagination',
    'Navigation',
    'A small pagination control with tactile page cells and active state.',
    `<nav class="i-pages"><button>‹</button><button>1</button><button class="active">2</button><button>3</button><span>…</span><button>12</button><button>›</button></nav>`,
    `.i-pages{display:flex;align-items:center;gap:5px;font:700 9px Inter,sans-serif}.i-pages button{width:34px;height:34px;border:1px solid #ffffff0d;border-radius:9px;background:#111313;color:#777;cursor:pointer;transition:.2s}.i-pages button:hover{color:#ddd;border-color:#ffffff18;transform:translateY(-1px)}.i-pages .active{background:#d6cfbd;color:#171716;border-color:#d6cfbd}.i-pages span{color:#555;padding:0 2px}`,
    ['navigation','pagination','pages'],
  ),
  seed(
    'exp3-filter-side-navigation',
    'Filter Side Navigation',
    'Navigation',
    'A narrow filter navigation with counts and selected rail marker.',
    `<nav class="i-filter"><strong>Library</strong><button class="active"><span>All</span><b>284</b></button><button><span>Favorites</span><b>18</b></button><button><span>Recent</span><b>32</b></button><button><span>Drafts</span><b>7</b></button></nav>`,
    `.i-filter{width:190px;padding:11px;border:1px solid #ffffff0d;border-radius:16px;background:#101212;font:600 10px Inter,sans-serif}.i-filter>strong{display:block;padding:7px 8px 11px;color:#eee;font-size:12px}.i-filter button{position:relative;width:100%;height:38px;padding:0 9px;border:0;border-radius:9px;background:transparent;color:#707571;display:flex;justify-content:space-between;align-items:center;cursor:pointer}.i-filter button:hover{background:#ffffff04;color:#bbb}.i-filter .active{background:#ffffff06;color:#e4e3de}.i-filter .active::before{content:"";position:absolute;left:-11px;width:2px;height:18px;border-radius:2px;background:#d5cebb}.i-filter b{font-size:8px;color:#555}`,
    ['navigation','sidebar','filter'],
  ),
  seed(
    'exp3-inline-alert',
    'Inline Alert',
    'Feedback & Status',
    'A calm inline alert with icon tile, message and dismiss action.',
    `<div class="i-alert"><i>!</i><p><strong>Unsaved changes</strong><span>Your latest edits are only local.</span></p><button>×</button></div>`,
    `.i-alert{width:350px;padding:12px;border:1px solid #d9b56a22;border-radius:15px;background:linear-gradient(90deg,#d9b56a0b,#111313);display:flex;align-items:center;gap:11px;font-family:Inter,sans-serif}.i-alert>i{width:34px;height:34px;border-radius:10px;background:#d9b56a12;display:grid;place-items:center;color:#d9b56a;font-style:normal;font-weight:900}.i-alert p{flex:1;margin:0}.i-alert strong,.i-alert span{display:block}.i-alert strong{color:#ddd;font-size:10px}.i-alert span{margin-top:3px;color:#777;font-size:8px}.i-alert button{border:0;background:transparent;color:#666;cursor:pointer}.i-alert button:hover{color:#ddd}`,
    ['feedback','alert','warning','status'],
  ),
  seed(
    'exp3-success-status',
    'Success Status Panel',
    'Feedback & Status',
    'A compact success panel with animated confirmation ring.',
    `<div class="i-success"><i>✓</i><div><strong>Published</strong><span>All 284 components are live.</span></div></div>`,
    `.i-success{width:300px;padding:16px;border:1px solid #73c8941f;border-radius:16px;background:#101312;display:flex;align-items:center;gap:12px;font-family:Inter,sans-serif}.i-success>i{width:40px;height:40px;border-radius:50%;background:#73c89412;border:1px solid #73c89433;display:grid;place-items:center;color:#73c894;font-style:normal;animation:i-success-ring 1.8s infinite}.i-success strong,.i-success span{display:block}.i-success strong{color:#ddd;font-size:11px}.i-success span{margin-top:4px;color:#6f7570;font-size:8px}@keyframes i-success-ring{50%{box-shadow:0 0 0 7px #73c89400,0 0 0 1px #73c89444}}`,
    ['feedback','success','status','panel'],
  ),
  seed(
    'exp3-sparkline-metric',
    'Sparkline Metric',
    'Dashboards & Data',
    'A compact metric with animated sparkline and delta badge.',
    `<div class="i-metric"><div><span>Sessions</span><b>+12.4%</b></div><strong>48,291</strong><svg viewBox="0 0 220 55"><path d="M2 44 C25 39 28 17 52 25 S87 47 112 29 S146 12 165 22 S198 33 218 8"/></svg></div>`,
    `.i-metric{width:260px;padding:16px;border:1px solid #ffffff0e;border-radius:17px;background:#111313;font-family:Inter,sans-serif}.i-metric>div{display:flex;justify-content:space-between;color:#777;font-size:8px}.i-metric b{color:#78ca9d}.i-metric>strong{display:block;margin:8px 0 2px;color:#eee;font-size:25px}.i-metric svg{width:100%;height:55px;overflow:visible}.i-metric path{fill:none;stroke:#d8d1be;stroke-width:2;stroke-linecap:round;stroke-dasharray:300;animation:i-metric-draw 1.3s ease}@keyframes i-metric-draw{from{stroke-dashoffset:300}}`,
    ['dashboard','data','metric','sparkline'],
  ),
  seed(
    'exp3-comparison-bars',
    'Comparison Bars',
    'Dashboards & Data',
    'A horizontal comparison chart for three compact metrics.',
    `<div class="i-bars"><div><span>Buttons</span><i><b style="--w:86%"></b></i><em>86</em></div><div><span>Cards</span><i><b style="--w:72%"></b></i><em>72</em></div><div><span>Inputs</span><i><b style="--w:58%"></b></i><em>58</em></div></div>`,
    `.i-bars{width:330px;padding:17px;border:1px solid #ffffff0e;border-radius:17px;background:#111313;font:600 9px Inter,sans-serif}.i-bars>div{display:grid;grid-template-columns:58px 1fr 24px;align-items:center;gap:9px;height:35px;color:#777}.i-bars i{height:7px;border-radius:8px;background:#ffffff07;overflow:hidden}.i-bars b{display:block;width:var(--w);height:100%;border-radius:inherit;background:linear-gradient(90deg,#777468,#d8d1be);animation:i-bars-grow .8s ease}.i-bars em{text-align:right;color:#aaa;font-style:normal}@keyframes i-bars-grow{from{width:0}}`,
    ['dashboard','data','comparison','bars'],
  ),
  seed(
    'exp3-quiet-action-button',
    'Quiet Action Button',
    'Buttons',
    'A restrained stone action button with subtle edge light and press travel.',
    `<button class="i-action"><span>Continue</span><i>→</i></button>`,
    `.i-action{height:48px;padding:0 17px;border:1px solid #ffffff11;border-radius:13px;background:linear-gradient(160deg,#1a1c1b,#111313);box-shadow:inset 0 1px #fff1,0 14px 28px #0004;color:#ddd;display:flex;align-items:center;gap:18px;font:800 10px Inter,sans-serif;cursor:pointer;transition:.22s}.i-action i{font-style:normal;color:#777;transition:.22s}.i-action:hover{border-color:#ffffff1f;background:#1b1d1c;transform:translateY(-2px)}.i-action:hover i{transform:translateX(3px);color:#ddd}.i-action:active{transform:translateY(1px) scale(.98)}`,
    ['button','action','stone','quiet'],
  ),
  seed(
    'exp3-info-card',
    'Compact Info Card',
    'Cards',
    'A compact information card with tiny accent rule and metadata.',
    `<article class="i-card"><i></i><span>COLLECTION</span><strong>Stone Interfaces</strong><p>24 quiet components with tactile details.</p><footer><small>Updated today</small><b>↗</b></footer></article>`,
    `.i-card{position:relative;width:250px;padding:17px;border:1px solid #ffffff0e;border-radius:18px;background:linear-gradient(150deg,#171918,#101212);font-family:Inter,sans-serif;transition:.25s}.i-card>i{position:absolute;left:0;top:22px;width:2px;height:28px;border-radius:2px;background:#d4cdba}.i-card>span{color:#666;font-size:7px;font-weight:800;letter-spacing:.12em}.i-card>strong{display:block;margin-top:9px;color:#eee;font-size:15px}.i-card>p{margin:8px 0 16px;color:#777;font-size:9px;line-height:1.5}.i-card footer{display:flex;justify-content:space-between;padding-top:11px;border-top:1px solid #ffffff08;color:#606561}.i-card b{color:#888}.i-card:hover{border-color:#ffffff18;transform:translateY(-3px)}`,
    ['card','info','stone','metadata'],
  ),
]
