import type { CustomDesign } from './types'

const seed = (
  id: string,
  name: string,
  category: string,
  description: string,
  html: string,
  css: string,
  tags: string[],
): CustomDesign => ({ id, name, category, description, html, css, tags, source: 'seed' })

export const catalogExpansionH: CustomDesign[] = [
  seed(
    'exp3-linear-progress',
    'Stone Linear Progress',
    'Progress & Steps',
    'A restrained linear progress indicator with moving highlight and numeric readout.',
    `<div class="h-progress"><div><strong>Syncing archive</strong><span>72%</span></div><i><b></b></i></div>`,
    `.h-progress{width:320px;padding:18px;border:1px solid #ffffff0e;border-radius:16px;background:#111313;font-family:Inter,sans-serif}.h-progress>div{display:flex;justify-content:space-between;margin-bottom:12px;color:#ccc;font-size:10px}.h-progress span{color:#777}.h-progress>i{display:block;height:8px;border-radius:999px;background:#ffffff07;overflow:hidden}.h-progress b{display:block;width:72%;height:100%;border-radius:inherit;background:linear-gradient(90deg,#aaa594,#e1dccb,#aaa594);background-size:180% 100%;animation:h-progress-shine 2s linear infinite}@keyframes h-progress-shine{to{background-position:180% 0}}`,
    ['progress','linear','completion'],
  ),
  seed(
    'exp3-stepper',
    'Four Step Stepper',
    'Progress & Steps',
    'A four-stage stepper with completed, active and upcoming states.',
    `<div class="h-stepper"><div class="done"><i>✓</i><span>Setup</span></div><b></b><div class="done"><i>✓</i><span>Design</span></div><b></b><div class="active"><i>3</i><span>Review</span></div><b></b><div><i>4</i><span>Ship</span></div></div>`,
    `.h-stepper{width:360px;display:flex;align-items:center;font:600 9px Inter,sans-serif;color:#5e635f}.h-stepper div{display:grid;justify-items:center;gap:7px}.h-stepper i{width:30px;height:30px;border:1px solid #ffffff12;border-radius:50%;display:grid;place-items:center;background:#111313;font-style:normal}.h-stepper b{flex:1;height:1px;background:#ffffff0d}.h-stepper .done i{background:#cfc8b7;color:#151515;border-color:#cfc8b7}.h-stepper .done+b{background:#cfc8b755}.h-stepper .active{color:#ddd}.h-stepper .active i{border-color:#d8d1be55;box-shadow:0 0 0 6px #d8d1be08;animation:h-step-pulse 2s infinite}@keyframes h-step-pulse{50%{box-shadow:0 0 0 10px #d8d1be00}}`,
    ['stepper','steps','wizard'],
  ),
  seed(
    'exp3-circular-progress',
    'Circular Completion',
    'Progress & Steps',
    'A circular completion meter with an animated stroke and centered percentage.',
    `<div class="h-ring"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40"/><circle class="value" cx="50" cy="50" r="40"/></svg><div><strong>68%</strong><span>complete</span></div></div>`,
    `.h-ring{position:relative;width:150px;height:150px;display:grid;place-items:center;font-family:Inter,sans-serif}.h-ring svg{position:absolute;inset:0;transform:rotate(-90deg)}.h-ring circle{fill:none;stroke:#ffffff0a;stroke-width:8}.h-ring .value{stroke:#d8d1be;stroke-linecap:round;stroke-dasharray:251;stroke-dashoffset:80;animation:h-ring-draw 1s ease}.h-ring div{text-align:center}.h-ring strong{display:block;color:#eee;font-size:28px}.h-ring span{color:#666;font-size:9px}@keyframes h-ring-draw{from{stroke-dashoffset:251}}`,
    ['progress','ring','completion'],
  ),
  seed(
    'exp3-upload-progress',
    'Upload Progress Row',
    'Progress & Steps',
    'A file upload row with live progress bar and compact file metadata.',
    `<div class="h-upload"><i>ZIP</i><div><strong>ui-kit-export.zip</strong><span>18.2 MB · uploading</span><b><em></em></b></div><small>54%</small></div>`,
    `.h-upload{width:350px;padding:14px;border:1px solid #ffffff0e;border-radius:16px;background:#111313;display:flex;align-items:center;gap:12px;font-family:Inter,sans-serif}.h-upload>i{width:42px;height:42px;border-radius:11px;background:#ffffff07;display:grid;place-items:center;color:#8b908c;font:700 8px 'JetBrains Mono',monospace}.h-upload>div{flex:1}.h-upload strong,.h-upload span{display:block}.h-upload strong{color:#ddd;font-size:10px}.h-upload span{margin:4px 0 8px;color:#666;font-size:8px}.h-upload b{display:block;height:4px;border-radius:9px;background:#ffffff07;overflow:hidden}.h-upload em{display:block;width:54%;height:100%;background:#cfc8b7;animation:h-upload 1.2s ease}.h-upload small{color:#777;font-size:9px}@keyframes h-upload{from{width:0}}`,
    ['progress','upload','file'],
  ),
  seed(
    'exp3-onboarding-steps',
    'Onboarding Steps',
    'Progress & Steps',
    'A vertical onboarding sequence with a calm active marker and completion line.',
    `<div class="h-onboard"><div class="done"><i>✓</i><p><strong>Create account</strong><span>Done</span></p></div><div class="active"><i>2</i><p><strong>Choose workspace</strong><span>In progress</span></p></div><div><i>3</i><p><strong>Invite team</strong><span>Next</span></p></div></div>`,
    `.h-onboard{width:280px;font-family:Inter,sans-serif}.h-onboard>div{position:relative;min-height:62px;display:flex;gap:12px}.h-onboard>div:not(:last-child)::after{content:"";position:absolute;left:14px;top:30px;bottom:0;width:1px;background:#ffffff10}.h-onboard i{position:relative;z-index:1;width:29px;height:29px;border-radius:50%;border:1px solid #ffffff12;background:#101212;display:grid;place-items:center;color:#666;font-style:normal;font-size:9px}.h-onboard p{margin:1px 0}.h-onboard strong,.h-onboard span{display:block}.h-onboard strong{color:#aaa;font-size:10px}.h-onboard span{margin-top:4px;color:#5e635f;font-size:8px}.h-onboard .done i{background:#cfc8b7;color:#151515}.h-onboard .active i{color:#eee;border-color:#d8d1be44;box-shadow:0 0 0 5px #d8d1be08}.h-onboard .active strong{color:#eee}`,
    ['steps','onboarding','vertical'],
  ),
  seed(
    'exp3-segment-progress',
    'Segment Progress',
    'Progress & Steps',
    'A segmented milestone bar with five tactile completion blocks.',
    `<div class="h-segments"><div><b></b><b></b><b></b><b class="active"></b><b></b></div><span>Stage 4 of 5 · Review</span></div>`,
    `.h-segments{width:320px;padding:18px;border:1px solid #ffffff0e;border-radius:16px;background:#111313;font:600 9px Inter,sans-serif;color:#777}.h-segments div{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-bottom:10px}.h-segments b{height:7px;border-radius:4px;background:#ffffff08}.h-segments b:nth-child(-n+3){background:#9d998d}.h-segments .active{background:#dfd8c5;box-shadow:0 0 16px #dfd8c533;animation:h-segment-pulse 1.8s infinite}@keyframes h-segment-pulse{50%{filter:brightness(1.25)}}`,
    ['progress','steps','segments'],
  ),
  seed(
    'exp3-presence-avatar',
    'Presence Avatar',
    'Avatars & Profiles',
    'A dimensional avatar tile with online state and subtle breathing presence ring.',
    `<div class="h-avatar"><div>RB</div><i></i></div>`,
    `.h-avatar{position:relative;width:88px;height:88px}.h-avatar div{width:100%;height:100%;border-radius:28px;display:grid;place-items:center;background:linear-gradient(145deg,#393c38,#171918);border:1px solid #ffffff12;box-shadow:inset 0 1px #fff1,0 20px 35px #0006;color:#ddd;font:800 22px Inter,sans-serif}.h-avatar i{position:absolute;right:-2px;bottom:-2px;width:18px;height:18px;border:4px solid #0f1110;border-radius:50%;background:#77c99b;box-shadow:0 0 0 0 #77c99b44;animation:h-presence 2s infinite}@keyframes h-presence{50%{box-shadow:0 0 0 7px #77c99b00}}`,
    ['avatar','presence','profile'],
  ),
  seed(
    'exp3-profile-chip',
    'Compact Profile Chip',
    'Avatars & Profiles',
    'A compact user chip with avatar initials, role and dropdown affordance.',
    `<button class="h-chip"><i>AR</i><span><strong>Alex Rivera</strong><small>Designer</small></span><b>⌄</b></button>`,
    `.h-chip{height:54px;padding:0 11px;border:1px solid #ffffff0e;border-radius:15px;background:#111313;display:flex;align-items:center;gap:10px;color:#aaa;cursor:pointer;font-family:Inter,sans-serif;transition:.2s}.h-chip:hover{background:#171918;border-color:#ffffff18}.h-chip>i{width:34px;height:34px;border-radius:11px;background:linear-gradient(145deg,#d7d0bd,#8f8b7f);display:grid;place-items:center;color:#1b1b1a;font:800 9px Inter,sans-serif}.h-chip span{text-align:left;min-width:110px}.h-chip strong,.h-chip small{display:block}.h-chip strong{color:#ddd;font-size:10px}.h-chip small{margin-top:3px;color:#666;font-size:8px}.h-chip>b{color:#666}`,
    ['profile','user chip','avatar'],
  ),
  seed(
    'exp3-member-stack',
    'Member Stack',
    'Avatars & Profiles',
    'An overlapping member stack with hover separation and overflow counter.',
    `<div class="h-stack"><i>MK</i><i>SR</i><i>AL</i><i>JT</i><b>+8</b></div>`,
    `.h-stack{display:flex;align-items:center;padding-left:14px}.h-stack i,.h-stack b{width:42px;height:42px;margin-left:-14px;border:3px solid #101212;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#30332f,#1a1c1b);color:#bbb;font:800 8px Inter,sans-serif;transition:.25s}.h-stack i:nth-child(2){background:linear-gradient(145deg,#4b453a,#27231e)}.h-stack i:nth-child(3){background:linear-gradient(145deg,#35444a,#1d2629)}.h-stack i:nth-child(4){background:linear-gradient(145deg,#443944,#241e24)}.h-stack b{background:#d6cfbd;color:#171716}.h-stack:hover i,.h-stack:hover b{margin-left:-7px;transform:translateY(-2px)}`,
    ['member stack','avatars','team','profile'],
  ),
  seed(
    'exp3-profile-summary',
    'Profile Summary',
    'Avatars & Profiles',
    'A compact profile summary with role, activity and animated presence marker.',
    `<div class="h-summary"><div class="pic">LM<i></i></div><div><strong>Lea Müller</strong><span>Motion designer</span><small>Active now</small></div><button>•••</button></div>`,
    `.h-summary{width:320px;padding:14px;border:1px solid #ffffff0e;border-radius:17px;background:#111313;display:flex;align-items:center;gap:12px;font-family:Inter,sans-serif}.h-summary .pic{position:relative;width:48px;height:48px;border-radius:15px;background:linear-gradient(145deg,#d6cfbd,#777267);display:grid;place-items:center;color:#181817;font-weight:800}.h-summary .pic i{position:absolute;right:-2px;bottom:-2px;width:11px;height:11px;border:3px solid #111313;border-radius:50%;background:#78ca9d}.h-summary>div:nth-child(2){flex:1}.h-summary strong,.h-summary span,.h-summary small{display:block}.h-summary strong{color:#ddd;font-size:11px}.h-summary span{margin-top:4px;color:#777;font-size:9px}.h-summary small{margin-top:5px;color:#78ca9d;font-size:8px}.h-summary button{border:0;background:transparent;color:#555;cursor:pointer}`,
    ['profile','avatar','presence','summary'],
  ),
  seed(
    'exp3-avatar-ring',
    'Activity Avatar Ring',
    'Avatars & Profiles',
    'An avatar wrapped by a rotating activity arc for active contributors.',
    `<div class="h-avatar-ring"><span>NO</span><i></i></div>`,
    `.h-avatar-ring{position:relative;width:94px;height:94px;display:grid;place-items:center}.h-avatar-ring::before{content:"";position:absolute;inset:0;border-radius:50%;background:conic-gradient(#d8d1be 0 72%,#ffffff0b 72% 100%);mask:radial-gradient(transparent 61%,#000 62%);animation:h-avatar-spin 8s linear infinite}.h-avatar-ring span{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#2a2d2a,#151716);border:1px solid #ffffff10;color:#ccc;font:800 16px Inter,sans-serif}.h-avatar-ring i{position:absolute;width:7px;height:7px;border-radius:50%;background:#d8d1be;right:5px;top:19px;box-shadow:0 0 10px #d8d1be55}@keyframes h-avatar-spin{to{transform:rotate(360deg)}}`,
    ['avatar','activity','profile','ring'],
  ),
  seed(
    'exp3-role-profile',
    'Role Profile Tile',
    'Avatars & Profiles',
    'A role-focused identity tile with department badge and compact metadata.',
    `<div class="h-role"><header><i>SK</i><b>CORE</b></header><strong>Sam Keller</strong><span>Product Engineer</span><footer><small>12 projects</small><small>84 components</small></footer></div>`,
    `.h-role{width:220px;padding:16px;border:1px solid #ffffff0e;border-radius:18px;background:linear-gradient(155deg,#171918,#101212);font-family:Inter,sans-serif}.h-role header{display:flex;justify-content:space-between;align-items:center}.h-role i{width:44px;height:44px;border-radius:14px;background:#d4cdba;display:grid;place-items:center;color:#161616;font-style:normal;font-weight:800}.h-role header b{padding:5px 7px;border-radius:999px;background:#ffffff07;color:#767b77;font-size:7px;letter-spacing:.1em}.h-role>strong{display:block;margin-top:16px;color:#eee;font-size:14px}.h-role>span{display:block;margin-top:4px;color:#777;font-size:9px}.h-role footer{display:flex;gap:12px;margin-top:16px;padding-top:12px;border-top:1px solid #ffffff08}.h-role small{color:#626763;font-size:8px}.h-role:hover{border-color:#ffffff18}`,
    ['profile','role','avatar','identity'],
  ),
]
