import type { CustomDesign } from './types'

type Idea = readonly [name: string, description: string, tags: readonly string[]]
type Built = { html: string; css: string; js?: string }

const esc = (value: string) => value.replace(/[<>]/g, '')
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const seed = (number: number, category: string, idea: Idea, built: Built): CustomDesign => ({
  id: `extreme-${String(number).padStart(3, '0')}-${slug(idea[0])}`,
  name: idea[0],
  category,
  description: idea[1],
  html: built.html,
  css: built.css,
  js: built.js,
  tags: [...idea[2], 'extreme-100'],
  source: 'seed',
})

const buttonIdeas: Idea[] = [
  ['True Depth Button', 'A physical button that sinks eight pixels into its base while the highlight compresses.', ['button', '3d', 'press', 'depth']],
  ['Liquid Glass Button', 'Translucent liquid glass with refraction-like glow, blur and a moving highlight edge.', ['button', 'glass', 'liquid', 'blur']],
  ['Magnetic Button', 'The control leans and travels toward the pointer as if the cursor were magnetic.', ['button', 'magnetic', 'cursor', 'physics']],
  ['Jelly Button', 'A soft gummy control that squashes, stretches and settles after interaction.', ['button', 'jelly', 'spring', 'playful']],
  ['Particle Burst Button', 'Clicking the button fires a small ring of glowing fragments around it.', ['button', 'particles', 'click', 'burst']],
  ['Morphing Blob Button', 'An organic button whose silhouette keeps changing between rounded blob shapes.', ['button', 'blob', 'morph', 'organic']],
  ['Chrome Reflection Button', 'A metallic surface whose reflection follows the pointer position.', ['button', 'chrome', 'metal', 'reflection']],
  ['Hologram Button', 'Scanlines, cyan-magenta RGB separation and a faint holographic glitch.', ['button', 'hologram', 'glitch', 'rgb']],
  ['Electric Neon Button', 'A neon control with a breathing outer glow and tiny electric edge sparks.', ['button', 'neon', 'electric', 'glow']],
  ['Frosted Noise Button', 'Milky frosted glass with blur, grain and a subtle icy highlight.', ['button', 'frosted', 'noise', 'glass']],
]

const buttonVariants = [
  `.x100-btn{--c:#766dff;position:relative;border:0;border-radius:18px;padding:16px 27px;color:#fff;background:linear-gradient(#8178ff,#574cd4);font:900 13px Inter,sans-serif;letter-spacing:.08em;cursor:pointer;box-shadow:0 8px 0 #30298d,0 16px 28px #0008,inset 0 2px #fff5;transition:transform .12s,box-shadow .12s}.x100-btn:before{content:"";position:absolute;inset:5px 12px auto;height:6px;border-radius:50%;background:#fff5;filter:blur(3px)}.x100-btn:hover{transform:translateY(-2px);box-shadow:0 10px 0 #30298d,0 20px 32px #0008,inset 0 2px #fff6}.x100-btn:active{transform:translateY(8px);box-shadow:0 1px 0 #30298d,0 5px 10px #0007,inset 0 1px #fff3}`,
  `.x100-btn{position:relative;border:1px solid #fff4;border-radius:22px;padding:16px 28px;color:#fff;background:linear-gradient(135deg,#ffffff22,#8abfff13);backdrop-filter:blur(20px) saturate(170%);font:800 13px Inter,sans-serif;letter-spacing:.06em;cursor:pointer;overflow:hidden;box-shadow:inset 0 1px #fff6,inset 0 -12px 24px #6fa8ff16,0 20px 40px #0005}.x100-btn:before{content:"";position:absolute;inset:-40% -20%;background:radial-gradient(circle at 20% 15%,#fff9,transparent 16%),linear-gradient(110deg,transparent 30%,#fff6 48%,transparent 62%);transform:translateX(-42%) rotate(-7deg);animation:x100-liquid-shine 3.4s ease-in-out infinite}.x100-btn span{position:relative}.x100-btn:hover{border-color:#bce7ff88;box-shadow:inset 0 1px #fff8,0 0 35px #7dd3fc33,0 20px 40px #0006}@keyframes x100-liquid-shine{50%{transform:translateX(45%) rotate(7deg)}}`,
  `.x100-btn{--mx:0px;--my:0px;position:relative;border:1px solid #ffffff22;border-radius:18px;padding:16px 28px;color:#fff;background:#12151c;font:900 13px Inter,sans-serif;cursor:pointer;transform:translate(var(--mx),var(--my)) rotateX(calc(var(--my)*-.18)) rotateY(calc(var(--mx)*.18));transition:transform .12s ease-out,box-shadow .2s;box-shadow:0 18px 35px #0006,inset 0 1px #fff2}.x100-btn:before{content:"";position:absolute;inset:-35px;border-radius:40px;background:radial-gradient(circle at var(--px,50%) var(--py,50%),#756cff44,transparent 38%);z-index:-1}.x100-btn:hover{box-shadow:0 22px 40px #0007,0 0 28px #756cff22}`,
  `.x100-btn{border:0;border-radius:25px 20px 29px 22px;padding:17px 29px;color:#fff;background:linear-gradient(145deg,#ff72ae,#8b5cf6);font:900 13px Inter,sans-serif;cursor:pointer;box-shadow:inset 0 3px #fff5,inset 0 -11px 18px #551b7a55,0 18px 30px #0005;animation:x100-jelly-idle 3.8s ease-in-out infinite}.x100-btn:hover{animation:x100-jelly-pop .62s cubic-bezier(.2,.9,.2,1.3)}.x100-btn:active{transform:scaleX(1.15) scaleY(.76)}@keyframes x100-jelly-idle{50%{border-radius:20px 29px 21px 27px;transform:translateY(-3px)}}@keyframes x100-jelly-pop{0%,100%{transform:scale(1)}25%{transform:scaleX(1.18) scaleY(.83) rotate(-2deg)}55%{transform:scaleX(.91) scaleY(1.12) rotate(2deg)}80%{transform:scaleX(1.05) scaleY(.96)}}`,
  `.x100-wrap{position:relative;display:inline-grid;place-items:center}.x100-btn{position:relative;border:1px solid #ffffff24;border-radius:18px;padding:16px 28px;color:#fff;background:linear-gradient(145deg,#1f2330,#101218);font:900 13px Inter,sans-serif;cursor:pointer;box-shadow:0 18px 34px #0006,inset 0 1px #fff2}.x100-btn:hover{border-color:#f472b688;box-shadow:0 0 28px #f472b633,0 18px 34px #0006}.x100-particle{position:absolute;left:50%;top:50%;width:7px;height:7px;border-radius:2px;background:hsl(var(--h) 90% 68%);pointer-events:none;animation:x100-burst .65s ease-out forwards}@keyframes x100-burst{to{transform:translate(var(--x),var(--y)) rotate(240deg) scale(.15);opacity:0}}`,
  `.x100-btn{border:0;padding:17px 31px;color:#fff;background:linear-gradient(135deg,#22d3ee,#756cff,#f472b6);font:900 13px Inter,sans-serif;cursor:pointer;box-shadow:0 18px 35px #0005;animation:x100-blob 5s ease-in-out infinite;transition:filter .2s}.x100-btn:hover{filter:saturate(1.3) brightness(1.08);animation-duration:1.8s}@keyframes x100-blob{0%,100%{border-radius:51% 49% 58% 42%/53% 61% 39% 47%}33%{border-radius:40% 60% 43% 57%/62% 41% 59% 38%}66%{border-radius:61% 39% 56% 44%/41% 58% 42% 59%}}`,
  `.x100-btn{--px:50%;position:relative;border:1px solid #fff8;border-radius:16px;padding:16px 29px;color:#101115;background:linear-gradient(105deg,#37393d 0%,#f5f5f5 22%,#777b82 42%,#fff 52%,#4a4d53 70%,#d8dbe0 88%,#5e6269);background-size:220% 100%;background-position:calc(var(--px) - 50%) center;font:900 13px Inter,sans-serif;letter-spacing:.08em;cursor:pointer;box-shadow:inset 0 2px 2px #fff,inset 0 -3px 5px #0006,0 18px 32px #0007;text-shadow:0 1px #fff8;transition:background-position .08s,transform .2s}.x100-btn:hover{transform:translateY(-3px) rotateX(4deg)}`,
  `.x100-btn{position:relative;border:1px solid #67e8f999;border-radius:13px;padding:16px 28px;color:#bff8ff;background:#04151c99;font:900 13px monospace;letter-spacing:.14em;cursor:pointer;overflow:hidden;text-shadow:-1px 0 #ff4d9d,1px 0 #22d3ee,0 0 10px #22d3ee;box-shadow:inset 0 0 22px #22d3ee18,0 0 22px #22d3ee26}.x100-btn:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#67e8f91a 3px 4px);animation:x100-scan .7s linear infinite}.x100-btn:hover span{animation:x100-glitch .28s steps(2) infinite}@keyframes x100-scan{to{background-position:0 4px}}@keyframes x100-glitch{0%{transform:translate(0)}33%{transform:translate(2px,-1px)}66%{transform:translate(-2px,1px)}}`,
  `.x100-btn{position:relative;border:1px solid #a78bfa;border-radius:16px;padding:16px 29px;color:#f5f3ff;background:#100d19;font:900 13px Inter,sans-serif;letter-spacing:.08em;cursor:pointer;box-shadow:0 0 9px #8b5cf6,0 0 26px #8b5cf666,inset 0 0 18px #8b5cf622;animation:x100-neon 1.7s ease-in-out infinite}.x100-btn:before,.x100-btn:after{content:"";position:absolute;width:4px;height:4px;border-radius:50%;background:#fff;box-shadow:0 0 9px #fff;opacity:.2}.x100-btn:before{left:10%;top:-2px;animation:x100-spark 1.2s steps(2) infinite}.x100-btn:after{right:13%;bottom:-2px;animation:x100-spark 1.6s steps(2) .4s infinite}@keyframes x100-neon{50%{box-shadow:0 0 14px #a78bfa,0 0 38px #8b5cf688,inset 0 0 25px #8b5cf633}}@keyframes x100-spark{50%{opacity:1;transform:scale(2)}}`,
  `.x100-btn{position:relative;border:1px solid #ffffff3d;border-radius:19px;padding:16px 29px;color:#fff;background:linear-gradient(145deg,#ffffff18,#dbeafe0b);backdrop-filter:blur(18px);font:800 13px Inter,sans-serif;cursor:pointer;overflow:hidden;box-shadow:inset 0 1px #fff5,0 18px 36px #0005}.x100-btn:before{content:"";position:absolute;inset:0;opacity:.28;background-image:radial-gradient(#fff 0.7px,transparent .8px);background-size:5px 5px;mask-image:linear-gradient(135deg,#000,transparent 80%)}.x100-btn:after{content:"";position:absolute;left:12px;right:12px;top:6px;height:1px;background:linear-gradient(90deg,transparent,#fff,transparent);filter:blur(.2px)}.x100-btn:hover{box-shadow:inset 0 1px #fff7,0 0 28px #bae6fd22,0 20px 40px #0005}`,
]

function buildButton(index: number, idea: Idea): Built {
  const isBurst = index === 4
  const html = isBurst
    ? `<span class="x100-wrap"><button class="x100-btn" type="button"><span>${esc(idea[0].replace(' Button', ''))}</span></button></span>`
    : `<button class="x100-btn" type="button"><span>${esc(idea[0].replace(' Button', ''))}</span><i></i><b></b></button>`
  let js: string | undefined
  if (index === 2) js = `const b=document.querySelector('.x100-btn');b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;b.style.setProperty('--mx',(x*.16)+'px');b.style.setProperty('--my',(y*.16)+'px');b.style.setProperty('--px',((e.clientX-r.left)/r.width*100)+'%');b.style.setProperty('--py',((e.clientY-r.top)/r.height*100)+'%')});b.addEventListener('pointerleave',()=>{b.style.setProperty('--mx','0px');b.style.setProperty('--my','0px')})`
  if (index === 4) js = `const w=document.querySelector('.x100-wrap'),b=document.querySelector('.x100-btn');b.addEventListener('click',()=>{for(let i=0;i<16;i++){const p=document.createElement('i'),a=Math.PI*2*i/16,d=45+Math.random()*55;p.className='x100-particle';p.style.setProperty('--x',Math.cos(a)*d+'px');p.style.setProperty('--y',Math.sin(a)*d+'px');p.style.setProperty('--h',String((i*27)%360));w.appendChild(p);setTimeout(()=>p.remove(),700)}})`
  if (index === 6) js = `const b=document.querySelector('.x100-btn');b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();b.style.setProperty('--px',((e.clientX-r.left)/r.width*100)+'%')})`
  return { html, css: buttonVariants[index], js }
}

const loginIdeas: Idea[] = [
  ['Perspective Login Card', 'A sign-in card that tilts in real 3D toward the pointer.', ['login', '3d', 'tilt']],
  ['Floating Login Panel', 'A calm sign-in panel that slowly floats in depth with layered shadows.', ['login', 'floating', 'depth']],
  ['Portal Login', 'Successful login collapses the panel into a glowing portal.', ['login', 'portal', 'transition']],
  ['Face Reaction Login', 'A small character changes its eyes when the password field receives focus.', ['login', 'character', 'reaction']],
  ['Cyberpunk Login', 'Neon frame, scanlines, glitch title and a perspective grid floor.', ['login', 'cyberpunk', 'glitch']],
  ['Space Login', 'Glass inputs float in a compact star field with orbital decoration.', ['login', 'space', 'glass']],
  ['Underwater Login', 'Soft caustic light, bubbles and blue depth make the panel feel submerged.', ['login', 'underwater', 'bubbles']],
  ['Cloud Login', 'A bright glass card appears to float between soft volumetric cloud blobs.', ['login', 'cloud', 'soft']],
  ['Retro CRT Login', 'Terminal-green login with CRT curvature, scanlines and a blinking cursor.', ['login', 'retro', 'crt']],
  ['Vault Login', 'Submitting the form rotates a miniature vault door to reveal access granted.', ['login', 'vault', 'mechanical']],
]

const loginVariantCss = [
  `.x100-login{transform:perspective(700px) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg));transition:transform .12s ease-out;box-shadow:0 28px 55px #0008,inset 0 1px #fff2}.x100-login:before{content:"";position:absolute;inset:-1px;border-radius:21px;background:linear-gradient(135deg,#756cff66,transparent 40%,#22d3ee33);z-index:-1;transform:translateZ(-1px)}`,
  `.x100-login{animation:x100-float-login 4s ease-in-out infinite;box-shadow:0 26px 60px #0007,0 0 60px #756cff14}.x100-login:before,.x100-login:after{content:"";position:absolute;inset:12px;border:1px solid #ffffff12;border-radius:18px;transform:translateZ(-22px);filter:blur(.2px)}.x100-login:after{inset:25px;transform:translateZ(-44px);opacity:.4}@keyframes x100-float-login{50%{transform:translateY(-10px) rotateX(2deg) rotateY(-2deg)}}`,
  `.x100-login{transition:transform .8s cubic-bezier(.2,.9,.2,1),filter .8s,opacity .8s}.x100-login:after{content:"";position:absolute;left:50%;top:50%;width:12px;height:12px;border-radius:50%;background:#756cff;box-shadow:0 0 30px 12px #756cff;opacity:0;transform:translate(-50%,-50%) scale(.1);transition:.7s}.x100-login.success{transform:scale(.08) rotate(260deg);filter:blur(8px);opacity:.3}.x100-login.success:after{opacity:1;transform:translate(-50%,-50%) scale(7)}`,
  `.x100-face{display:block;font-size:34px;text-align:center;margin:-2px 0 8px;transition:transform .3s}.x100-face:before{content:"◉‿◉"}.x100-login.looking-away .x100-face{transform:rotate(-8deg) translateX(-6px)}.x100-login.looking-away .x100-face:before{content:"◔‿◔"}.x100-login input:focus{box-shadow:0 0 0 2px #f472b655}`, 
  `.x100-login{border-color:#22d3ee66;box-shadow:0 0 0 1px #f472b633,0 0 30px #22d3ee22;overflow:hidden}.x100-login:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#22d3ee10 3px 4px);pointer-events:none;animation:x100-cyber-scan .8s linear infinite}.x100-login:after{content:"";position:absolute;left:-20%;right:-20%;bottom:-42px;height:85px;background:repeating-linear-gradient(90deg,#22d3ee22 0 1px,transparent 1px 22px),repeating-linear-gradient(0deg,#22d3ee22 0 1px,transparent 1px 15px);transform:perspective(140px) rotateX(65deg);pointer-events:none}.x100-login h3{text-shadow:-2px 0 #f472b6,2px 0 #22d3ee}@keyframes x100-cyber-scan{to{background-position:0 4px}}`,
  `.x100-login{background:linear-gradient(145deg,#ffffff10,#5965ff0c);backdrop-filter:blur(18px);box-shadow:0 25px 60px #0008,0 0 55px #4257ff18}.x100-login:before{content:"✦  ·  ✧  ·  ✦   ·  ✧";position:absolute;inset:-28px;color:#fff8;font-size:10px;letter-spacing:18px;animation:x100-stars 5s linear infinite;pointer-events:none}.x100-login:after{content:"";position:absolute;width:70px;height:24px;border:1px solid #8b8fff66;border-radius:50%;right:-24px;top:28px;transform:rotate(-25deg);box-shadow:0 0 18px #756cff44}@keyframes x100-stars{50%{transform:translateY(12px) rotate(2deg)}}`,
  `.x100-login{background:linear-gradient(180deg,#0a4166dd,#06243bdd);box-shadow:inset 0 15px 35px #8ce7ff15,0 30px 60px #0008}.x100-login:before,.x100-login:after{content:"";position:absolute;border-radius:50%;border:1px solid #b9f2ff88;width:16px;height:16px;left:18px;bottom:-24px;animation:x100-bubble 3.6s linear infinite}.x100-login:after{width:9px;height:9px;left:auto;right:30px;animation-delay:1.2s;animation-duration:2.8s}.x100-login h3{color:#c9f6ff;text-shadow:0 0 12px #67e8f9}@keyframes x100-bubble{to{transform:translateY(-260px) translateX(22px);opacity:0}}`,
  `.x100-login{background:#ffffffd9;color:#1f2937;border-color:#fff;box-shadow:0 28px 70px #8ca5c755,0 0 50px #fff8}.x100-login input{background:#ffffffaa;color:#111827;border-color:#dbeafe}.x100-login button{color:#fff}.x100-login:before,.x100-login:after{content:"";position:absolute;width:120px;height:50px;border-radius:999px;background:#fff;filter:blur(14px);opacity:.75;z-index:-1}.x100-login:before{left:-65px;top:35px}.x100-login:after{right:-70px;bottom:22px}`, 
  `.x100-login{background:#07110b;border-color:#24ff7055;box-shadow:0 0 28px #24ff7018,inset 0 0 28px #24ff7008;font-family:monospace}.x100-login h3,.x100-login small{color:#64ff91}.x100-login h3:after{content:"_";animation:x100-cursor .7s steps(1) infinite}.x100-login input{background:#020704;border-color:#24ff7033;color:#8dffae;font-family:monospace}.x100-login button{background:#143a20;color:#79ff9c;border:1px solid #24ff7044}.x100-login:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#0009 3px 4px);pointer-events:none}@keyframes x100-cursor{50%{opacity:0}}`,
  `.x100-login{padding-left:86px;overflow:visible}.x100-vault{position:absolute;left:12px;top:50%;width:62px;height:62px;border-radius:50%;transform:translateY(-50%);background:radial-gradient(circle,#23262d 0 25%,#6c727d 26% 31%,#17191f 32% 52%,#9ca3af 53% 57%,#15171c 58%);box-shadow:inset 0 2px 5px #fff5,0 12px 25px #0007;transition:transform .9s cubic-bezier(.2,.9,.2,1.1)}.x100-vault:before{content:"✣";position:absolute;inset:0;display:grid;place-items:center;color:#d2d6dd;font-size:30px}.x100-login.success .x100-vault{transform:translateY(-50%) rotate(390deg) scale(.88);box-shadow:0 0 25px #2dd4bf66}.x100-login.success h3{color:#2dd4bf}`,
]

function loginBase(extra = '') {
  return `.x100-login{position:relative;width:250px;padding:20px;border:1px solid #ffffff18;border-radius:20px;background:#10131a;color:#fff;transform-style:preserve-3d}.x100-login h3{margin:0 0 3px;font:800 18px Inter,sans-serif;letter-spacing:-.04em}.x100-login small{display:block;margin-bottom:14px;color:#788191;font:500 10px Inter,sans-serif}.x100-login input{display:block;width:100%;height:37px;margin:7px 0;border:1px solid #ffffff12;border-radius:10px;background:#171a22;color:#fff;padding:0 10px;outline:none}.x100-login button{width:100%;height:38px;margin-top:7px;border:0;border-radius:10px;background:#756cff;color:#fff;font-weight:800;cursor:pointer}.x100-face{display:none}${extra}`
}

function buildLogin(index: number, idea: Idea): Built {
  const face = index === 3 ? `<span class="x100-face"></span>` : ''
  const vault = index === 9 ? `<span class="x100-vault"></span>` : ''
  const html = `<form class="x100-login">${vault}${face}<h3>${esc(idea[0].replace(' Login', ''))}</h3><small>Welcome back to RED UI</small><input aria-label="Email" placeholder="email@red.ui"><input class="x100-password" aria-label="Password" type="password" placeholder="••••••••"><button type="button">Continue</button></form>`
  let js: string | undefined
  if (index === 0) js = `const c=document.querySelector('.x100-login');c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.setProperty('--ry',(x*12)+'deg');c.style.setProperty('--rx',(-y*10)+'deg')});c.addEventListener('pointerleave',()=>{c.style.setProperty('--rx','0deg');c.style.setProperty('--ry','0deg')})`
  if (index === 2 || index === 9) js = `const c=document.querySelector('.x100-login'),b=c.querySelector('button');b.addEventListener('click',()=>{c.classList.remove('success');void c.offsetWidth;c.classList.add('success');setTimeout(()=>c.classList.remove('success'),1500)})`
  if (index === 3) js = `const c=document.querySelector('.x100-login'),p=c.querySelector('.x100-password');p.addEventListener('focus',()=>c.classList.add('looking-away'));p.addEventListener('blur',()=>c.classList.remove('looking-away'))`
  return { html, css: loginBase(loginVariantCss[index]), js }
}

const dashboardIdeas: Idea[] = [
  ['Glass Layer Dashboard', 'Layered translucent widgets use different blur strengths to create depth.', ['dashboard', 'glass', 'blur']],
  ['Z-Depth Dashboard', 'Dashboard panels sit on visible Z-levels like a tiny spatial workspace.', ['dashboard', '3d', 'depth']],
  ['Parallax Dashboard', 'The scene shifts in multiple layers as the pointer moves across it.', ['dashboard', 'parallax', 'pointer']],
  ['Extruded Chart Dashboard', 'Chart columns physically rise out of the surface in perspective.', ['dashboard', 'chart', '3d']],
  ['Floating KPI Dashboard', 'Metric cards drift with tiny independent rotations and shadows.', ['dashboard', 'kpi', 'floating']],
  ['Aurora Dashboard', 'Animated aurora blobs travel behind a translucent dashboard shell.', ['dashboard', 'aurora', 'ambient']],
  ['Reactive Background Dashboard', 'A radial light field follows pointer movement behind the widgets.', ['dashboard', 'reactive', 'cursor']],
  ['Ambient Lighting Dashboard', 'Hovering a metric changes the ambient glow around the entire scene.', ['dashboard', 'ambient', 'lighting']],
  ['Spotlight Dashboard', 'The cursor acts like a moving spotlight revealing the dashboard surface.', ['dashboard', 'spotlight', 'cursor']],
  ['Depth Blur Dashboard', 'Back-layer widgets blur while the focused foreground card remains sharp.', ['dashboard', 'depth', 'blur']],
]

const dashboardVariants = [
  `.x100-dash{background:#ffffff0a;backdrop-filter:blur(18px);box-shadow:0 25px 55px #0006,inset 0 1px #fff2}.x100-kpi{background:#ffffff0d;backdrop-filter:blur(9px)}.x100-kpi:nth-child(2){backdrop-filter:blur(18px)}.x100-kpi:nth-child(3){backdrop-filter:blur(26px)}`,
  `.x100-dash{perspective:700px;transform-style:preserve-3d}.x100-kpi{transform:translateZ(25px);box-shadow:0 18px 22px #0006}.x100-kpi:nth-child(2){transform:translateZ(48px) rotateY(-3deg)}.x100-kpi:nth-child(3){transform:translateZ(15px) rotateY(3deg)}.x100-chart{transform:translateZ(35px) rotateX(4deg);transform-style:preserve-3d}`,
  `.x100-dash{--dx:0px;--dy:0px}.x100-kpi{transform:translate(calc(var(--dx)*.25),calc(var(--dy)*.25))}.x100-kpi:nth-child(2){transform:translate(calc(var(--dx)*-.35),calc(var(--dy)*-.35))}.x100-chart{transform:translate(calc(var(--dx)*.15),calc(var(--dy)*-.15))}.x100-dash:before{transform:translate(calc(var(--dx)*-.5),calc(var(--dy)*-.5))}`,
  `.x100-chart{height:92px;display:flex;align-items:end;gap:8px;perspective:500px;transform:rotateX(8deg)}.x100-bar{width:18px;background:linear-gradient(#22d3ee,#5046d8);border-radius:5px 5px 2px 2px;box-shadow:8px 8px 0 #292372,0 0 16px #22d3ee22;transform:rotateY(-6deg);transform-origin:bottom;animation:x100-bars-rise 2.6s ease-in-out infinite alternate}.x100-bar:nth-child(2){animation-delay:.2s}.x100-bar:nth-child(3){animation-delay:.4s}.x100-bar:nth-child(4){animation-delay:.6s}@keyframes x100-bars-rise{to{transform:rotateY(-6deg) scaleY(.72)}}`,
  `.x100-kpi{animation:x100-kpi-float 4s ease-in-out infinite;box-shadow:0 20px 35px #0007}.x100-kpi:nth-child(2){animation-delay:.7s;transform:rotate(2deg)}.x100-kpi:nth-child(3){animation-delay:1.3s;transform:rotate(-2deg)}@keyframes x100-kpi-float{50%{translate:0 -9px;rotate:1.5deg}}`,
  `.x100-dash{overflow:hidden;background:#10131aaa}.x100-dash:before,.x100-dash:after{content:"";position:absolute;width:180px;height:130px;border-radius:50%;filter:blur(45px);opacity:.45;animation:x100-aurora 5s ease-in-out infinite alternate}.x100-dash:before{background:#756cff;left:-45px;top:-35px}.x100-dash:after{background:#22d3ee;right:-60px;bottom:-40px;animation-delay:1.2s}.x100-kpi,.x100-chart{position:relative;z-index:1;background:#ffffff0b;backdrop-filter:blur(16px)}@keyframes x100-aurora{to{transform:translate(65px,45px) scale(1.25);filter:blur(52px) hue-rotate(35deg)}}`,
  `.x100-dash{--px:50%;--py:50%;background:radial-gradient(circle at var(--px) var(--py),#756cff35,transparent 32%),#0d1016;transition:background .08s}.x100-kpi{background:#ffffff08}.x100-chart{background:linear-gradient(180deg,#ffffff09,transparent)}`,
  `.x100-dash{transition:box-shadow .3s}.x100-kpi{transition:background .25s,box-shadow .25s,transform .25s}.x100-kpi:nth-child(1):hover{background:#756cff22;box-shadow:0 0 28px #756cff33;transform:translateY(-4px)}.x100-kpi:nth-child(2):hover{background:#22d3ee18;box-shadow:0 0 28px #22d3ee33;transform:translateY(-4px)}.x100-kpi:nth-child(3):hover{background:#f472b618;box-shadow:0 0 28px #f472b633;transform:translateY(-4px)}`,
  `.x100-dash{--px:50%;--py:50%;background:#080a0e}.x100-dash:after{content:"";position:absolute;inset:0;background:radial-gradient(circle 72px at var(--px) var(--py),#ffffff19,transparent 75%);pointer-events:none;mix-blend-mode:screen}.x100-kpi,.x100-chart{background:#ffffff05}`,
  `.x100-kpi,.x100-chart{filter:blur(3px);opacity:.6;transition:filter .3s,opacity .3s,transform .3s}.x100-kpi:first-child{filter:none;opacity:1;transform:translateZ(20px);box-shadow:0 18px 35px #0007}.x100-kpi:hover,.x100-chart:hover{filter:none;opacity:1;transform:translateY(-5px) scale(1.02)}`,
]

function buildDashboard(index: number, idea: Idea): Built {
  const html = `<div class="x100-dash"><header><b>${esc(idea[0].replace(' Dashboard', ''))}</b><i>● LIVE</i></header><div class="x100-kpis"><article class="x100-kpi"><small>Energy</small><strong>84%</strong></article><article class="x100-kpi"><small>Focus</small><strong>7.2h</strong></article><article class="x100-kpi"><small>Flow</small><strong>+28</strong></article></div><div class="x100-chart"><span class="x100-bar" style="height:48%"></span><span class="x100-bar" style="height:78%"></span><span class="x100-bar" style="height:61%"></span><span class="x100-bar" style="height:88%"></span></div></div>`
  const base = `.x100-dash{position:relative;width:300px;padding:15px;border:1px solid #ffffff13;border-radius:19px;background:#10131a;color:#fff;overflow:visible;transform-style:preserve-3d}.x100-dash header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;font:800 12px Inter,sans-serif}.x100-dash header i{font-style:normal;color:#2dd4bf;font-size:8px;letter-spacing:.08em}.x100-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.x100-kpi{padding:10px;border:1px solid #ffffff0f;border-radius:12px;background:#171a22;transition:.3s}.x100-kpi small{display:block;color:#78808e;font:600 8px Inter,sans-serif}.x100-kpi strong{display:block;margin-top:4px;font:900 15px Inter,sans-serif}.x100-chart{height:82px;margin-top:10px;padding:10px;border-radius:12px;background:#0b0d12;display:flex;align-items:end;gap:8px}.x100-bar{display:block;flex:1;border-radius:5px 5px 2px 2px;background:linear-gradient(#756cff,#4438b8)}`
  let js: string | undefined
  if ([2, 6, 8].includes(index)) js = `const d=document.querySelector('.x100-dash');d.addEventListener('pointermove',e=>{const r=d.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;d.style.setProperty('--px',(x/r.width*100)+'%');d.style.setProperty('--py',(y/r.height*100)+'%');d.style.setProperty('--dx',(x-r.width/2)*.12+'px');d.style.setProperty('--dy',(y-r.height/2)*.12+'px')});d.addEventListener('pointerleave',()=>{d.style.setProperty('--dx','0px');d.style.setProperty('--dy','0px')})`
  return { html, css: base + dashboardVariants[index], js }
}

const cardIdeas: Idea[] = [
  ['3D Credit Card', 'A premium card tilts in perspective and shifts its metallic reflection with the cursor.', ['card', 'credit', '3d']],
  ['Spatial Flip Card', 'The front rotates away in 3D to reveal a fully designed back side.', ['card', 'flip', '3d']],
  ['Expandable Card', 'A compact card grows into a larger detail surface when clicked.', ['card', 'expand', 'motion']],
  ['Elastic Edge Card', 'Pointer movement bends the card with a rubber-like skew and spring return.', ['card', 'elastic', 'physics']],
  ['Magnetic Pair Cards', 'Two small cards subtly attract and repel while you move across the scene.', ['card', 'magnetic', 'pair']],
  ['Physical Stack Cards', 'A deck of layers fans out and the top card can be pushed aside.', ['card', 'stack', 'depth']],
  ['Spring Polaroid Card', 'A photographic paper card hangs at an angle and springs on hover.', ['card', 'polaroid', 'spring']],
  ['Heat Danger Card', 'A danger card emits animated flames and shimmering heat-like glow.', ['card', 'danger', 'heat']],
  ['Frozen Disabled Card', 'An inactive card appears covered in frost, ice highlights and snow grain.', ['card', 'frozen', 'disabled']],
  ['Liquid Interior Card', 'Colored liquid blobs drift behind the card content like a tiny lava lamp.', ['card', 'liquid', 'blob']],
]

function buildCard(index: number, idea: Idea): Built {
  const baseHtml = `<article class="x100-card"><div class="x100-card-front"><small>RED / 0${index + 1}</small><h3>${esc(idea[0])}</h3><p>Interactive material study</p><b>↗</b></div><div class="x100-card-back"><strong>BACK SIDE</strong><span>depth · motion · light</span></div><i class="x100-blob-a"></i><i class="x100-blob-b"></i></article>`
  const base = `.x100-card{--rx:0deg;--ry:0deg;position:relative;width:240px;height:150px;border-radius:20px;color:#fff;transform-style:preserve-3d;perspective:700px}.x100-card-front,.x100-card-back{position:absolute;inset:0;padding:18px;border:1px solid #ffffff15;border-radius:inherit;background:linear-gradient(145deg,#191d27,#0e1016);box-shadow:0 22px 42px #0007;backface-visibility:hidden;overflow:hidden}.x100-card small{color:#737b8b;font:700 8px Inter,sans-serif;letter-spacing:.1em}.x100-card h3{margin:21px 0 4px;font:900 17px Inter,sans-serif;letter-spacing:-.04em}.x100-card p{margin:0;color:#7d8594;font:500 9px Inter,sans-serif}.x100-card-front>b{position:absolute;right:17px;bottom:15px}.x100-card-back{display:grid;place-items:center;align-content:center;gap:8px;transform:rotateY(180deg);background:#756cff}.x100-card-back span{font-size:9px;opacity:.65}.x100-blob-a,.x100-blob-b{display:none}`
  const variants = [
    `.x100-card-front{background:linear-gradient(115deg,#11141b,#272b33 38%,#a2a8b1 48%,#30343c 58%,#12151a);background-size:220% 100%;background-position:var(--px,50%) center;transform:rotateX(var(--rx)) rotateY(var(--ry));transition:transform .1s,background-position .1s}.x100-card-front:after{content:"4532  ••••  ••••  1987";position:absolute;left:18px;bottom:16px;font:700 9px monospace;color:#d8dde5}.x100-card p,.x100-card-front>b{display:none}`,
    `.x100-card{transition:transform .7s cubic-bezier(.2,.8,.2,1)}.x100-card:hover{transform:rotateY(180deg) translateY(-4px)}`,
    `.x100-card{transition:transform .55s cubic-bezier(.2,.9,.2,1),width .55s,height .55s}.x100-card.open{width:300px;height:210px;transform:translateY(-10px)}.x100-card.open .x100-card-front{background:linear-gradient(145deg,#212638,#12151e)}.x100-card.open h3{font-size:22px}.x100-card-front{cursor:pointer}`,
    `.x100-card-front{transform:perspective(650px) rotateX(var(--rx)) rotateY(var(--ry)) skew(var(--sx,0deg),var(--sy,0deg));transition:transform .12s ease-out}.x100-card:hover .x100-card-front{box-shadow:0 28px 48px #0008,0 0 30px #756cff22}`,
    `.x100-card{width:270px}.x100-card-front{width:145px;right:auto;transform:translateX(var(--a,0px)) rotate(var(--ar,-3deg));transition:transform .12s}.x100-card-back{display:block;left:auto;width:145px;transform:translateX(var(--b,0px)) rotate(var(--br,3deg));background:linear-gradient(145deg,#171a22,#0b0d12);transition:transform .12s}.x100-card-back strong{display:block;margin-top:35px}.x100-card-back span{display:block;margin-top:8px}`,
    `.x100-card:before,.x100-card:after{content:"";position:absolute;inset:0;border-radius:20px;background:#1b1e27;border:1px solid #ffffff10;box-shadow:0 18px 30px #0005;transition:.4s}.x100-card:before{transform:translate(10px,10px) rotate(4deg);z-index:-1}.x100-card:after{transform:translate(-9px,14px) rotate(-5deg);z-index:-2}.x100-card:hover:before{transform:translate(30px,6px) rotate(10deg)}.x100-card:hover:after{transform:translate(-28px,8px) rotate(-11deg)}.x100-card:hover .x100-card-front{transform:translateY(-8px)}`,
    `.x100-card{transform:rotate(-4deg);transition:transform .5s cubic-bezier(.2,1.4,.3,1)}.x100-card-front{background:#f2eadc;color:#28231d;border:8px solid #f7f0e5;border-bottom-width:28px;box-shadow:0 20px 35px #0007}.x100-card small,.x100-card p{color:#776b5c}.x100-card:hover{transform:rotate(2deg) translateY(-9px) scale(1.03)}`,
    `.x100-card-front{background:linear-gradient(145deg,#361016,#14090b);border-color:#ff5b7055;box-shadow:0 0 22px #fb718544,0 22px 42px #0008}.x100-card:before,.x100-card:after{content:"";position:absolute;bottom:-12px;width:50px;height:60px;background:radial-gradient(ellipse at bottom,#ffdd75 0 8%,#ff7b32 24%,#ff304f 48%,transparent 70%);filter:blur(3px);animation:x100-flame 1s ease-in-out infinite alternate;z-index:-1}.x100-card:before{left:34px}.x100-card:after{right:28px;animation-delay:.35s}@keyframes x100-flame{to{transform:translateY(-15px) scale(.75) rotate(7deg);filter:blur(5px)}}`,
    `.x100-card-front{background:linear-gradient(145deg,#d7f4ff22,#7dd3fc0b);border-color:#dff7ff66;backdrop-filter:blur(10px);filter:saturate(.5);box-shadow:inset 0 0 25px #bff3ff22,0 20px 40px #0007}.x100-card-front:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 12% 18%,#fff 0 1px,transparent 2px),radial-gradient(circle at 80% 35%,#fff 0 1px,transparent 2px),linear-gradient(135deg,#fff3,transparent 25%);background-size:18px 18px,23px 23px,100% 100%;opacity:.55}.x100-card h3,.x100-card p{opacity:.55}`,
    `.x100-card-front{background:#0d0f15;overflow:hidden}.x100-blob-a,.x100-blob-b{display:block;position:absolute;width:150px;height:100px;border-radius:45% 55% 60% 40%;filter:blur(18px);opacity:.55;z-index:0;animation:x100-liquid-card 5s ease-in-out infinite}.x100-blob-a{background:#756cff;left:-35px;top:-20px}.x100-blob-b{background:#22d3ee;right:-45px;bottom:-30px;animation-delay:1.4s}.x100-card-front>*{position:relative;z-index:2}@keyframes x100-liquid-card{50%{transform:translate(70px,45px) rotate(140deg) scale(1.2)}}`,
  ]
  let js: string | undefined
  if ([0, 3].includes(index)) js = `const c=document.querySelector('.x100-card'),f=c.querySelector('.x100-card-front');c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;f.style.setProperty('--ry',(x*12)+'deg');f.style.setProperty('--rx',(-y*10)+'deg');f.style.setProperty('--sx',(x*2)+'deg');f.style.setProperty('--sy',(y*2)+'deg');f.style.setProperty('--px',((x+.5)*100)+'%')});c.addEventListener('pointerleave',()=>{['--rx','--ry','--sx','--sy'].forEach(k=>f.style.setProperty(k,'0deg'))})`
  if (index === 2) js = `const c=document.querySelector('.x100-card');c.querySelector('.x100-card-front').addEventListener('click',()=>c.classList.toggle('open'))`
  if (index === 4) js = `const c=document.querySelector('.x100-card'),a=c.querySelector('.x100-card-front'),b=c.querySelector('.x100-card-back');c.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5;a.style.setProperty('--a',(x*22)+'px');b.style.setProperty('--b',(-x*22)+'px');a.style.setProperty('--ar',(-3+x*8)+'deg');b.style.setProperty('--br',(3-x*8)+'deg')})`
  return { html: baseHtml, css: base + variants[index], js }
}

const navIdeas: Idea[] = [
  ['3D Navigation Dock', 'A floating icon dock scales and tilts controls as the pointer approaches.', ['navigation', 'dock', '3d']],
  ['Liquid Bubble Navigation', 'A glossy bubble slides behind the active navigation destination.', ['navigation', 'bubble', 'active']],
  ['Morphing Navigation', 'A compact pill expands into a full navigation bar on demand.', ['navigation', 'morph', 'expand']],
  ['Circular Burst Menu', 'Menu actions explode radially around a central trigger.', ['navigation', 'radial', 'menu']],
  ['Orbital Menu', 'Small navigation nodes orbit a luminous central sphere.', ['navigation', 'orbit', 'orb']],
  ['Spatial Z Menu', 'Navigation destinations occupy visibly different Z-depth planes.', ['navigation', 'spatial', 'depth']],
  ['Elastic Sidebar', 'A narrow sidebar stretches open like rubber when engaged.', ['navigation', 'sidebar', 'elastic']],
  ['Deep Glass Sidebar', 'Blur and translucency increase as the glass sidebar opens.', ['navigation', 'glass', 'sidebar']],
  ['Floating Island Navigation', 'A detached island of navigation floats above the surface.', ['navigation', 'floating', 'island']],
  ['Magnetic Cursor Navigation', 'Nearby nav items lean and drift toward the pointer.', ['navigation', 'magnetic', 'cursor']],
]

function buildNav(index: number, idea: Idea): Built {
  const icons = ['⌂','◈','✦','◎','⚙']
  const html = `<nav class="x100-nav"><button class="x100-trigger" type="button">✦</button><span class="x100-active"></span>${icons.map((x,i)=>`<button class="x100-nav-item${i===0?' active':''}" type="button" aria-label="item ${i+1}">${x}</button>`).join('')}</nav>`
  const base = `.x100-nav{position:relative;display:flex;align-items:center;gap:7px;padding:7px;border:1px solid #ffffff14;border-radius:18px;background:#11141bcc;color:#fff;box-shadow:0 18px 38px #0006;transform-style:preserve-3d}.x100-nav button{position:relative;width:42px;height:42px;border:0;border-radius:12px;background:#ffffff07;color:#9da4b2;font-size:17px;cursor:pointer;transition:.3s;z-index:2}.x100-nav-item.active{color:#fff}.x100-trigger{display:none!important}.x100-active{position:absolute;width:42px;height:42px;left:7px;top:7px;border-radius:12px;background:#756cff33;box-shadow:inset 0 0 0 1px #756cff44;transition:left .45s cubic-bezier(.2,.8,.2,1)}`
  const variants = [
    `.x100-nav{perspective:500px}.x100-nav-item:hover{transform:translateY(-8px) rotateX(16deg) scale(1.35);color:#fff;box-shadow:0 12px 22px #0006;background:#756cff33}.x100-nav-item:has(+.x100-nav-item:hover),.x100-nav-item:hover+.x100-nav-item{transform:translateY(-3px) scale(1.12)}`,
    `.x100-active{border-radius:50%;background:radial-gradient(circle at 35% 25%,#fff8,#756cffaa 32%,#4338ca 70%);box-shadow:0 0 20px #756cff66}.x100-nav-item{background:transparent}.x100-nav{border-radius:999px}.x100-nav-item{border-radius:50%}`,
    `.x100-nav{width:58px;overflow:hidden;transition:width .55s cubic-bezier(.2,.9,.2,1);justify-content:flex-start}.x100-trigger{display:block!important;flex:0 0 42px}.x100-nav .x100-nav-item,.x100-nav .x100-active{opacity:0;transform:translateX(-12px);transition:.35s}.x100-nav.open{width:290px}.x100-nav.open .x100-nav-item,.x100-nav.open .x100-active{opacity:1;transform:none}.x100-nav.open .x100-trigger{transform:rotate(45deg);color:#fff}`,
    `.x100-nav{width:160px;height:160px;border-radius:50%;padding:0;background:transparent;border:0;box-shadow:none}.x100-trigger{display:block!important;position:absolute!important;left:59px;top:59px;z-index:5;background:#756cff!important;color:white!important;border-radius:50%!important;box-shadow:0 0 24px #756cff55}.x100-nav-item{position:absolute!important;left:59px;top:59px;border-radius:50%!important;opacity:0;transform:translate(0,0) scale(.2);transition:.5s cubic-bezier(.2,1.2,.2,1)}.x100-active{display:none}.x100-nav.open .x100-nav-item{opacity:1;transform:translate(var(--x),var(--y)) scale(1)}.x100-nav-item:nth-of-type(2){--x:0px;--y:-58px}.x100-nav-item:nth-of-type(3){--x:55px;--y:-18px}.x100-nav-item:nth-of-type(4){--x:34px;--y:49px}.x100-nav-item:nth-of-type(5){--x:-34px;--y:49px}.x100-nav-item:nth-of-type(6){--x:-55px;--y:-18px}`,
    `.x100-nav{width:180px;height:180px;border-radius:50%;padding:0;background:transparent;border:1px solid #756cff33;animation:x100-orbit-menu 8s linear infinite}.x100-trigger{display:block!important;position:absolute!important;left:69px;top:69px;border-radius:50%!important;background:radial-gradient(circle at 35% 25%,#fff,#8b5cf6 18%,#30268f 65%)!important;color:transparent!important;box-shadow:0 0 32px #756cff66}.x100-nav-item{position:absolute!important;left:69px;top:69px;border-radius:50%!important;background:#12151c!important;border:1px solid #ffffff18!important;transform:rotate(var(--a)) translateX(72px) rotate(calc(var(--a)*-1));animation:x100-counter-menu 8s linear infinite}.x100-nav-item:nth-of-type(2){--a:0deg}.x100-nav-item:nth-of-type(3){--a:72deg}.x100-nav-item:nth-of-type(4){--a:144deg}.x100-nav-item:nth-of-type(5){--a:216deg}.x100-nav-item:nth-of-type(6){--a:288deg}.x100-active{display:none}@keyframes x100-orbit-menu{to{rotate:360deg}}@keyframes x100-counter-menu{to{rotate:-360deg}}`,
    `.x100-nav{perspective:700px}.x100-nav-item:nth-of-type(2){transform:translateZ(35px)}.x100-nav-item:nth-of-type(3){transform:translateZ(12px) translateY(-5px)}.x100-nav-item:nth-of-type(4){transform:translateZ(55px) translateY(-10px);box-shadow:0 14px 22px #0007}.x100-nav-item:nth-of-type(5){transform:translateZ(20px)}.x100-nav-item:nth-of-type(6){transform:translateZ(42px) translateY(-6px)}`,
    `.x100-nav{width:58px;height:280px;flex-direction:column;overflow:hidden;transition:width .5s cubic-bezier(.2,.9,.2,1);border-radius:20px}.x100-nav:hover{width:190px}.x100-nav-item{width:100%!important;flex:0 0 42px;text-align:left;padding-left:13px}.x100-nav-item:after{content:"  MENU";opacity:0;margin-left:18px;font:700 9px Inter,sans-serif;letter-spacing:.12em;transition:.3s}.x100-nav:hover .x100-nav-item:after{opacity:.7}.x100-active{display:none}`,
    `.x100-nav{height:260px;flex-direction:column;background:#ffffff08;backdrop-filter:blur(8px);transition:backdrop-filter .4s,background .4s}.x100-nav:hover{backdrop-filter:blur(24px) saturate(170%);background:#ffffff12}.x100-active{display:none}.x100-nav-item{background:#ffffff08}`,
    `.x100-nav{border-radius:999px;animation:x100-island 4s ease-in-out infinite;box-shadow:0 24px 45px #0008,0 0 30px #756cff15}.x100-nav-item{border-radius:50%}.x100-active{border-radius:50%}@keyframes x100-island{50%{transform:translateY(-8px) rotateX(3deg)}}`,
    `.x100-nav{--mx:0px;--my:0px}.x100-nav-item{transform:translate(calc(var(--mx)*var(--f,.2)),calc(var(--my)*var(--f,.2))) rotateX(calc(var(--my)*-.3)) rotateY(calc(var(--mx)*.3));transition:transform .1s}.x100-nav-item:nth-of-type(2){--f:.12}.x100-nav-item:nth-of-type(3){--f:.2}.x100-nav-item:nth-of-type(4){--f:.28}.x100-nav-item:nth-of-type(5){--f:.18}.x100-nav-item:nth-of-type(6){--f:.1}`,
  ]
  let js = `const n=document.querySelector('.x100-nav'),items=[...n.querySelectorAll('.x100-nav-item')],a=n.querySelector('.x100-active');items.forEach((b,i)=>b.addEventListener('click',()=>{items.forEach(x=>x.classList.remove('active'));b.classList.add('active');if(a)a.style.left=(7+i*49)+'px'}));`
  if ([2,3].includes(index)) js += `const t=n.querySelector('.x100-trigger');t.addEventListener('click',()=>n.classList.toggle('open'));`
  if (index === 9) js += `n.addEventListener('pointermove',e=>{const r=n.getBoundingClientRect();n.style.setProperty('--mx',((e.clientX-r.left-r.width/2)*.08)+'px');n.style.setProperty('--my',((e.clientY-r.top-r.height/2)*.08)+'px')});n.addEventListener('pointerleave',()=>{n.style.setProperty('--mx','0px');n.style.setProperty('--my','0px')});`
  return { html, css: base + variants[index], js }
}

const toggleIdeas: Idea[] = [
  ['Physical 3D Toggle', 'A tiny mechanical switch with a recessed track, hard shadow and physical travel.', ['toggle', '3d', 'physical']],
  ['Liquid Flow Toggle', 'Colored liquid appears to flow across the track as state changes.', ['toggle', 'liquid', 'flow']],
  ['Day Night Toggle', 'A miniature sun sets while a moon rises across the switch.', ['toggle', 'day-night', 'sun']],
  ['Weather Toggle', 'Rain clouds transform into a bright sun when toggled on.', ['toggle', 'weather', 'rain']],
  ['Electric Power Toggle', 'A pulse of electricity races through the track on activation.', ['toggle', 'power', 'electric']],
  ['Portal Toggle', 'The control orb shrinks into one portal and appears from the other.', ['toggle', 'portal', 'orb']],
  ['Planet Toggle', 'A small planet moves between two orbital positions around a star.', ['toggle', 'planet', 'orbit']],
  ['Rocket Toggle', 'A tiny rocket launches across the track between both states.', ['toggle', 'rocket', 'motion']],
  ['Character Walk Toggle', 'A miniature character walks from the off side to the on side.', ['toggle', 'character', 'walk']],
  ['Morph Icon Toggle', 'The central symbol morphs from a plus into a check instead of sliding.', ['toggle', 'morph', 'icon']],
]

function buildToggle(index: number, idea: Idea): Built {
  const html = `<label class="x100-toggle"><input type="checkbox"><span class="x100-track"><i class="x100-knob"></i><b class="x100-deco"></b><em></em></span></label>`
  const base = `.x100-toggle{position:relative;display:inline-block;width:92px;height:46px;cursor:pointer}.x100-toggle input{position:absolute;opacity:0}.x100-track{position:absolute;inset:0;border:1px solid #ffffff18;border-radius:999px;background:#1b1e25;box-shadow:inset 0 5px 12px #0007,0 12px 25px #0005;overflow:hidden;transition:.5s}.x100-knob{position:absolute;width:34px;height:34px;left:6px;top:5px;border-radius:50%;background:linear-gradient(#fff,#cbd0da);box-shadow:0 6px 12px #0007;transition:.55s cubic-bezier(.2,.9,.2,1.2);z-index:3}.x100-toggle input:checked+.x100-track .x100-knob{transform:translateX(46px)}.x100-deco,.x100-track em{position:absolute;pointer-events:none}`
  const variants = [
    `.x100-track{border-radius:15px;background:linear-gradient(#343842,#171920);box-shadow:inset 0 5px 0 #0c0d11,0 8px 0 #090a0d,0 16px 25px #0006}.x100-knob{border-radius:11px;background:linear-gradient(#89909b,#3e434d);box-shadow:inset 0 2px #fff4,0 5px 0 #17191e}.x100-toggle input:checked+.x100-track{background:linear-gradient(#276d62,#103a34)}.x100-toggle input:checked+.x100-track .x100-knob{background:linear-gradient(#67e8d4,#2bb6a0)}`,
    `.x100-track:before{content:"";position:absolute;left:-45px;top:-18px;width:105px;height:82px;border-radius:48% 52% 60% 40%;background:linear-gradient(145deg,#22d3ee,#756cff);transition:transform .7s cubic-bezier(.2,.8,.2,1);filter:blur(2px)}.x100-toggle input:checked+.x100-track:before{transform:translateX(78px) rotate(160deg)}.x100-knob{background:#ffffffdd;backdrop-filter:blur(7px)}`,
    `.x100-track{background:linear-gradient(#88c9ff,#dff4ff)}.x100-knob{background:radial-gradient(circle at 35% 35%,#fff,#ffd45a 28%,#ff9e38 70%);box-shadow:0 0 18px #ffd45a}.x100-toggle input:checked+.x100-track{background:linear-gradient(#101632,#29244c)}.x100-toggle input:checked+.x100-track .x100-knob{background:radial-gradient(circle at 35% 35%,#fff,#dbe8ff 30%,#8b9bb8 72%);box-shadow:0 0 15px #c8dcff}.x100-track:after{content:"✦ ·";position:absolute;right:12px;top:10px;color:white;opacity:0;transition:.4s}.x100-toggle input:checked+.x100-track:after{opacity:.8}`,
    `.x100-track{background:linear-gradient(#233b56,#152435)}.x100-deco:before{content:"☁";position:absolute;left:13px;top:7px;color:#b9d5ed;font-size:24px;transition:.5s}.x100-deco:after{content:"⋮ ⋮";position:absolute;left:17px;top:23px;color:#7dd3fc;letter-spacing:4px;font-size:12px;transition:.5s}.x100-toggle input:checked+.x100-track{background:linear-gradient(#74c8ff,#c4efff)}.x100-toggle input:checked+.x100-track .x100-deco:before{content:"☀";left:55px;color:#ffd44e;transform:rotate(180deg)}.x100-toggle input:checked+.x100-track .x100-deco:after{opacity:0}`,
    `.x100-track{background:#080c10;border-color:#22d3ee55}.x100-track:before{content:"";position:absolute;left:11px;right:11px;top:21px;height:2px;background:#16414a;box-shadow:0 0 5px #22d3ee}.x100-track:after{content:"";position:absolute;left:10px;top:19px;width:10px;height:6px;background:#fff;clip-path:polygon(0 40%,42% 40%,55% 0,100% 50%,58% 50%,46% 100%);opacity:0}.x100-toggle input:checked+.x100-track:after{opacity:1;animation:x100-electric 1s linear infinite}.x100-toggle input:checked+.x100-track{box-shadow:inset 0 0 18px #22d3ee22,0 0 24px #22d3ee33}@keyframes x100-electric{to{transform:translateX(58px)}}`,
    `.x100-track:before,.x100-track:after{content:"";position:absolute;top:8px;width:30px;height:30px;border-radius:50%;border:1px solid #756cff88;box-shadow:inset 0 0 14px #756cff66,0 0 14px #756cff33}.x100-track:before{left:7px}.x100-track:after{right:7px}.x100-knob{background:radial-gradient(circle,#fff,#bcb6ff 28%,#4c3fc5 65%)}.x100-toggle input:checked+.x100-track .x100-knob{animation:x100-portal-knob .55s ease both}@keyframes x100-portal-knob{40%{transform:translateX(20px) scale(.05)}60%{transform:translateX(28px) scale(.05)}100%{transform:translateX(46px) scale(1)}}`,
    `.x100-track{background:radial-gradient(circle at 20px 23px,#ffdb65 0 7px,#ff9c2f 8px 9px,transparent 10px),#10162a}.x100-knob{width:24px;height:24px;top:10px;left:11px;background:radial-gradient(circle at 35% 30%,#d9f2ff,#5994c7 55%,#244361);box-shadow:0 0 0 6px #ffffff0b,0 0 18px #60a5fa;transform-origin:35px 12px}.x100-toggle input:checked+.x100-track .x100-knob{transform:translateX(46px) rotate(360deg)}`,
    `.x100-knob{background:none;box-shadow:none;font-style:normal}.x100-knob:before{content:"🚀";position:absolute;inset:2px;display:grid;place-items:center;font-style:normal;font-size:25px;transform:rotate(45deg);transition:.55s}.x100-track:after{content:"";position:absolute;left:18px;top:31px;width:10px;height:3px;background:#22d3ee;box-shadow:0 0 10px #22d3ee;opacity:.25}.x100-toggle input:checked+.x100-track .x100-knob:before{transform:rotate(45deg) scale(1.15)}.x100-toggle input:checked+.x100-track:after{left:64px;opacity:1}`,
    `.x100-knob{background:none;box-shadow:none}.x100-knob:before{content:"♟";position:absolute;inset:0;display:grid;place-items:center;font-size:27px;color:#f2f4f7;transition:.4s}.x100-toggle input:checked+.x100-track .x100-knob:before{animation:x100-walk .55s steps(4)}@keyframes x100-walk{25%{transform:rotate(-12deg) translateY(-2px)}50%{transform:rotate(12deg)}75%{transform:rotate(-8deg) translateY(-2px)}}`,
    `.x100-knob{left:29px;background:#756cff;color:white;box-shadow:0 0 20px #756cff66}.x100-knob:before,.x100-knob:after{content:"";position:absolute;left:9px;right:9px;top:16px;height:2px;background:#fff;border-radius:2px;transition:.45s}.x100-knob:after{transform:rotate(90deg)}.x100-toggle input:checked+.x100-track .x100-knob{transform:none;background:#2dd4bf;box-shadow:0 0 20px #2dd4bf66}.x100-toggle input:checked+.x100-track .x100-knob:before{transform:translate(-2px,1px) rotate(42deg);width:12px}.x100-toggle input:checked+.x100-track .x100-knob:after{transform:translate(4px,-2px) rotate(-48deg);width:18px}`,
  ]
  return { html, css: base + variants[index] }
}

const searchIdeas: Idea[] = [
  ['Liquid Expand Search', 'The search surface stretches into place with a soft liquid-like edge.', ['search', 'liquid', 'expand']],
  ['Spotlight Search', 'Focusing search darkens the environment while the field becomes a bright stage.', ['search', 'spotlight', 'focus']],
  ['3D Search Portal', 'Results appear in perspective layers behind the main query field.', ['search', 'portal', '3d']],
  ['Particle Clear Search', 'Clearing the query breaks the typed state into small visual particles.', ['search', 'particles', 'clear']],
  ['AI Orb Search', 'A reactive AI orb brightens and pulses according to typed input.', ['search', 'ai', 'orb']],
  ['Voice Wave Search', 'Voice-style bars animate beside the field like a compact audio waveform.', ['search', 'voice', 'wave']],
  ['Search Tunnel', 'Result rows emerge from a perspective tunnel behind the query.', ['search', 'tunnel', 'depth']],
  ['Scanning Magnifier Search', 'An animated magnifying glass sweeps over the result surface.', ['search', 'magnifier', 'scan']],
  ['Glass Command Palette', 'A compact deep-blur command palette inspired by spatial desktop search.', ['search', 'command', 'glass']],
  ['Search Galaxy', 'Search results become tiny orbiting planets around the query core.', ['search', 'galaxy', 'orbit']],
]

function buildSearch(index: number, idea: Idea): Built {
  const html = `<div class="x100-search"><div class="x100-search-row"><i>⌕</i><input value="RED" aria-label="Search"><button type="button">×</button><span class="x100-ai-orb"></span><span class="x100-wave"><b></b><b></b><b></b><b></b></span></div><div class="x100-results"><span>Design systems</span><span>RED motion</span><span>3D components</span></div><em class="x100-magnifier">⌕</em></div>`
  const base = `.x100-search{position:relative;width:280px;color:#fff;perspective:700px}.x100-search-row{position:relative;height:48px;border:1px solid #ffffff18;border-radius:15px;background:#11141b;display:flex;align-items:center;padding:0 11px;gap:8px;box-shadow:0 16px 32px #0006;z-index:4;transition:.4s}.x100-search-row>i{font-style:normal;color:#7d8594;font-size:22px}.x100-search input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:#fff;font:600 12px Inter,sans-serif}.x100-search-row>button{border:0;background:transparent;color:#6f7785;cursor:pointer}.x100-results{margin:7px 8px 0;padding:9px;border:1px solid #ffffff0f;border-radius:12px;background:#0d0f15;display:grid;gap:6px;transition:.4s}.x100-results span{padding:7px 8px;border-radius:8px;background:#ffffff05;color:#9ca3af;font:600 9px Inter,sans-serif}.x100-ai-orb,.x100-wave,.x100-magnifier{display:none}`
  const variants = [
    `.x100-search-row{border-radius:24px 16px 24px 17px;width:185px;transition:width .55s cubic-bezier(.2,.9,.2,1.1),border-radius .55s}.x100-search-row:focus-within{width:280px;border-radius:16px 24px 17px 23px;box-shadow:0 0 24px #756cff22,0 18px 32px #0006}.x100-search-row:before{content:"";position:absolute;inset:-1px;border-radius:inherit;background:linear-gradient(90deg,#756cff33,#22d3ee33,transparent);z-index:-1;filter:blur(5px)}`,
    `.x100-search:before{content:"";position:absolute;inset:-110px;background:#000b;opacity:0;transition:.45s;z-index:-1;border-radius:40px}.x100-search:focus-within:before{opacity:1}.x100-search-row:focus-within{background:#1a1d25;border-color:#fff4;box-shadow:0 0 0 1px #fff2,0 0 45px #ffffff18}.x100-search:focus-within .x100-results{opacity:.35}`,
    `.x100-results{transform:rotateX(28deg) translateY(-12px) translateZ(-65px);transform-origin:top;opacity:.65;box-shadow:0 30px 50px #0009}.x100-search:focus-within .x100-results{transform:rotateX(12deg) translateY(0) translateZ(-25px);opacity:1}.x100-results span:nth-child(2){transform:translateZ(-18px)}.x100-results span:nth-child(3){transform:translateZ(-35px)}`,
    `.x100-search-particle{position:absolute;width:5px;height:5px;border-radius:50%;background:hsl(var(--h) 90% 70%);left:50%;top:24px;z-index:9;animation:x100-search-pop .65s ease-out forwards}@keyframes x100-search-pop{to{transform:translate(var(--x),var(--y)) scale(.1);opacity:0}}`,
    `.x100-search-row{padding-right:47px}.x100-ai-orb{display:block;position:absolute;right:10px;width:27px;height:27px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff,#a78bfa 18%,#4338ca 58%,#111827 72%);box-shadow:0 0 calc(8px + var(--energy,0)*1px) #756cff;transform:scale(calc(1 + var(--energy,0)*.006));transition:.25s}.x100-ai-orb:after{content:"";position:absolute;inset:-5px;border:1px solid #756cff55;border-radius:50%;animation:x100-ai-orbit 3s linear infinite}@keyframes x100-ai-orbit{to{rotate:360deg}}`,
    `.x100-search-row{padding-right:78px}.x100-wave{display:flex;position:absolute;right:10px;height:25px;align-items:center;gap:3px}.x100-wave b{display:block;width:3px;height:8px;border-radius:5px;background:#22d3ee;animation:x100-voice 1s ease-in-out infinite}.x100-wave b:nth-child(2){animation-delay:.12s}.x100-wave b:nth-child(3){animation-delay:.24s}.x100-wave b:nth-child(4){animation-delay:.36s}@keyframes x100-voice{50%{height:24px;background:#756cff}}`,
    `.x100-results{transform-style:preserve-3d;perspective:250px;overflow:hidden;background:radial-gradient(ellipse at top,#756cff22,#0d0f15 55%)}.x100-results span{transform:translateZ(var(--z)) scale(var(--s));animation:x100-tunnel 3s ease-in-out infinite}.x100-results span:nth-child(1){--z:0px;--s:1}.x100-results span:nth-child(2){--z:-45px;--s:.92;animation-delay:.4s}.x100-results span:nth-child(3){--z:-90px;--s:.84;animation-delay:.8s}@keyframes x100-tunnel{50%{transform:translateY(5px) translateZ(12px) scale(1.03)}}`,
    `.x100-magnifier{display:grid;place-items:center;position:absolute;width:38px;height:38px;border:2px solid #fff8;border-radius:50%;top:58px;left:4px;font-style:normal;color:#fff;background:#ffffff08;backdrop-filter:blur(3px);box-shadow:0 8px 18px #0006;animation:x100-magnify 3s ease-in-out infinite}.x100-magnifier:after{content:"";position:absolute;width:16px;height:2px;background:#fff8;right:-11px;bottom:-5px;rotate:45deg;border-radius:2px}@keyframes x100-magnify{50%{left:225px;top:100px;transform:scale(1.16)}}`,
    `.x100-search{padding:10px;border:1px solid #ffffff16;border-radius:20px;background:#ffffff08;backdrop-filter:blur(24px) saturate(160%);box-shadow:0 26px 55px #0007,inset 0 1px #fff2}.x100-search-row{background:#ffffff08}.x100-results{background:#ffffff04}.x100-results span{background:#ffffff08}`,
    `.x100-search{height:195px}.x100-results{position:absolute;inset:62px 0 0;border-radius:50%;background:radial-gradient(circle,#756cff20,transparent 65%);border:0}.x100-results span{position:absolute;width:52px;height:52px;padding:0;border-radius:50%;display:grid;place-items:center;text-align:center;background:radial-gradient(circle at 35% 25%,#fff6,#756cff 16%,#252059 70%);font-size:7px;color:#fff;box-shadow:0 0 16px #756cff44;animation:x100-galaxy 7s linear infinite}.x100-results span:nth-child(1){left:15px;top:45px}.x100-results span:nth-child(2){right:18px;top:18px;animation-direction:reverse}.x100-results span:nth-child(3){left:112px;top:65px;animation-duration:5s}@keyframes x100-galaxy{to{rotate:360deg}}`,
  ]
  let js: string | undefined
  if (index === 3) js = `const s=document.querySelector('.x100-search'),i=s.querySelector('input'),b=s.querySelector('button');b.addEventListener('click',()=>{i.value='';for(let n=0;n<14;n++){const p=document.createElement('i'),a=Math.PI*2*n/14,d=30+Math.random()*50;p.className='x100-search-particle';p.style.setProperty('--x',Math.cos(a)*d+'px');p.style.setProperty('--y',Math.sin(a)*d+'px');p.style.setProperty('--h',String(n*26));s.appendChild(p);setTimeout(()=>p.remove(),700)}})`
  if (index === 4) js = `const i=document.querySelector('.x100-search input'),o=document.querySelector('.x100-ai-orb');const u=()=>o.style.setProperty('--energy',String(Math.min(10,i.value.length)));i.addEventListener('input',u);u()`
  return { html, css: base + variants[index], js }
}

const loaderIdeas: Idea[] = [
  ['Fragmenting 3D Cube Loader', 'A rotating cube briefly separates into visible spatial fragments.', ['loader', 'cube', '3d']],
  ['Liquid Fill Loader', 'A glass capsule fills with an animated liquid surface.', ['loader', 'liquid', 'fill']],
  ['Gravity Ball Loader', 'Small balls repeatedly fall, bounce and settle under simulated gravity.', ['loader', 'gravity', 'physics']],
  ['Multi Orbit Loader', 'Multiple satellites rotate on different orbital planes around a core.', ['loader', 'orbit', '3d']],
  ['Portal Vortex Loader', 'Particles spiral inward toward a dark luminous portal center.', ['loader', 'portal', 'vortex']],
  ['Blur Skeleton Reveal', 'A compact content skeleton repeatedly sharpens out of blur.', ['loader', 'skeleton', 'blur']],
  ['Pixel Assembly Loader', 'Pixels progressively assemble and dissolve into a small interface tile.', ['loader', 'pixel', 'assembly']],
  ['Morph Shape Loader', 'One object continuously transforms between circle, diamond and blob.', ['loader', 'morph', 'shape']],
  ['DNA Helix Loader', 'Two strands of nodes form a rotating depth-like double helix.', ['loader', 'dna', 'helix']],
  ['Black Hole Loader', 'Orbiting dots shrink and disappear as they approach a dark center.', ['loader', 'black-hole', 'gravity']],
]

function buildLoader(index: number, idea: Idea): Built {
  const htmlVariants = [
    `<div class="x100-cube-loader"><i></i><i></i><i></i><i></i><i></i><i></i></div>`,
    `<div class="x100-liquid-loader"><i></i><span>LOADING</span></div>`,
    `<div class="x100-gravity-loader">${'<i></i>'.repeat(5)}<b></b></div>`,
    `<div class="x100-orbit-loader"><b></b><i></i><i></i><i></i></div>`,
    `<div class="x100-vortex-loader">${'<i></i>'.repeat(8)}<b></b></div>`,
    `<div class="x100-skeleton"><i></i><b></b><span></span><span></span><span></span></div>`,
    `<div class="x100-pixel-loader">${'<i></i>'.repeat(16)}</div>`,
    `<div class="x100-morph-loader"></div>`,
    `<div class="x100-dna">${Array.from({length:9},(_,i)=>`<span style="--i:${i}"><i></i><b></b></span>`).join('')}</div>`,
    `<div class="x100-black-hole">${'<i></i>'.repeat(6)}<b></b></div>`,
  ]
  const cssVariants = [
    `.x100-cube-loader{position:relative;width:72px;height:72px;transform-style:preserve-3d;animation:x100-cube-spin 3s linear infinite}.x100-cube-loader i{position:absolute;inset:11px;background:#756cff88;border:1px solid #c4bfff88;box-shadow:inset 0 0 18px #fff2;transition:.4s}.x100-cube-loader i:nth-child(1){transform:translateZ(25px)}.x100-cube-loader i:nth-child(2){transform:rotateY(180deg) translateZ(25px)}.x100-cube-loader i:nth-child(3){transform:rotateY(90deg) translateZ(25px)}.x100-cube-loader i:nth-child(4){transform:rotateY(-90deg) translateZ(25px)}.x100-cube-loader i:nth-child(5){transform:rotateX(90deg) translateZ(25px)}.x100-cube-loader i:nth-child(6){transform:rotateX(-90deg) translateZ(25px)}@keyframes x100-cube-spin{0%,35%{transform:rotateX(20deg) rotateY(0)}50%{transform:rotateX(150deg) rotateY(170deg) scale(1.25)}65%,100%{transform:rotateX(380deg) rotateY(360deg)}}`,
    `.x100-liquid-loader{position:relative;width:82px;height:112px;border:2px solid #ffffff55;border-radius:22px;overflow:hidden;background:#ffffff08;box-shadow:inset 0 0 20px #fff1,0 18px 35px #0007}.x100-liquid-loader i{position:absolute;left:-35%;bottom:-10px;width:170%;height:75%;background:#22d3ee;border-radius:43% 57% 48% 52%;animation:x100-liquid-fill 3s ease-in-out infinite}.x100-liquid-loader i:before{content:"";position:absolute;inset:12px;background:#756cff88;border-radius:50%;filter:blur(18px)}.x100-liquid-loader span{position:absolute;left:0;right:0;bottom:10px;text-align:center;color:#fff;font:800 7px Inter,sans-serif;letter-spacing:.14em;mix-blend-mode:overlay}@keyframes x100-liquid-fill{0%{transform:translateY(80%) rotate(0)}60%{transform:translateY(0) rotate(150deg)}100%{transform:translateY(80%) rotate(360deg)}}`,
    `.x100-gravity-loader{position:relative;width:130px;height:100px;border-bottom:2px solid #ffffff22}.x100-gravity-loader i{position:absolute;top:0;left:14px;width:16px;height:16px;border-radius:50%;background:#756cff;box-shadow:0 0 14px #756cff;animation:x100-gravity 1.45s cubic-bezier(.45,.05,.55,.95) infinite}.x100-gravity-loader i:nth-child(2){left:38px;animation-delay:.12s;background:#22d3ee}.x100-gravity-loader i:nth-child(3){left:62px;animation-delay:.24s;background:#2dd4bf}.x100-gravity-loader i:nth-child(4){left:86px;animation-delay:.36s;background:#f472b6}.x100-gravity-loader i:nth-child(5){left:110px;animation-delay:.48s;background:#fbbf24}@keyframes x100-gravity{0%{transform:translateY(0) scaleY(1)}65%{transform:translateY(78px) scaleY(1)}75%{transform:translateY(82px) scaleY(.55)}88%{transform:translateY(56px) scaleY(1.12)}100%{transform:translateY(0)}}`,
    `.x100-orbit-loader{position:relative;width:120px;height:120px;transform-style:preserve-3d}.x100-orbit-loader b{position:absolute;left:43px;top:43px;width:34px;height:34px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff,#8b5cf6 20%,#312e81 65%);box-shadow:0 0 24px #756cff77}.x100-orbit-loader i{position:absolute;inset:12px;border:1px solid #22d3ee55;border-radius:50%;transform:rotateX(68deg);animation:x100-orbit-l 2.6s linear infinite}.x100-orbit-loader i:after{content:"";position:absolute;top:-4px;left:50%;width:8px;height:8px;border-radius:50%;background:#22d3ee;box-shadow:0 0 12px #22d3ee}.x100-orbit-loader i:nth-of-type(2){inset:22px;transform:rotateY(68deg);animation-direction:reverse;animation-duration:2s}.x100-orbit-loader i:nth-of-type(3){inset:2px;transform:rotateX(75deg) rotateZ(35deg);animation-duration:3.8s}@keyframes x100-orbit-l{to{rotate:360deg}}`,
    `.x100-vortex-loader{position:relative;width:120px;height:120px;border-radius:50%;filter:drop-shadow(0 0 15px #756cff55)}.x100-vortex-loader b{position:absolute;left:42px;top:42px;width:36px;height:36px;border-radius:50%;background:#020207;box-shadow:inset 0 0 12px #756cff99,0 0 18px #756cff55}.x100-vortex-loader i{position:absolute;left:56px;top:56px;width:8px;height:8px;border-radius:50%;background:#fff;box-shadow:0 0 8px #22d3ee;transform-origin:4px 4px;animation:x100-vortex 2.2s ease-in infinite}.x100-vortex-loader i:nth-child(1){--a:0deg}.x100-vortex-loader i:nth-child(2){--a:45deg;animation-delay:-.25s}.x100-vortex-loader i:nth-child(3){--a:90deg;animation-delay:-.5s}.x100-vortex-loader i:nth-child(4){--a:135deg;animation-delay:-.75s}.x100-vortex-loader i:nth-child(5){--a:180deg;animation-delay:-1s}.x100-vortex-loader i:nth-child(6){--a:225deg;animation-delay:-1.25s}.x100-vortex-loader i:nth-child(7){--a:270deg;animation-delay:-1.5s}.x100-vortex-loader i:nth-child(8){--a:315deg;animation-delay:-1.75s}@keyframes x100-vortex{0%{transform:rotate(var(--a)) translateX(54px) scale(1)}100%{transform:rotate(calc(var(--a) + 720deg)) translateX(4px) scale(.05);opacity:.1}}`,
    `.x100-skeleton{width:210px;padding:15px;border:1px solid #ffffff10;border-radius:16px;background:#11141a;display:grid;grid-template-columns:44px 1fr;gap:9px;animation:x100-skeleton-blur 2.2s ease-in-out infinite}.x100-skeleton i{grid-row:1/4;width:44px;height:44px;border-radius:12px;background:#ffffff12}.x100-skeleton b,.x100-skeleton span{display:block;height:10px;border-radius:5px;background:linear-gradient(90deg,#ffffff0c,#ffffff20,#ffffff0c);background-size:200% 100%;animation:x100-shimmer 1.4s linear infinite}.x100-skeleton span:nth-of-type(1){width:90%}.x100-skeleton span:nth-of-type(2){width:65%}.x100-skeleton span:nth-of-type(3){width:45%}@keyframes x100-shimmer{to{background-position:200% 0}}@keyframes x100-skeleton-blur{0%,100%{filter:blur(6px);opacity:.45}50%{filter:blur(0);opacity:1}}`,
    `.x100-pixel-loader{display:grid;grid-template-columns:repeat(4,14px);gap:4px;transform:rotate(45deg)}.x100-pixel-loader i{width:14px;height:14px;background:#756cff;border-radius:3px;animation:x100-pixel 1.8s ease-in-out infinite;animation-delay:calc(var(--i,0)*.06s)}.x100-pixel-loader i:nth-child(2n){background:#22d3ee;animation-delay:.2s}.x100-pixel-loader i:nth-child(3n){background:#f472b6;animation-delay:.4s}.x100-pixel-loader i:nth-child(5n){animation-delay:.6s}@keyframes x100-pixel{0%,100%{transform:scale(.25);opacity:.15}45%,60%{transform:scale(1);opacity:1;box-shadow:0 0 12px currentColor}}`,
    `.x100-morph-loader{width:74px;height:74px;background:linear-gradient(135deg,#22d3ee,#756cff,#f472b6);box-shadow:0 0 30px #756cff55;animation:x100-morph-shape 2.8s ease-in-out infinite}@keyframes x100-morph-shape{0%,100%{border-radius:50%;transform:rotate(0) scale(.75)}25%{border-radius:12%;transform:rotate(45deg) scale(1)}50%{border-radius:45% 55% 30% 70%/60% 35% 65% 40%;transform:rotate(160deg) scale(.85)}75%{clip-path:polygon(50% 0,100% 100%,0 100%);border-radius:0;transform:rotate(300deg) scale(1.05)}}`,
    `.x100-dna{position:relative;width:120px;height:110px;perspective:600px}.x100-dna span{position:absolute;left:50%;top:calc(var(--i)*11px);width:80px;height:8px;transform:translateX(-50%) rotateY(calc(var(--i)*38deg));transform-style:preserve-3d;animation:x100-dna-spin 2.6s linear infinite}.x100-dna i,.x100-dna b{position:absolute;width:9px;height:9px;border-radius:50%;top:0}.x100-dna i{left:0;background:#22d3ee;box-shadow:0 0 10px #22d3ee}.x100-dna b{right:0;background:#f472b6;box-shadow:0 0 10px #f472b6}.x100-dna span:after{content:"";position:absolute;left:8px;right:8px;top:4px;height:1px;background:#ffffff25}@keyframes x100-dna-spin{to{rotate:0 1 0 360deg}}`,
    `.x100-black-hole{position:relative;width:130px;height:130px;border-radius:50%;background:radial-gradient(circle,#000 0 16%,#756cff55 17% 21%,#f472b633 27%,transparent 54%);filter:drop-shadow(0 0 18px #756cff44)}.x100-black-hole:before{content:"";position:absolute;inset:21px;border-radius:50%;border:7px solid transparent;border-top-color:#22d3ee88;border-bottom-color:#f472b688;filter:blur(5px);animation:x100-hole-ring 1.3s linear infinite}.x100-black-hole i{position:absolute;left:61px;top:61px;width:7px;height:7px;border-radius:50%;background:#fff;transform-origin:4px 4px;animation:x100-hole-dot 2s ease-in infinite}.x100-black-hole i:nth-child(2){animation-delay:-.3s}.x100-black-hole i:nth-child(3){animation-delay:-.6s}.x100-black-hole i:nth-child(4){animation-delay:-.9s}.x100-black-hole i:nth-child(5){animation-delay:-1.2s}.x100-black-hole i:nth-child(6){animation-delay:-1.5s}@keyframes x100-hole-ring{to{rotate:360deg}}@keyframes x100-hole-dot{0%{transform:rotate(0) translateX(58px) scale(1)}100%{transform:rotate(720deg) translateX(2px) scale(.05);opacity:0}}`,
  ]
  return { html: htmlVariants[index], css: cssVariants[index] }
}

const feedbackIdeas: Idea[] = [
  ['Gravity Confetti Success', 'Success launches colorful confetti that falls under simple gravity.', ['feedback', 'success', 'confetti']],
  ['Success Shockwave', 'A bright green spatial ring expands outward from a success badge.', ['feedback', 'success', 'shockwave']],
  ['Physics Error Shake', 'The error panel shakes with decaying motion instead of a flat vibration.', ['feedback', 'error', 'shake']],
  ['RGB Error Glitch', 'An error state briefly splits into red/cyan channels and scanline fragments.', ['feedback', 'error', 'glitch']],
  ['Warning Surface Pulse', 'The entire warning card subtly breathes with warm light.', ['feedback', 'warning', 'pulse']],
  ['Achievement Explosion', 'An achievement badge springs forward while stars burst behind it.', ['feedback', 'achievement', 'burst']],
  ['Delete Dissolve', 'A deleted tile breaks into shrinking pixel dust before returning.', ['feedback', 'delete', 'dissolve']],
  ['Archive Vacuum', 'The card visually compresses and gets sucked toward a tiny archive slot.', ['feedback', 'archive', 'vacuum']],
  ['Reverse Undo State', 'The removal animation can visibly reverse itself with the Undo action.', ['feedback', 'undo', 'reverse']],
  ['Save Light Sweep', 'Saving sends a fast light flash across the entire surface.', ['feedback', 'save', 'flash']],
]

function buildFeedback(index: number, idea: Idea): Built {
  const labels = ['SUCCESS','SAVED','ERROR','FAILED','WARNING','ACHIEVED','DELETE','ARCHIVE','UNDO','SAVE']
  const html = `<div class="x100-feedback"><div class="x100-feedback-icon">${['✓','✓','!','!','⚠','★','×','↓','↶','✓'][index]}</div><strong>${labels[index]}</strong><span>${esc(idea[0])}</span><button type="button">Trigger</button><i class="x100-fx"></i></div>`
  const base = `.x100-feedback{position:relative;width:235px;padding:20px;border:1px solid #ffffff14;border-radius:18px;background:#11141b;color:#fff;text-align:center;overflow:hidden;box-shadow:0 20px 38px #0006}.x100-feedback-icon{width:46px;height:46px;margin:0 auto 10px;border-radius:50%;display:grid;place-items:center;background:#756cff22;border:1px solid #756cff55;color:#a9a4ff;font:900 21px Inter,sans-serif}.x100-feedback strong{display:block;font:900 14px Inter,sans-serif;letter-spacing:.08em}.x100-feedback>span{display:block;margin:5px 0 14px;color:#747d8d;font:500 9px Inter,sans-serif}.x100-feedback button{border:1px solid #ffffff12;border-radius:10px;background:#ffffff07;color:#aab1bd;padding:8px 12px;font:700 9px Inter,sans-serif;cursor:pointer}.x100-fx{position:absolute;pointer-events:none}`
  const variants = [
    `.x100-feedback.play .x100-confetti{position:absolute;left:50%;top:40%;width:7px;height:10px;background:hsl(var(--h) 90% 65%);animation:x100-confetti-fall 1.2s cubic-bezier(.2,.7,.4,1) forwards}@keyframes x100-confetti-fall{0%{transform:translate(0,0) rotate(0)}40%{transform:translate(var(--x),-55px) rotate(180deg)}100%{transform:translate(calc(var(--x)*1.2),95px) rotate(520deg);opacity:0}}`,
    `.x100-feedback-icon{background:#2dd4bf22;border-color:#2dd4bf66;color:#5eead4}.x100-feedback.play .x100-feedback-icon:after{content:"";position:absolute;width:46px;height:46px;border:2px solid #2dd4bf;border-radius:50%;animation:x100-shock .85s ease-out forwards}@keyframes x100-shock{to{transform:scale(4.5);opacity:0}}`,
    `.x100-feedback-icon{background:#fb718522;border-color:#fb718566;color:#fb7185}.x100-feedback.play{animation:x100-error-physics .75s cubic-bezier(.3,.9,.4,1)}@keyframes x100-error-physics{0%,100%{transform:translateX(0) rotate(0)}15%{transform:translateX(-16px) rotate(-3deg)}30%{transform:translateX(13px) rotate(2.5deg)}48%{transform:translateX(-9px) rotate(-1.7deg)}64%{transform:translateX(6px) rotate(1deg)}80%{transform:translateX(-3px) rotate(-.5deg)}}`,
    `.x100-feedback-icon{background:#fb718522;border-color:#fb718566;color:#fb7185}.x100-feedback.play{animation:x100-rgb-error .48s steps(2)}.x100-feedback.play:before,.x100-feedback.play:after{content:"ERROR";position:absolute;left:0;right:0;top:45%;font:900 34px monospace;opacity:.22;pointer-events:none}.x100-feedback.play:before{color:#22d3ee;transform:translateX(-5px)}.x100-feedback.play:after{color:#f43f5e;transform:translateX(5px)}@keyframes x100-rgb-error{20%{transform:translateX(4px) skewX(3deg)}40%{transform:translateX(-6px)}60%{filter:hue-rotate(90deg)}80%{transform:translateX(2px)}}`,
    `.x100-feedback-icon{background:#fbbf2422;border-color:#fbbf2466;color:#fbbf24}.x100-feedback.play{animation:x100-warning-pulse 1.2s ease-in-out 2}@keyframes x100-warning-pulse{50%{box-shadow:0 0 0 1px #fbbf2444,0 0 42px #fbbf2433,inset 0 0 25px #fbbf2410;transform:scale(1.02)}}`,
    `.x100-feedback-icon{color:#fbbf24;border-color:#fbbf2466;background:#fbbf2415}.x100-feedback.play .x100-feedback-icon{animation:x100-achieve .75s cubic-bezier(.2,1.6,.3,1)}.x100-feedback.play:before{content:"✦  ★  ✧  ✦  ★";position:absolute;left:10px;right:10px;top:38px;color:#fbbf24;letter-spacing:12px;animation:x100-stars-explode .9s ease-out forwards}@keyframes x100-achieve{50%{transform:translateY(-18px) scale(1.7) rotate(12deg)}}@keyframes x100-stars-explode{to{transform:translateY(-45px) scale(1.8);opacity:0}}`,
    `.x100-feedback.play{animation:x100-dissolve-card .9s ease-in forwards}.x100-feedback.play:after{content:"";position:absolute;inset:0;background:repeating-radial-gradient(circle,#11141b 0 2px,transparent 3px 7px);animation:x100-dust .9s ease-out forwards}@keyframes x100-dissolve-card{70%{filter:blur(3px);transform:scale(.96)}100%{opacity:.08;transform:scale(.82)}}@keyframes x100-dust{to{transform:translateY(-35px) scale(1.4);opacity:0}}`,
    `.x100-feedback:after{content:"▰";position:absolute;right:15px;bottom:12px;color:#756cff;font-size:26px}.x100-feedback.play{animation:x100-vacuum .9s cubic-bezier(.55,.05,.75,.2) forwards;transform-origin:90% 88%}@keyframes x100-vacuum{55%{transform:translate(55px,28px) scale(.5) rotate(18deg);filter:blur(1px)}100%{transform:translate(100px,45px) scale(.03) rotate(80deg);opacity:0}}`,
    `.x100-feedback.removed{transform:translateX(80px) scale(.35) rotate(12deg);opacity:0;transition:.55s}.x100-feedback.restoring{animation:x100-undo-reverse .7s cubic-bezier(.2,1.2,.2,1)}@keyframes x100-undo-reverse{0%{transform:translateX(80px) scale(.35) rotate(12deg);opacity:0}100%{transform:none;opacity:1}}`,
    `.x100-feedback.play:after{content:"";position:absolute;top:-30%;left:-40%;width:28%;height:160%;background:linear-gradient(90deg,transparent,#fff,transparent);transform:rotate(18deg);filter:blur(1px);animation:x100-save-flash .75s ease-out forwards}.x100-feedback.play .x100-feedback-icon{box-shadow:0 0 28px #2dd4bf66;color:#2dd4bf}@keyframes x100-save-flash{to{left:130%}}`,
  ]
  let js = `const c=document.querySelector('.x100-feedback'),b=c.querySelector('button');const play=()=>{c.classList.remove('play');void c.offsetWidth;c.classList.add('play');setTimeout(()=>c.classList.remove('play'),1600)};b.addEventListener('click',play);`
  if (index === 0) js = `const c=document.querySelector('.x100-feedback'),b=c.querySelector('button');b.addEventListener('click',()=>{c.classList.add('play');for(let i=0;i<22;i++){const p=document.createElement('i');p.className='x100-confetti';p.style.setProperty('--x',(Math.random()*150-75)+'px');p.style.setProperty('--h',String(Math.random()*360));c.appendChild(p);setTimeout(()=>p.remove(),1300)}setTimeout(()=>c.classList.remove('play'),1400)})`
  if (index === 8) js = `const c=document.querySelector('.x100-feedback'),b=c.querySelector('button');let removed=false;b.addEventListener('click',()=>{if(!removed){c.classList.add('removed');b.textContent='Undo';removed=true;setTimeout(()=>{c.style.opacity='';},100)}else{c.classList.remove('removed');c.classList.add('restoring');b.textContent='Trigger';removed=false;setTimeout(()=>c.classList.remove('restoring'),750)}})`
  return { html, css: base + variants[index], js }
}

const cursorIdeas: Idea[] = [
  ['3D Light Cursor', 'A small lit sphere follows the pointer with a depth shadow.', ['cursor', '3d', 'light']],
  ['Liquid Cursor', 'A soft blob cursor stretches based on pointer velocity.', ['cursor', 'liquid', 'morph']],
  ['Particle Trail Cursor', 'Pointer movement emits a short-lived trail of colored particles.', ['cursor', 'particles', 'trail']],
  ['Glow Trail Cursor', 'A sequence of soft luminous dots creates a fading light tail.', ['cursor', 'glow', 'trail']],
  ['Gravity Cursor Field', 'Nearby floating nodes move slightly toward the pointer.', ['cursor', 'gravity', 'physics']],
  ['Lens Cursor', 'The pointer becomes a magnifying lens over a patterned surface.', ['cursor', 'lens', 'magnify']],
  ['Focus Blur Lens', 'Only the circular region under the pointer appears sharp.', ['cursor', 'blur', 'lens']],
  ['Heat Distortion Cursor', 'A warm local lens produces hue and blur distortion around the pointer.', ['cursor', 'heat', 'distortion']],
  ['Chromatic Cursor', 'RGB rings separate around the pointer with velocity-like lag.', ['cursor', 'chromatic', 'rgb']],
  ['Chaos Mode Playground', 'Tilt, particles, glow, floating icons, glitch and cursor light all combine.', ['cursor', 'chaos', 'particles', '3d']],
]

function buildCursor(index: number, idea: Idea): Built {
  const html = `<div class="x100-play"><div class="x100-play-grid"></div><span class="x100-follower"></span><strong>${esc(idea[0])}</strong><small>move your cursor here</small><i class="x100-node n1">✦</i><i class="x100-node n2">●</i><i class="x100-node n3">◆</i><div class="x100-lens-content">RED<br>UI<br>LAB</div></div>`
  const base = `.x100-play{--x:50%;--y:50%;position:relative;width:310px;height:190px;border:1px solid #ffffff14;border-radius:20px;background:#0c0f15;color:#fff;overflow:hidden;cursor:none;box-shadow:0 22px 45px #0007}.x100-play-grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:24px 24px}.x100-play>strong{position:absolute;left:18px;top:18px;font:900 14px Inter,sans-serif;z-index:2}.x100-play>small{position:absolute;left:18px;top:39px;color:#667080;font:600 8px Inter,sans-serif;z-index:2}.x100-follower{position:absolute;left:0;top:0;width:24px;height:24px;border-radius:50%;pointer-events:none;transform:translate(-50%,-50%);z-index:9}.x100-node{position:absolute;font-style:normal;transition:transform .08s;color:#8b86ff}.x100-node.n1{left:55px;bottom:32px}.x100-node.n2{right:55px;top:68px}.x100-node.n3{right:95px;bottom:33px}.x100-lens-content{position:absolute;right:18px;bottom:13px;color:#303746;font:900 26px/0.8 Inter,sans-serif;text-align:right}`
  const variants = [
    `.x100-follower{background:radial-gradient(circle at 35% 30%,#fff,#a78bfa 22%,#4338ca 64%);box-shadow:7px 10px 15px #0009,0 0 18px #756cff77}.x100-follower:after{content:"";position:absolute;inset:4px;border-radius:50%;border-top:1px solid #fff8}`,
    `.x100-follower{width:34px;height:34px;background:linear-gradient(135deg,#22d3eeaa,#756cffbb,#f472b6aa);filter:blur(.4px);box-shadow:0 0 22px #756cff55;transform:translate(-50%,-50%) scaleX(var(--stretch,1)) rotate(var(--angle,0deg));transition:width .1s,height .1s;border-radius:55% 45% 60% 40%}`,
    `.x100-follower{width:10px;height:10px;background:#fff;box-shadow:0 0 12px #fff}.x100-trail-particle{position:absolute;width:7px;height:7px;border-radius:50%;background:hsl(var(--h) 90% 67%);pointer-events:none;animation:x100-trail-p .7s ease-out forwards}@keyframes x100-trail-p{to{transform:translate(var(--dx),var(--dy)) scale(.05);opacity:0}}`,
    `.x100-follower{width:13px;height:13px;background:#fff;border-radius:50%;box-shadow:0 0 18px #22d3ee}.x100-glow-dot{position:absolute;width:15px;height:15px;border-radius:50%;background:#22d3ee55;filter:blur(5px);pointer-events:none;animation:x100-glowfade .65s linear forwards}@keyframes x100-glowfade{to{transform:scale(2.3);opacity:0}}`,
    `.x100-follower{width:18px;height:18px;background:#756cff;border:3px solid #d8d5ff;box-shadow:0 0 22px #756cff88}.x100-node{font-size:22px;filter:drop-shadow(0 0 7px #756cff)}`,
    `.x100-follower{width:68px;height:68px;border:2px solid #ffffff99;background:#ffffff0c;backdrop-filter:brightness(1.65) saturate(1.4);box-shadow:0 12px 25px #0007,inset 0 0 0 4px #ffffff12}.x100-follower:after{content:"";position:absolute;width:28px;height:3px;background:#fff8;right:-20px;bottom:0;rotate:45deg;border-radius:2px}.x100-play-grid{background-size:16px 16px}.x100-lens-content{font-size:34px;color:#4d5566}`,
    `.x100-play{filter:blur(4px)}.x100-follower{width:86px;height:86px;border:1px solid #fff5;background:#0000;backdrop-filter:blur(0);box-shadow:0 0 30px #756cff22}.x100-follower:before{content:"";position:absolute;inset:-7px;border-radius:50%;backdrop-filter:blur(0);filter:none}.x100-play>strong,.x100-play>small,.x100-lens-content{filter:blur(0)}`,
    `.x100-follower{width:78px;height:78px;background:radial-gradient(circle,#ffb45c18 0 35%,#ff6b3522 55%,transparent 70%);backdrop-filter:blur(2px) hue-rotate(18deg) saturate(1.8);box-shadow:0 0 32px #ff7a3344}.x100-follower:after{content:"";position:absolute;inset:13px;border-radius:50%;border:1px dashed #ffbd7a88;animation:x100-heat 2s linear infinite}@keyframes x100-heat{to{rotate:360deg}}`,
    `.x100-follower{width:28px;height:28px;border:2px solid #fff;background:#ffffff08}.x100-follower:before,.x100-follower:after{content:"";position:absolute;inset:-2px;border-radius:50%;border:2px solid}.x100-follower:before{border-color:#22d3ee;transform:translate(-6px,2px)}.x100-follower:after{border-color:#f43f5e;transform:translate(6px,-2px)}.x100-play{background:radial-gradient(circle at var(--x) var(--y),#756cff24,transparent 25%),#0c0f15}`,
    `.x100-play{background:radial-gradient(circle at var(--x) var(--y),#ffffff18,transparent 22%),linear-gradient(135deg,#120d25,#071820);transform:perspective(700px) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg));transition:transform .08s}.x100-follower{width:30px;height:30px;background:conic-gradient(#22d3ee,#756cff,#f472b6,#22d3ee);box-shadow:0 0 25px #756cff66;animation:x100-chaos-spin 1.5s linear infinite}.x100-node{font-size:24px;animation:x100-chaos-float 2s ease-in-out infinite}.x100-node.n2{animation-delay:.4s}.x100-node.n3{animation-delay:.8s}.x100-chaos-p{position:absolute;width:5px;height:5px;border-radius:50%;background:#fff;pointer-events:none;animation:x100-chaos-p .75s ease-out forwards}@keyframes x100-chaos-spin{to{rotate:360deg}}@keyframes x100-chaos-float{50%{transform:translateY(-13px) rotate(25deg);filter:drop-shadow(0 0 10px #22d3ee)}}@keyframes x100-chaos-p{to{transform:translate(var(--dx),var(--dy));opacity:0}}`,
  ]
  let js = `const p=document.querySelector('.x100-play'),f=p.querySelector('.x100-follower'),nodes=[...p.querySelectorAll('.x100-node')];let lastX=0,lastY=0;p.addEventListener('pointermove',e=>{const r=p.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,dx=x-lastX,dy=y-lastY;lastX=x;lastY=y;f.style.left=x+'px';f.style.top=y+'px';p.style.setProperty('--x',(x/r.width*100)+'%');p.style.setProperty('--y',(y/r.height*100)+'%');`
  if (index === 1) js += `const speed=Math.min(2.2,1+Math.hypot(dx,dy)/14);f.style.setProperty('--stretch',String(speed));f.style.setProperty('--angle',(Math.atan2(dy,dx)*57.2958)+'deg');`
  if (index === 2) js += `if(Math.random()>.45){const q=document.createElement('i');q.className='x100-trail-particle';q.style.left=x+'px';q.style.top=y+'px';q.style.setProperty('--dx',(Math.random()*40-20)+'px');q.style.setProperty('--dy',(Math.random()*40-20)+'px');q.style.setProperty('--h',String(Math.random()*360));p.appendChild(q);setTimeout(()=>q.remove(),720)}`
  if (index === 3) js += `const q=document.createElement('i');q.className='x100-glow-dot';q.style.left=(x-7)+'px';q.style.top=(y-7)+'px';p.appendChild(q);setTimeout(()=>q.remove(),680);`
  if (index === 4) js += `nodes.forEach((n,i)=>{const nr=n.getBoundingClientRect(),cx=nr.left-r.left+nr.width/2,cy=nr.top-r.top+nr.height/2,dd=Math.max(45,Math.hypot(x-cx,y-cy)),force=Math.min(16,520/dd);n.style.transform='translate('+((x-cx)/dd*force)+'px,'+((y-cy)/dd*force)+'px)'})`
  if (index === 9) js += `p.style.setProperty('--ry',((x/r.width-.5)*9)+'deg');p.style.setProperty('--rx',(-(y/r.height-.5)*8)+'deg');if(Math.random()>.55){const q=document.createElement('i');q.className='x100-chaos-p';q.style.left=x+'px';q.style.top=y+'px';q.style.setProperty('--dx',(Math.random()*60-30)+'px');q.style.setProperty('--dy',(Math.random()*60-30)+'px');p.appendChild(q);setTimeout(()=>q.remove(),760)}`
  js += `});p.addEventListener('pointerleave',()=>{f.style.left='-50px';f.style.top='-50px';nodes.forEach(n=>n.style.transform='');p.style.setProperty('--rx','0deg');p.style.setProperty('--ry','0deg')});`
  return { html, css: base + variants[index], js }
}

const all: CustomDesign[] = []
buttonIdeas.forEach((idea, index) => all.push(seed(index + 1, 'Extreme Buttons', idea, buildButton(index, idea))))
loginIdeas.forEach((idea, index) => all.push(seed(index + 11, 'Extreme Login', idea, buildLogin(index, idea))))
dashboardIdeas.forEach((idea, index) => all.push(seed(index + 21, 'Extreme Dashboards', idea, buildDashboard(index, idea))))
cardIdeas.forEach((idea, index) => all.push(seed(index + 31, 'Extreme Cards', idea, buildCard(index, idea))))
navIdeas.forEach((idea, index) => all.push(seed(index + 41, 'Extreme Navigation', idea, buildNav(index, idea))))
toggleIdeas.forEach((idea, index) => all.push(seed(index + 51, 'Extreme Toggles', idea, buildToggle(index, idea))))
searchIdeas.forEach((idea, index) => all.push(seed(index + 61, 'Extreme Search', idea, buildSearch(index, idea))))
loaderIdeas.forEach((idea, index) => all.push(seed(index + 71, 'Extreme Loaders', idea, buildLoader(index, idea))))
feedbackIdeas.forEach((idea, index) => all.push(seed(index + 81, 'Extreme Feedback', idea, buildFeedback(index, idea))))
cursorIdeas.forEach((idea, index) => all.push(seed(index + 91, 'Extreme Cursor & Physics', idea, buildCursor(index, idea))))

export const extremeSeedDesigns = all
export const extremeCategories = [...new Set(all.map((design) => design.category))]
