import type { CustomDesign } from './types'

const make = (
  index: number,
  category: string,
  name: string,
  description: string,
  html: string,
  css: string,
  tags: string[],
  js?: string,
): CustomDesign => ({
  id: `final-${String(index).padStart(3, '0')}-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
  name,
  category,
  description,
  html,
  css,
  js,
  tags,
  source: 'seed',
})

const out: CustomDesign[] = []
let n = 1
const add = (category: string, name: string, description: string, html: string, css: string, tags: string[], js?: string) => {
  out.push(make(n++, category, name, description, html, css, tags, js))
}

// Ambient Scenes
add('Ambient Scenes','Aurora Room','Soft aurora light drifts behind a frosted glass room.',`<div class="f-aurora"><i></i><i></i><span>AMBIENT</span></div>`,`.f-aurora{position:relative;width:230px;height:145px;border-radius:24px;overflow:hidden;background:#080b13;border:1px solid #ffffff15;box-shadow:0 22px 40px #0008}.f-aurora i{position:absolute;width:150px;height:120px;border-radius:50%;filter:blur(28px);opacity:.6;animation:f-aurora 6s ease-in-out infinite}.f-aurora i:first-child{background:#22d3ee;left:-30px;top:10px}.f-aurora i:nth-child(2){background:#8b5cf6;right:-35px;bottom:-15px;animation-delay:-3s}.f-aurora:after{content:"";position:absolute;inset:14px;border:1px solid #ffffff18;border-radius:18px;background:#ffffff08;backdrop-filter:blur(16px)}.f-aurora span{position:absolute;z-index:2;inset:0;display:grid;place-items:center;color:#fff;font:900 11px Inter;letter-spacing:.18em}@keyframes f-aurora{50%{transform:translate(35px,-18px) scale(1.2);filter:blur(36px) hue-rotate(35deg)}}`,['ambient','aurora','glass','blur'])
add('Ambient Scenes','Night City','A tiny neon city flickers beneath a dark skyline.',`<div class="f-city"><span></span><i></i><b></b></div>`,`.f-city{position:relative;width:230px;height:145px;border-radius:22px;overflow:hidden;background:linear-gradient(#070916,#111833);border:1px solid #ffffff12}.f-city:before{content:"";position:absolute;inset:0;background:radial-gradient(circle,#fff 0 1px,transparent 1.5px) 0 0/26px 26px;opacity:.35}.f-city span,.f-city i,.f-city b{position:absolute;bottom:0;background:#0a0c12;border-top:1px solid #ffffff10}.f-city span{left:15px;width:58px;height:78px;box-shadow:inset 10px 0 #22d3ee0d}.f-city i{left:80px;width:72px;height:105px;box-shadow:inset -10px 0 #f472b60c}.f-city b{right:16px;width:54px;height:65px}.f-city span:after,.f-city i:after,.f-city b:after{content:"";position:absolute;inset:10px;background:repeating-linear-gradient(0deg,#facc1544 0 5px,transparent 5px 13px);animation:f-city 2.5s steps(1) infinite}@keyframes f-city{50%{opacity:.35}}`,['ambient','city','neon','scene'])
add('Ambient Scenes','Ocean Glass','Moving caustic light crosses a deep glass ocean panel.',`<div class="f-ocean"><span>DEEP</span></div>`,`.f-ocean{position:relative;width:230px;height:145px;border-radius:24px;background:linear-gradient(#0e7490,#082f49 55%,#020617);overflow:hidden;border:1px solid #67e8f944;box-shadow:inset 0 0 35px #0007}.f-ocean:before{content:"";position:absolute;inset:-60%;background:repeating-radial-gradient(ellipse at center,#ffffff18 0 3px,transparent 4px 18px);transform:rotate(16deg);animation:f-ocean 9s linear infinite;filter:blur(1px)}.f-ocean:after{content:"";position:absolute;inset:0;background:linear-gradient(120deg,#ffffff18,transparent 35%,#ffffff0d 60%,transparent);animation:f-shimmer 4s ease-in-out infinite}.f-ocean span{position:absolute;z-index:2;bottom:13px;right:15px;color:#a5f3fc;font:900 9px Inter;letter-spacing:.2em}@keyframes f-ocean{to{transform:translate(80px,35px) rotate(16deg)}}@keyframes f-shimmer{50%{transform:translateX(40px)}}`,['ambient','ocean','caustic','glass'])
add('Ambient Scenes','Sunset Horizon','A warm sun slowly sinks into a gradient horizon.',`<div class="f-sunset"><i></i><span></span></div>`,`.f-sunset{position:relative;width:230px;height:145px;border-radius:22px;overflow:hidden;background:linear-gradient(#4c1d95,#be185d 48%,#fb923c 78%,#111827 79%);border:1px solid #ffffff18}.f-sunset i{position:absolute;width:62px;height:62px;border-radius:50%;left:84px;top:34px;background:#fde68a;box-shadow:0 0 35px #fbbf24aa;animation:f-sun 8s ease-in-out infinite}.f-sunset span{position:absolute;left:-10%;right:-10%;bottom:-25px;height:70px;border-radius:50%;background:#101827;box-shadow:0 -4px #fdba7444}@keyframes f-sun{50%{transform:translateY(58px);filter:saturate(.7);opacity:.55}}`,['ambient','sunset','horizon','warm'])
add('Ambient Scenes','Snow Globe','Snow particles drift inside a miniature glass globe.',`<div class="f-globe"><span>⌂</span>${Array.from({length:14},(_,i)=>`<i style="--x:${8+(i*6)%86}%;--d:${(i%7)*.23}s"></i>`).join('')}</div>`,`.f-globe{position:relative;width:145px;height:145px;border-radius:50%;background:radial-gradient(circle at 35% 25%,#ffffff33,#bfdbfe22 35%,#0f172a 78%);border:1px solid #ffffff55;box-shadow:inset 0 0 28px #fff2,0 20px 35px #0007;overflow:hidden}.f-globe span{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);font-size:42px;color:#dbeafe}.f-globe i{position:absolute;left:var(--x);top:-8px;width:5px;height:5px;border-radius:50%;background:#fff;box-shadow:0 0 5px #fff;animation:f-snow 3s linear infinite;animation-delay:var(--d)}@keyframes f-snow{to{transform:translate(-18px,165px) rotate(180deg)}}`,['ambient','snow','globe','particles'])
add('Ambient Scenes','Thunder Glass','Lightning briefly illuminates a dark frosted panel.',`<div class="f-thunder"><i></i><span>STORM</span></div>`,`.f-thunder{position:relative;width:230px;height:145px;border-radius:22px;background:linear-gradient(#111827,#030712);border:1px solid #ffffff15;overflow:hidden;box-shadow:inset 0 0 30px #000}.f-thunder:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 60% 20%,#ffffff33,transparent 40%);opacity:0;animation:f-flash 5s infinite}.f-thunder i{position:absolute;left:112px;top:18px;width:6px;height:100px;background:#e0f2fe;clip-path:polygon(55% 0,100% 0,65% 38%,100% 38%,0 100%,28% 55%,0 55%);filter:drop-shadow(0 0 12px #67e8f9);opacity:0;animation:f-lightning 5s infinite}.f-thunder span{position:absolute;left:14px;bottom:11px;color:#64748b;font:900 8px Inter;letter-spacing:.2em}@keyframes f-flash{0%,70%,74%,78%,100%{opacity:0}71%,73%,76%{opacity:1}}@keyframes f-lightning{0%,70%,78%,100%{opacity:0}71%,77%{opacity:1}}`,['ambient','storm','lightning','glass'])
add('Ambient Scenes','Desert Heat','Heat haze ripples above a warm desert landscape.',`<div class="f-desert"><i></i><span></span></div>`,`.f-desert{position:relative;width:230px;height:145px;border-radius:22px;overflow:hidden;background:linear-gradient(#fb923c,#fde68a 62%,#c2410c 63%);border:1px solid #ffffff20}.f-desert:before{content:"";position:absolute;width:55px;height:55px;border-radius:50%;right:32px;top:22px;background:#fff7c2;box-shadow:0 0 32px #fff2a8}.f-desert i,.f-desert span{position:absolute;left:-20px;right:-20px;height:75px;border-radius:50%;bottom:-38px;background:#b45309}.f-desert span{bottom:-55px;background:#7c2d12}.f-desert:after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 12px,#fff1 13px 15px);filter:blur(5px);animation:f-heat 2s ease-in-out infinite}@keyframes f-heat{50%{transform:translateX(8px) skewX(3deg)}}`,['ambient','desert','heat','distortion'])
add('Ambient Scenes','Forest Mist','Layered tree silhouettes fade through moving mist.',`<div class="f-forest"><i></i><b></b><span></span></div>`,`.f-forest{position:relative;width:230px;height:145px;border-radius:22px;overflow:hidden;background:linear-gradient(#0f3d37,#071b18);border:1px solid #ffffff12}.f-forest i,.f-forest b,.f-forest span{position:absolute;bottom:0;width:0;height:0;border-left:34px solid transparent;border-right:34px solid transparent;border-bottom:110px solid #163b34}.f-forest i{left:8px}.f-forest b{left:83px;border-bottom-color:#0d2b27}.f-forest span{right:5px;border-bottom-color:#143630}.f-forest:after{content:"";position:absolute;left:-40%;right:-40%;bottom:18px;height:50px;background:#d1fae533;filter:blur(16px);animation:f-mist 7s linear infinite}@keyframes f-mist{to{transform:translateX(110px)}}`,['ambient','forest','mist','layers'])
add('Ambient Scenes','Space Dust','Colored dust clouds and stars drift through a tiny nebula.',`<div class="f-nebula"><i></i><b></b></div>`,`.f-nebula{position:relative;width:230px;height:145px;border-radius:22px;background:#020617;overflow:hidden;border:1px solid #ffffff12}.f-nebula:before{content:"";position:absolute;inset:0;background:radial-gradient(circle,#fff 0 1px,transparent 1.5px) 0 0/23px 23px;opacity:.55}.f-nebula i,.f-nebula b{position:absolute;width:150px;height:95px;border-radius:50%;filter:blur(28px);opacity:.5;animation:f-neb 8s ease-in-out infinite}.f-nebula i{background:#7c3aed;left:-30px;top:10px}.f-nebula b{background:#06b6d4;right:-35px;bottom:-10px;animation-delay:-4s}@keyframes f-neb{50%{transform:translate(45px,12px) scale(1.3);filter:blur(36px) hue-rotate(55deg)}}`,['ambient','space','nebula','dust'])
add('Ambient Scenes','Lava Lamp','Large colorful blobs float and merge behind glass.',`<div class="f-lava"><i></i><i></i><i></i></div>`,`.f-lava{position:relative;width:115px;height:170px;border-radius:48px 48px 28px 28px;background:#17111f;border:3px solid #45404d;overflow:hidden;box-shadow:inset 0 0 25px #000,0 20px 35px #0008}.f-lava i{position:absolute;width:55px;height:55px;border-radius:45% 55% 60% 40%;background:#f472b6;filter:blur(2px);animation:f-lava 5s ease-in-out infinite;left:27px;bottom:18px}.f-lava i:nth-child(2){width:40px;height:40px;background:#8b5cf6;left:12px;animation-delay:-2s}.f-lava i:nth-child(3){width:34px;height:34px;background:#22d3ee;left:62px;animation-delay:-3.5s}@keyframes f-lava{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-105px) scale(1.2) rotate(120deg)}}`,['ambient','lava','blob','glass'])

// Strange Inputs
add('Strange Inputs','Dial Input','A numeric field controlled by a physical rotating dial.',`<div class="f-dial-input"><input value="42" readonly><button>◉</button></div>`,`.f-dial-input{display:flex;align-items:center;gap:16px;padding:14px 18px;border-radius:20px;background:#12151b;border:1px solid #ffffff15;box-shadow:0 16px 30px #0007}.f-dial-input input{width:62px;border:0;background:transparent;color:#fff;font:1000 28px Inter;outline:none;text-align:center}.f-dial-input button{width:64px;height:64px;border-radius:50%;border:0;background:radial-gradient(circle,#4b5360,#1b1f26 62%);color:#22d3ee;font-size:25px;box-shadow:inset 0 3px #fff2,0 8px 14px #0007;cursor:pointer;transition:.25s}.f-dial-input button:active{transform:rotate(70deg) scale(.95)}`,['input','dial','numeric','physical'])
add('Strange Inputs','Orb Input','A glowing orb expands into a text input on focus.',`<label class="f-orb-input"><input placeholder="Ask…"><span>✦</span></label>`,`.f-orb-input{position:relative;display:flex;align-items:center;width:58px;height:58px;border-radius:999px;background:#0b0e14;border:1px solid #756cff66;box-shadow:0 0 24px #756cff33;transition:.45s;overflow:hidden}.f-orb-input:focus-within{width:220px}.f-orb-input input{flex:1;min-width:0;height:100%;border:0;outline:0;background:transparent;color:white;padding:0 16px 0 18px;opacity:0;transition:.3s}.f-orb-input:focus-within input{opacity:1}.f-orb-input span{min-width:58px;text-align:center;color:#a78bfa;font-size:20px;text-shadow:0 0 12px #8b5cf6}`,['input','orb','expand','glow'])
add('Strange Inputs','Ribbon Input','The field unfolds like a ribbon when activated.',`<label class="f-ribbon"><input placeholder="Type something"><span>INPUT</span></label>`,`.f-ribbon{position:relative;display:block;width:200px;height:54px;perspective:600px}.f-ribbon input{position:absolute;inset:0;border:1px solid #ffffff15;border-radius:14px;background:#101319;color:#fff;padding:0 15px;outline:none;transform:rotateX(75deg);transform-origin:top;opacity:.2;transition:.45s}.f-ribbon span{position:absolute;inset:0;display:grid;place-items:center;border-radius:14px;background:#756cff;color:#fff;font:900 10px Inter;letter-spacing:.16em;transition:.45s;transform-origin:bottom}.f-ribbon:focus-within input{transform:rotateX(0);opacity:1}.f-ribbon:focus-within span{transform:rotateX(-85deg);opacity:.2}`,['input','ribbon','fold','3d'])
add('Strange Inputs','Magnetic Search Input','The submit orb follows the pointer inside the field.',`<div class="f-mag-input"><input placeholder="Search"><button>⌕</button></div>`,`.f-mag-input{position:relative;width:230px;height:58px;border-radius:18px;background:#0d1016;border:1px solid #ffffff15;display:flex;align-items:center;padding-left:16px;box-shadow:inset 0 1px #fff1}.f-mag-input input{flex:1;min-width:0;border:0;background:transparent;color:#fff;outline:none}.f-mag-input button{position:absolute;right:7px;top:7px;width:44px;height:44px;border-radius:14px;border:0;background:#756cff;color:#fff;font-size:19px;transition:transform .08s;box-shadow:0 8px 16px #756cff33}`,['input','search','magnetic','pointer'],`const p=document.querySelector('.f-mag-input'),b=p.querySelector('button');p.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.max(1,Math.hypot(dx,dy)),f=Math.max(0,1-d/100);b.style.transform='translate('+(dx/d*f*10)+'px,'+(dy/d*f*10)+'px)'})`)
add('Strange Inputs','Liquid Underline Input','A liquid underline flows toward the cursor and focus point.',`<label class="f-liquid-input"><input placeholder="Your name"><i></i></label>`,`.f-liquid-input{position:relative;display:block;width:220px;padding-bottom:5px}.f-liquid-input input{width:100%;height:50px;border:0;background:transparent;color:#fff;outline:none;font:700 14px Inter;padding:0 4px;border-bottom:1px solid #ffffff18}.f-liquid-input i{position:absolute;left:0;bottom:0;width:35%;height:4px;border-radius:4px;background:linear-gradient(90deg,#22d3ee,#756cff);box-shadow:0 0 12px #22d3ee;transition:.4s cubic-bezier(.2,.8,.2,1)}.f-liquid-input:focus-within i{width:100%;border-radius:50% 20% 50% 20%}`,['input','liquid','underline','focus'])
add('Strange Inputs','Flip Label Input','The label flips backward as the field receives focus.',`<label class="f-flip-input"><span>EMAIL</span><input placeholder="name@example.com"></label>`,`.f-flip-input{position:relative;display:block;width:230px;height:64px;perspective:500px}.f-flip-input input{position:absolute;inset:12px 0 0;height:52px;border:1px solid #ffffff16;border-radius:14px;background:#101319;color:#fff;padding:0 14px;outline:none}.f-flip-input span{position:absolute;left:12px;top:0;z-index:2;padding:4px 8px;border-radius:8px;background:#756cff;color:#fff;font:900 8px Inter;letter-spacing:.12em;transform-origin:bottom;transition:.35s}.f-flip-input:focus-within span{transform:rotateX(180deg);background:#22d3ee}`,['input','label','flip','3d'])
add('Strange Inputs','Pixel Input','Each typed area looks like a retro pixel terminal.',`<div class="f-pixel-input"><span>></span><input placeholder="COMMAND"></div>`,`.f-pixel-input{width:235px;height:56px;border:4px solid #111827;background:#020617;box-shadow:6px 6px 0 #22d3ee,-3px -3px 0 #756cff;display:flex;align-items:center;padding:0 12px;font-family:monospace}.f-pixel-input span{color:#2dd4bf;font-size:18px;margin-right:8px}.f-pixel-input input{flex:1;min-width:0;border:0;background:transparent;color:#a7f3d0;outline:none;font:900 12px monospace;letter-spacing:.08em;text-shadow:0 0 8px #2dd4bf}`,['input','pixel','terminal','retro'])
add('Strange Inputs','Hologram Input','A scanline hologram field flickers subtly while focused.',`<label class="f-holo-input"><input placeholder="HOLO LINK"><i></i></label>`,`.f-holo-input{position:relative;display:block;width:230px;height:58px;border:1px solid #22d3ee66;border-radius:14px;background:#03141b88;overflow:hidden;box-shadow:inset 0 0 18px #22d3ee11,0 0 18px #22d3ee11}.f-holo-input:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#67e8f911 3px 4px);pointer-events:none}.f-holo-input input{position:relative;z-index:2;width:100%;height:100%;border:0;background:transparent;color:#a5f3fc;outline:none;padding:0 14px;font:800 12px monospace;letter-spacing:.08em}.f-holo-input i{position:absolute;left:-40%;top:0;width:30%;height:100%;background:linear-gradient(90deg,transparent,#67e8f944,transparent);transform:skewX(-18deg);transition:.6s}.f-holo-input:focus-within i{left:115%}`,['input','hologram','scanline','glow'])
add('Strange Inputs','Capsule Input','A capsule splits open to expose the editable field.',`<label class="f-caps-input"><span></span><i></i><input placeholder="SECRET"></label>`,`.f-caps-input{position:relative;display:block;width:230px;height:58px}.f-caps-input span,.f-caps-input i{position:absolute;top:0;width:50%;height:100%;background:linear-gradient(#303744,#15191f);border:1px solid #ffffff18;transition:.45s;z-index:2}.f-caps-input span{left:0;border-radius:29px 0 0 29px}.f-caps-input i{right:0;border-radius:0 29px 29px 0}.f-caps-input input{position:absolute;inset:4px;border:1px solid #756cff66;border-radius:25px;background:#090b10;color:#fff;outline:none;padding:0 18px;text-align:center;font:800 11px Inter}.f-caps-input:focus-within span{transform:translateX(-55px)}.f-caps-input:focus-within i{transform:translateX(55px)}`,['input','capsule','split','sci-fi'])
add('Strange Inputs','Waveform Input','Typing focus wakes an animated waveform under the field.',`<label class="f-wave-input"><input placeholder="Voice note"><span>${Array.from({length:10},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</span></label>`,`.f-wave-input{display:grid;gap:8px;width:230px}.f-wave-input input{height:48px;border:1px solid #ffffff15;border-radius:14px;background:#101319;color:#fff;outline:none;padding:0 14px}.f-wave-input span{height:26px;display:flex;align-items:center;justify-content:center;gap:3px}.f-wave-input i{width:4px;height:7px;border-radius:5px;background:#756cff;transition:.3s}.f-wave-input:focus-within i{animation:f-wave .8s ease-in-out infinite;animation-delay:calc(var(--i)*.06s)}@keyframes f-wave{50%{height:25px;background:#22d3ee}}`,['input','waveform','voice','animated'])

// Mini Devices
add('Mini Devices','Pocket Console','A tiny game console with animated screen and buttons.',`<div class="f-console"><screen>READY</screen><i></i><b></b><span></span></div>`,`.f-console{position:relative;width:150px;height:190px;border-radius:24px;background:linear-gradient(145deg,#525b68,#20242c);box-shadow:inset 0 3px #fff2,0 22px 35px #0008;padding:18px}.f-console screen{display:grid;place-items:center;width:114px;height:88px;border-radius:12px;background:#071b15;color:#86efac;font:900 11px monospace;box-shadow:inset 0 0 18px #000,0 0 10px #86efac22;animation:f-console 3s steps(1) infinite}.f-console i{position:absolute;left:28px;bottom:33px;width:38px;height:10px;background:#16191e;border-radius:5px}.f-console i:after{content:"";position:absolute;left:14px;top:-14px;width:10px;height:38px;background:#16191e;border-radius:5px}.f-console b,.f-console span{position:absolute;width:17px;height:17px;border-radius:50%;background:#fb7185;right:34px;bottom:45px;box-shadow:0 4px 5px #0005}.f-console span{right:17px;bottom:27px;background:#22d3ee}@keyframes f-console{0%,45%,100%{color:#86efac}50%{color:#fff;background:#0f3d30}}`,['device','console','game','mini'])
add('Mini Devices','Tiny Synth','A miniature synth with bouncing keys and glowing knobs.',`<div class="f-synth"><div>${Array.from({length:8},()=>'<i></i>').join('')}</div><b></b><b></b><span></span></div>`,`.f-synth{position:relative;width:220px;height:120px;border-radius:18px;background:linear-gradient(#2b303a,#14171c);box-shadow:0 18px 30px #0008;padding:16px}.f-synth div{position:absolute;left:14px;right:14px;bottom:14px;height:55px;display:flex;gap:3px}.f-synth i{flex:1;background:#f8fafc;border-radius:0 0 5px 5px;transform-origin:top;animation:f-key 2s ease-in-out infinite}.f-synth i:nth-child(2n){animation-delay:.16s}.f-synth i:nth-child(3n){animation-delay:.3s}.f-synth b{position:absolute;width:22px;height:22px;border-radius:50%;background:#756cff;top:15px;left:20px;box-shadow:0 0 12px #756cff}.f-synth b:nth-of-type(2){left:52px;background:#22d3ee;box-shadow:0 0 12px #22d3ee}.f-synth span{position:absolute;right:20px;top:20px;width:55px;height:10px;background:#071b15;box-shadow:inset 0 0 8px #000}@keyframes f-key{0%,85%,100%{transform:rotateX(0)}90%{transform:rotateX(-18deg);background:#cbd5e1}}`,['device','synth','music','mini'])
add('Mini Devices','Mini Camera','A camera lens focuses and flashes on click.',`<button class="f-camera"><i></i><b></b></button>`,`.f-camera{position:relative;width:170px;height:120px;border:0;border-radius:22px;background:linear-gradient(145deg,#434a56,#1b1f25);box-shadow:inset 0 3px #fff2,0 20px 32px #0008;cursor:pointer}.f-camera:before{content:"";position:absolute;width:58px;height:58px;border-radius:50%;left:56px;top:31px;background:radial-gradient(circle,#0b1320 0 24%,#2563eb 25% 34%,#05070a 35% 48%,#777f8d 49% 60%,#14171c 61%);box-shadow:inset 0 0 12px #000,0 0 0 4px #22262d}.f-camera i{position:absolute;width:10px;height:10px;border-radius:50%;background:#fb7185;right:18px;top:16px}.f-camera b{position:absolute;inset:0;background:#fff;opacity:0;border-radius:22px}.f-camera:focus:before{animation:f-focus .45s ease}.f-camera:focus b{animation:f-flash .3s ease}@keyframes f-focus{50%{transform:scale(.8);filter:brightness(1.5)}}@keyframes f-flash{0%{opacity:.9}100%{opacity:0}}`,['device','camera','lens','flash'])
add('Mini Devices','Pocket Radio','A radio tuner glides while an antenna gently sways.',`<div class="f-radio"><i></i><b></b><span></span></div>`,`.f-radio{position:relative;width:190px;height:125px;border-radius:20px;background:linear-gradient(145deg,#8b6f47,#3f2f20);box-shadow:inset 0 3px #fff2,0 20px 30px #0008}.f-radio:before{content:"";position:absolute;left:18px;top:20px;width:84px;height:64px;border-radius:10px;background:repeating-linear-gradient(90deg,#241a12 0 3px,transparent 3px 7px)}.f-radio i{position:absolute;right:24px;top:24px;width:42px;height:42px;border-radius:50%;background:radial-gradient(circle,#8b7358,#2a2118);box-shadow:inset 0 2px #fff2}.f-radio b{position:absolute;left:18px;right:18px;bottom:17px;height:10px;border-radius:7px;background:#231a12}.f-radio b:after{content:"";position:absolute;width:12px;height:16px;border-radius:4px;background:#fbbf24;left:10px;top:-3px;animation:f-tuner 5s ease-in-out infinite}.f-radio span{position:absolute;width:3px;height:75px;background:#9ca3af;right:18px;top:-48px;transform-origin:bottom;animation:f-antenna 4s ease-in-out infinite}@keyframes f-tuner{50%{left:125px}}@keyframes f-antenna{50%{rotate:8deg}}`,['device','radio','tuner','retro'])
add('Mini Devices','Mini Terminal','A tiny monitor prints fake command lines with a blinking cursor.',`<div class="f-terminal"><code>$ boot<br>> ui-kit<br>> ready<span>_</span></code></div>`,`.f-terminal{width:220px;height:140px;border:9px solid #343943;border-radius:18px;background:#020604;box-shadow:0 20px 32px #0008,inset 0 0 25px #000;padding:17px;color:#86efac;font:800 11px/1.7 monospace;text-shadow:0 0 8px #22c55e}.f-terminal code span{animation:f-cursor .8s steps(1) infinite}@keyframes f-cursor{50%{opacity:0}}`,['device','terminal','crt','mini'])
add('Mini Devices','Tiny Projector','A projector casts a moving beam onto a miniature screen.',`<div class="f-project"><i></i><b></b><span>RED UI</span></div>`,`.f-project{position:relative;width:230px;height:145px}.f-project i{position:absolute;left:12px;bottom:22px;width:70px;height:45px;border-radius:12px;background:linear-gradient(#525a67,#242931);box-shadow:0 10px 16px #0007}.f-project i:after{content:"";position:absolute;width:22px;height:22px;border-radius:50%;right:9px;top:11px;background:#fff7ae;box-shadow:0 0 15px #fef08a}.f-project b{position:absolute;left:72px;bottom:35px;width:95px;height:38px;clip-path:polygon(0 38%,100% 0,100% 100%,0 62%);background:linear-gradient(90deg,#fff5,transparent);filter:blur(1px)}.f-project span{position:absolute;right:10px;top:20px;width:100px;height:72px;border:1px solid #ffffff30;background:#ffffff0b;display:grid;place-items:center;color:#fff;font:900 10px Inter;letter-spacing:.12em;box-shadow:0 0 22px #fff1;animation:f-proj 2.5s ease-in-out infinite}@keyframes f-proj{50%{filter:brightness(1.4);transform:translateY(-3px)}}`,['device','projector','beam','mini'])
add('Mini Devices','Pocket Scanner','A handheld scanner sweeps a green beam over a code plate.',`<div class="f-pocket-scan"><i></i><span>|||| || |||| |</span></div>`,`.f-pocket-scan{position:relative;width:180px;height:125px;border-radius:20px;background:linear-gradient(#3c434f,#171b22);box-shadow:0 18px 30px #0008;padding:18px}.f-pocket-scan span{position:absolute;left:22px;right:22px;bottom:22px;height:38px;background:#f8fafc;color:#111827;font:900 14px/38px monospace;text-align:center;letter-spacing:2px}.f-pocket-scan i{position:absolute;left:18px;right:18px;height:2px;background:#4ade80;box-shadow:0 0 14px 3px #22c55e;z-index:2;animation:f-pocket-scan 2s ease-in-out infinite}@keyframes f-pocket-scan{0%,100%{top:24px}50%{top:98px}}`,['device','scanner','beam','handheld'])
add('Mini Devices','Tiny Server Rack','Three server trays blink and breathe with status lights.',`<div class="f-server"><i></i><i></i><i></i></div>`,`.f-server{display:grid;gap:7px;padding:12px;width:190px;border-radius:18px;background:#14171d;border:1px solid #ffffff15;box-shadow:0 20px 32px #0008}.f-server i{position:relative;height:34px;border-radius:8px;background:linear-gradient(#333944,#1a1e25);box-shadow:inset 0 2px #fff1}.f-server i:before{content:"";position:absolute;left:12px;top:13px;width:8px;height:8px;border-radius:50%;background:#2dd4bf;box-shadow:0 0 10px #2dd4bf;animation:f-server 2s ease-in-out infinite}.f-server i:nth-child(2):before{animation-delay:.45s}.f-server i:nth-child(3):before{background:#fbbf24;box-shadow:0 0 10px #fbbf24;animation-delay:.8s}@keyframes f-server{50%{opacity:.35}}`,['device','server','rack','status'])
add('Mini Devices','Mini Turntable','A tiny vinyl record spins while the tonearm moves inward.',`<div class="f-turn"><i></i><b></b></div>`,`.f-turn{position:relative;width:170px;height:140px;border-radius:18px;background:linear-gradient(#544637,#251d17);box-shadow:0 18px 30px #0008}.f-turn i{position:absolute;width:92px;height:92px;border-radius:50%;left:18px;top:23px;background:repeating-radial-gradient(circle,#111 0 3px,#222 4px 5px);box-shadow:0 8px 14px #0006;animation:f-record 3s linear infinite}.f-turn i:after{content:"";position:absolute;inset:34px;border-radius:50%;background:#f43f5e}.f-turn b{position:absolute;right:23px;top:25px;width:5px;height:86px;border-radius:4px;background:#a8a29e;transform-origin:top;animation:f-arm 8s ease-in-out infinite}@keyframes f-record{to{rotate:360deg}}@keyframes f-arm{0%,100%{rotate:-20deg}50%{rotate:8deg}}`,['device','turntable','music','vinyl'])
add('Mini Devices','Pocket Weather Station','A tiny station cycles through sun, cloud and rain states.',`<div class="f-weather-device"><span>☀</span><b>22°</b></div>`,`.f-weather-device{width:165px;height:135px;border-radius:22px;background:linear-gradient(145deg,#334155,#111827);border:1px solid #ffffff18;box-shadow:0 18px 32px #0008;display:grid;place-items:center;position:relative}.f-weather-device span{font-size:48px;color:#fbbf24;filter:drop-shadow(0 0 12px #fbbf24);animation:f-weather-state 6s steps(1) infinite}.f-weather-device b{position:absolute;bottom:14px;color:#e2e8f0;font:1000 12px Inter}@keyframes f-weather-state{0%,32%{filter:drop-shadow(0 0 12px #fbbf24)}33%,65%{filter:hue-rotate(140deg) saturate(.5);transform:translateY(3px)}66%,100%{filter:hue-rotate(190deg) brightness(.8);transform:translateY(7px)}}`,['device','weather','station','mini'])

export const finalSeedDesigns = out
export const finalCategories = [...new Set(out.map((design) => design.category))]
