import type { CustomDesign } from './types'

const seed = (
  id: string,
  name: string,
  category: string,
  description: string,
  html: string,
  css: string,
  tags: string[],
): CustomDesign => ({
  id: `custom-${id}`,
  name,
  category,
  description,
  html,
  css,
  tags,
  source: 'seed',
})

export const funSeedDesigns: CustomDesign[] = [
  seed(
    'folder-burst',
    'Folder Burst 3D',
    '3D Toys',
    'A tactile folder that opens and fans five files into real perspective depth.',
    `<label class="red-folder">
  <input type="checkbox" />
  <span class="red-folder-back"></span>
  <span class="red-file red-file-5">AI</span>
  <span class="red-file red-file-4">IMG</span>
  <span class="red-file red-file-3">PDF</span>
  <span class="red-file red-file-2">DOC</span>
  <span class="red-file red-file-1">RED</span>
  <span class="red-folder-front"><b>FILES</b></span>
</label>`,
    `.red-folder{position:relative;width:180px;height:132px;display:block;perspective:1000px;cursor:pointer;transform-style:preserve-3d}.red-folder input{position:absolute;opacity:0}.red-folder-back,.red-folder-front{position:absolute;left:0;bottom:0;width:100%;height:105px;border-radius:15px;background:linear-gradient(145deg,#796dff,#5146c8);box-shadow:0 18px 32px #0007,inset 0 2px #fff4}.red-folder-back:before{content:"";position:absolute;left:0;top:-20px;width:75px;height:35px;border-radius:14px 14px 0 0;background:#8e84ff}.red-folder-front{z-index:10;display:grid;place-items:center;transform-origin:bottom;transition:transform .55s cubic-bezier(.2,.9,.2,1.25);background:linear-gradient(165deg,#8e84ff,#5b50dd)}.red-folder-front b{font:900 13px Inter,sans-serif;letter-spacing:.18em;color:#e9e7ff}.red-file{position:absolute;left:16px;bottom:16px;width:148px;height:82px;border-radius:9px;padding:12px;font:900 10px Inter,sans-serif;color:#fff;box-shadow:0 8px 18px #0005;transition:transform .58s cubic-bezier(.34,1.56,.64,1);transform-origin:bottom center}.red-file-1{background:#ff5f78;z-index:9}.red-file-2{background:#ffae55;z-index:8}.red-file-3{background:#4f9dff;z-index:7}.red-file-4{background:#21d4d4;z-index:6}.red-file-5{background:#a06ef5;z-index:5}.red-folder input:checked~.red-folder-front{transform:rotateX(-58deg)}.red-folder input:checked~.red-file-1{transform:translate3d(-24px,-82px,38px) rotate(-11deg)}.red-folder input:checked~.red-file-2{transform:translate3d(24px,-66px,30px) rotate(9deg)}.red-folder input:checked~.red-file-3{transform:translate3d(-12px,-50px,22px) rotate(-7deg)}.red-folder input:checked~.red-file-4{transform:translate3d(16px,-34px,14px) rotate(7deg)}.red-folder input:checked~.red-file-5{transform:translate3d(-4px,-19px,8px) rotate(-3deg)}.red-folder:after{content:"tap";position:absolute;right:-6px;top:-34px;color:#9d97ff;font:800 10px Inter,sans-serif;animation:red-folder-hint 2s ease-in-out infinite}@keyframes red-folder-hint{50%{transform:translateY(6px)}}`,
    ['3d', 'folder', 'perspective', 'files', 'click'],
  ),
  seed(
    'orbit-core',
    'Orbit Core',
    'Loaders',
    'A glowing reactor core with three orbital tracks and counter-rotating satellites.',
    `<div class="red-orbit-core"><i></i><i></i><i></i><b></b></div>`,
    `.red-orbit-core{position:relative;width:120px;height:120px;border-radius:50%;display:grid;place-items:center;filter:drop-shadow(0 0 24px #776dff66);transform-style:preserve-3d}.red-orbit-core b{width:42px;height:42px;border-radius:50%;background:radial-gradient(circle at 35% 25%,#fff 0 5%,#8f86ff 18%,#4637b8 55%,#090a0e 72%);box-shadow:0 0 24px #756cffaa,inset 0 0 18px #fff3;animation:red-core-pulse 1.8s ease-in-out infinite}.red-orbit-core i{position:absolute;inset:10px;border:1px solid #756cff55;border-radius:50%;transform:rotateX(68deg);animation:red-orbit-spin 3s linear infinite}.red-orbit-core i:after{content:"";position:absolute;left:50%;top:-4px;width:8px;height:8px;border-radius:50%;background:#22d3ee;box-shadow:0 0 12px #22d3ee}.red-orbit-core i:nth-child(2){inset:20px;transform:rotateY(66deg);animation-duration:2.4s;animation-direction:reverse;border-color:#f472b655}.red-orbit-core i:nth-child(2):after{background:#f472b6;box-shadow:0 0 12px #f472b6}.red-orbit-core i:nth-child(3){inset:2px;transform:rotateX(74deg) rotateZ(35deg);animation-duration:4.2s;border-color:#2dd4bf44}.red-orbit-core i:nth-child(3):after{background:#2dd4bf;box-shadow:0 0 12px #2dd4bf}@keyframes red-orbit-spin{to{rotate:360deg}}@keyframes red-core-pulse{50%{transform:scale(1.13);filter:hue-rotate(30deg)}}`,
    ['loader', 'orbit', 'reactor', 'glow', '3d'],
  ),
  seed(
    'jelly-launch',
    'Jelly Launch',
    'Buttons',
    'A soft squishy button that wobbles like a gummy object before snapping back.',
    `<button class="red-jelly">BOING!</button>`,
    `.red-jelly{position:relative;border:0;padding:18px 28px;border-radius:26px 20px 29px 22px;color:white;font:900 14px Inter,sans-serif;letter-spacing:.08em;cursor:pointer;background:linear-gradient(145deg,#ff72ae,#8b5cf6 70%);box-shadow:inset 0 3px #fff5,inset 0 -12px 20px #511e8355,0 20px 34px #7029a644;animation:red-jelly-idle 4s ease-in-out infinite;transition:filter .2s}.red-jelly:before{content:"";position:absolute;left:15%;right:15%;top:8px;height:8px;border-radius:50%;background:#fff5;filter:blur(4px)}.red-jelly:hover{animation:red-jelly-wobble .65s cubic-bezier(.2,.9,.2,1.25);filter:saturate(1.2)}.red-jelly:active{transform:scaleX(1.12) scaleY(.78)}@keyframes red-jelly-idle{50%{border-radius:20px 30px 21px 28px;transform:translateY(-3px)}}@keyframes red-jelly-wobble{0%,100%{transform:scale(1)}25%{transform:scaleX(1.18) scaleY(.84) rotate(-2deg)}55%{transform:scaleX(.9) scaleY(1.12) rotate(2deg)}75%{transform:scaleX(1.05) scaleY(.96)}}`,
    ['button', 'jelly', 'playful', 'squish', 'animated'],
  ),
  seed(
    'rocket-launch',
    'Pocket Rocket',
    'Buttons',
    'A tiny launch button whose rocket lifts off through a glowing exhaust trail.',
    `<button class="red-rocket"><span>LAUNCH</span><i>🚀</i><b></b></button>`,
    `.red-rocket{position:relative;width:145px;height:58px;border:1px solid #ffffff20;border-radius:18px;background:linear-gradient(160deg,#171a24,#0b0d12);color:#fff;font:900 12px Inter,sans-serif;letter-spacing:.12em;cursor:pointer;overflow:visible;box-shadow:inset 0 1px #fff2,0 18px 30px #0006}.red-rocket span{position:absolute;left:18px;top:22px}.red-rocket i{position:absolute;right:18px;top:15px;font-style:normal;font-size:25px;transition:transform .65s cubic-bezier(.2,.8,.2,1),opacity .5s}.red-rocket b{position:absolute;right:27px;top:40px;width:5px;height:5px;border-radius:50%;background:#22d3ee;box-shadow:0 0 12px 4px #22d3ee;opacity:0}.red-rocket:hover i{transform:translate(24px,-46px) rotate(18deg) scale(1.25);opacity:.15}.red-rocket:hover b{animation:red-exhaust .65s ease-out}.red-rocket:active{transform:translateY(3px) scale(.97)}@keyframes red-exhaust{0%{opacity:1;transform:scale(1)}100%{opacity:0;transform:translate(-12px,20px) scale(4)}}`,
    ['button', 'rocket', 'launch', 'fun', 'motion'],
  ),
  seed(
    'cube-switch',
    'Cube Switch',
    'Toggles',
    'A checkbox hidden inside a physical cube that flips between OFF and ON faces.',
    `<label class="red-cube-switch"><input type="checkbox"/><span class="red-cube"><b>OFF</b><i>ON</i></span></label>`,
    `.red-cube-switch{display:block;width:82px;height:54px;perspective:500px;cursor:pointer}.red-cube-switch input{position:absolute;opacity:0}.red-cube{position:relative;display:block;width:100%;height:100%;transform-style:preserve-3d;transition:transform .55s cubic-bezier(.2,.8,.2,1)}.red-cube b,.red-cube i{position:absolute;inset:0;display:grid;place-items:center;border-radius:13px;color:white;font:900 11px Inter,sans-serif;letter-spacing:.1em;backface-visibility:hidden;border:1px solid #ffffff24;box-shadow:0 16px 24px #0005,inset 0 2px #fff3}.red-cube b{background:linear-gradient(145deg,#313540,#171920);transform:translateZ(16px)}.red-cube i{font-style:normal;background:linear-gradient(145deg,#2dd4bf,#0f766e);transform:rotateX(180deg) translateZ(16px);box-shadow:0 0 25px #2dd4bf44}.red-cube-switch input:checked+.red-cube{transform:rotateX(180deg)}.red-cube-switch:hover .red-cube{filter:brightness(1.12)}`,
    ['toggle', 'cube', '3d', 'flip', 'physical'],
  ),
  seed(
    'holo-card',
    'Hologram ID Card',
    'Cards',
    'A floating holographic card with scanlines, shifting light and a faux depth plane.',
    `<article class="red-holo"><small>RED // ACCESS</small><h3>JARVIS</h3><p>INTERFACE NODE 07</p><i></i></article>`,
    `.red-holo{position:relative;width:230px;height:145px;padding:20px;border-radius:18px;color:#c8fbff;background:linear-gradient(145deg,#06222a88,#111529cc);border:1px solid #42e8ff77;box-shadow:inset 0 0 28px #22d3ee16,0 18px 40px #0007,0 0 30px #22d3ee14;overflow:hidden;transform:perspective(700px) rotateX(6deg) rotateY(-6deg);transition:transform .35s ease}.red-holo:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 4px,#7ef9ff12 4px 5px);animation:red-scanlines 1s linear infinite}.red-holo:after{content:"";position:absolute;width:180%;height:50%;left:-40%;top:-70%;background:linear-gradient(transparent,#74efff28,transparent);transform:rotate(-12deg);animation:red-holo-sweep 3s ease-in-out infinite}.red-holo:hover{transform:perspective(700px) rotateX(-3deg) rotateY(5deg) translateY(-6px)}.red-holo h3{margin:26px 0 5px;font:900 28px Inter,sans-serif;letter-spacing:.08em;text-shadow:0 0 14px #22d3ee}.red-holo p,.red-holo small{font:700 9px Inter,sans-serif;letter-spacing:.16em;opacity:.7}.red-holo i{position:absolute;right:20px;bottom:18px;width:10px;height:10px;border-radius:50%;background:#2dd4bf;box-shadow:0 0 12px #2dd4bf}@keyframes red-scanlines{to{background-position:0 5px}}@keyframes red-holo-sweep{50%{top:125%}}`,
    ['card', 'hologram', 'scanlines', '3d', 'cyber'],
  ),
  seed(
    'flip-ticket',
    'Floating Flip Ticket',
    'Cards',
    'A ticket that floats gently and reveals its back side with a 3D flip.',
    `<div class="red-ticket"><div class="red-ticket-inner"><section>BOARDING<br/><b>RED 07</b></section><section>ACCESS<br/><b>GRANTED</b></section></div></div>`,
    `.red-ticket{width:210px;height:110px;perspective:900px;animation:red-ticket-float 3s ease-in-out infinite}.red-ticket-inner{position:relative;width:100%;height:100%;transform-style:preserve-3d;transition:transform .7s cubic-bezier(.2,.8,.2,1)}.red-ticket:hover .red-ticket-inner{transform:rotateY(180deg)}.red-ticket section{position:absolute;inset:0;backface-visibility:hidden;border-radius:14px;padding:22px;color:#17191f;background:linear-gradient(145deg,#fff9da,#ffd166);font:700 11px Inter,sans-serif;letter-spacing:.12em;box-shadow:0 20px 35px #0006}.red-ticket section:before,.red-ticket section:after{content:"";position:absolute;top:46px;width:18px;height:18px;border-radius:50%;background:#090a0e}.red-ticket section:before{left:-9px}.red-ticket section:after{right:-9px}.red-ticket section:nth-child(2){transform:rotateY(180deg);background:linear-gradient(145deg,#91f7d4,#2dd4bf)}.red-ticket b{display:block;margin-top:12px;font-size:22px}@keyframes red-ticket-float{50%{transform:translateY(-10px) rotateZ(1deg)}}`,
    ['card', 'ticket', 'flip', 'float', '3d'],
  ),
  seed(
    'gear-reactor',
    'Gear Reactor',
    'Loaders',
    'Three interlocking neon gears rotate at different speeds around a tiny energy core.',
    `<div class="red-gears"><i>✹</i><i>✹</i><i>✹</i><b></b></div>`,
    `.red-gears{position:relative;width:130px;height:100px}.red-gears i{position:absolute;font-style:normal;font-size:58px;line-height:1;color:#756cff;text-shadow:0 0 18px #756cff88;animation:red-gear 3.2s linear infinite}.red-gears i:nth-child(1){left:8px;top:20px}.red-gears i:nth-child(2){left:55px;top:0;color:#22d3ee;animation-direction:reverse;animation-duration:2.4s}.red-gears i:nth-child(3){left:69px;top:45px;color:#f472b6;font-size:42px;animation-duration:1.9s}.red-gears b{position:absolute;left:56px;top:43px;width:14px;height:14px;border-radius:50%;background:#fff;box-shadow:0 0 14px 5px #fff,0 0 28px 10px #756cff}@keyframes red-gear{to{transform:rotate(360deg)}}`,
    ['loader', 'gear', 'mechanical', 'neon', 'processing'],
  ),
  seed(
    'pixel-wave',
    'Pixel Matrix Wave',
    'Loaders',
    'A 5×5 pixel field ripples diagonally like a tiny living data matrix.',
    `<div class="red-pixels">${Array.from({ length: 25 }, (_, i) => `<i style="--n:${i}"></i>`).join('')}</div>`,
    `.red-pixels{display:grid;grid-template-columns:repeat(5,10px);gap:6px;transform:rotateX(58deg) rotateZ(45deg);transform-style:preserve-3d}.red-pixels i{width:10px;height:10px;border-radius:2px;background:#6f67ff;box-shadow:0 0 10px #6f67ff55;animation:red-pixel 1.6s ease-in-out infinite;animation-delay:calc(var(--n)*-.045s)}@keyframes red-pixel{0%,100%{transform:translateZ(0);opacity:.28}50%{transform:translateZ(28px) scale(1.35);opacity:1;background:#22d3ee;box-shadow:0 0 16px #22d3ee}}`,
    ['loader', 'pixel', 'matrix', '3d', 'wave'],
  ),
  seed(
    'tap-hand',
    'Tap-Tap Hand',
    'Motion',
    'A playful CSS hand whose four fingers tap in a staggered rhythm.',
    `<div class="red-hand"><b></b><i></i><i></i><i></i><i></i><span></span></div>`,
    `.red-hand{position:relative;width:100px;height:90px;transform:rotate(-8deg)}.red-hand b{position:absolute;left:30px;top:36px;width:62px;height:44px;border-radius:18px 30px 24px 16px;background:#e7bd78;box-shadow:inset -8px -8px #b8874d55,0 12px 20px #0004}.red-hand i{position:absolute;width:17px;height:50px;border-radius:12px;background:#e7bd78;bottom:45px;transform-origin:50% 100%;animation:red-finger .85s ease-in-out infinite}.red-hand i:nth-of-type(1){left:33px;animation-delay:0s}.red-hand i:nth-of-type(2){left:49px;height:58px;animation-delay:.08s}.red-hand i:nth-of-type(3){left:65px;height:54px;animation-delay:.16s}.red-hand i:nth-of-type(4){left:80px;height:43px;animation-delay:.24s}.red-hand span{position:absolute;left:6px;top:51px;width:46px;height:19px;border-radius:15px;background:#e7bd78;transform:rotate(-28deg);transform-origin:right center}@keyframes red-finger{0%,100%{transform:rotate(0)}45%{transform:rotate(34deg) translateY(4px)}}`,
    ['motion', 'hand', 'gesture', 'tutorial', 'playful'],
  ),
  seed(
    'heart-toggle',
    'Heartbeat Toggle',
    'Toggles',
    'A tiny 3D heart fills, pulses and throws a soft shockwave when selected.',
    `<label class="red-heart"><input type="checkbox"/><span>♥</span><i></i></label>`,
    `.red-heart{position:relative;display:grid;place-items:center;width:72px;height:72px;cursor:pointer}.red-heart input{position:absolute;opacity:0}.red-heart span{font-size:48px;color:#30333d;text-shadow:0 5px 8px #0008;transition:.35s cubic-bezier(.2,1.3,.3,1);z-index:2}.red-heart i{position:absolute;width:48px;height:48px;border-radius:50%;border:1px solid #ff5f8a;opacity:0}.red-heart input:checked+span{color:#ff5f8a;transform:scale(1.2);text-shadow:0 0 18px #ff5f8a88;animation:red-heart-beat .8s ease}.red-heart input:checked~i{animation:red-heart-ring .7s ease-out}@keyframes red-heart-beat{30%{transform:scale(.92)}55%{transform:scale(1.3)}100%{transform:scale(1.2)}}@keyframes red-heart-ring{0%{opacity:.8;transform:scale(.5)}100%{opacity:0;transform:scale(1.8)}}`,
    ['toggle', 'heart', 'love', 'pulse', 'fun'],
  ),
  seed(
    'mini-printer',
    'Mini Printer',
    'Motion',
    'A tiny desktop printer continuously feeds a paper strip with animated lines.',
    `<div class="red-printer"><div class="red-paper"><i></i><i></i><i></i></div><b></b><span></span></div>`,
    `.red-printer{position:relative;width:120px;height:100px;perspective:500px}.red-printer b{position:absolute;left:15px;top:32px;width:90px;height:55px;border-radius:12px;background:linear-gradient(#323641,#17191f);box-shadow:0 15px 24px #0006,inset 0 2px #fff2}.red-printer span{position:absolute;left:26px;top:46px;width:68px;height:17px;border-radius:5px;background:#090a0d;box-shadow:inset 0 2px 4px #000}.red-paper{position:absolute;z-index:4;left:34px;top:8px;width:52px;height:55px;padding:8px;background:#f7f2df;border-radius:3px;box-shadow:0 5px 10px #0003;animation:red-print 2.2s ease-in-out infinite}.red-paper i{display:block;height:2px;margin:5px 0;background:#56606f;border-radius:2px;opacity:.5}.red-paper i:nth-child(2){width:75%}.red-paper i:nth-child(3){width:55%}@keyframes red-print{0%,20%{transform:translateY(0)}70%{transform:translateY(30px)}100%{transform:translateY(0)}}`,
    ['motion', 'printer', 'process', 'paper', '3d'],
  ),
  seed(
    'magnetic-orb',
    'Magnetic Orb Button',
    'Buttons',
    'A glass button with a luminous orb that jumps across the surface on hover.',
    `<button class="red-magnet"><span>ATTRACT</span><i></i></button>`,
    `.red-magnet{position:relative;width:150px;height:58px;border:1px solid #ffffff20;border-radius:18px;background:linear-gradient(145deg,#ffffff12,#ffffff05);backdrop-filter:blur(14px);color:white;font:900 12px Inter,sans-serif;letter-spacing:.1em;cursor:pointer;overflow:hidden;box-shadow:inset 0 1px #fff3,0 18px 30px #0005}.red-magnet span{position:relative;z-index:2}.red-magnet i{position:absolute;width:30px;height:30px;border-radius:50%;left:-18px;top:14px;background:radial-gradient(circle at 30% 25%,white,#22d3ee 22%,#6f67ff 65%);box-shadow:0 0 26px #22d3eeaa;transition:left .6s cubic-bezier(.2,.9,.2,1.2),transform .35s}.red-magnet:hover i{left:136px;transform:scale(1.25)}.red-magnet:hover{box-shadow:inset 0 1px #fff4,0 0 35px #6f67ff33}`,
    ['button', 'orb', 'magnetic', 'glass', 'glow'],
  ),
  seed(
    'liquid-capsule',
    'Liquid Capsule',
    'Buttons',
    'A capsule slowly fills with liquid light and sloshes when hovered.',
    `<button class="red-liquid"><span>CHARGE</span><i></i></button>`,
    `.red-liquid{position:relative;width:155px;height:58px;border:1px solid #ffffff26;border-radius:999px;background:#101218;color:#fff;font:900 12px Inter,sans-serif;letter-spacing:.14em;overflow:hidden;cursor:pointer;box-shadow:inset 0 0 18px #0008,0 16px 30px #0005}.red-liquid span{position:relative;z-index:3;mix-blend-mode:screen}.red-liquid i{position:absolute;z-index:1;left:-20%;top:62%;width:140%;height:130%;border-radius:42%;background:linear-gradient(145deg,#22d3ee,#6f67ff);animation:red-liquid-spin 5s linear infinite;transition:top .7s cubic-bezier(.2,.8,.2,1)}.red-liquid:hover i{top:18%}.red-liquid:active i{top:-12%}@keyframes red-liquid-spin{to{transform:rotate(360deg)}}`,
    ['button', 'liquid', 'capsule', 'fill', 'animated'],
  ),
  seed(
    'crystal-card',
    'Crystal Shard Card',
    'Cards',
    'A faceted translucent card with changing highlights and a floating inner shard.',
    `<div class="red-crystal"><b>PRISM</b><span>07</span><i></i></div>`,
    `.red-crystal{position:relative;width:210px;height:145px;clip-path:polygon(10% 0,88% 4%,100% 34%,92% 100%,12% 94%,0 45%);background:linear-gradient(135deg,#ffffff45,#756cff66 34%,#22d3ee33 72%,#ffffff26);backdrop-filter:blur(16px);box-shadow:0 22px 50px #2c2c8a55;display:grid;place-items:center;transform:perspective(700px) rotateX(5deg) rotateY(-7deg);transition:.45s;color:white}.red-crystal:before{content:"";position:absolute;inset:2px;clip-path:inherit;background:linear-gradient(160deg,#ffffff18,#06070a44)}.red-crystal:after{content:"";position:absolute;width:35%;height:180%;left:-55%;top:-40%;background:linear-gradient(90deg,transparent,#fff9,transparent);transform:rotate(20deg);transition:left .8s}.red-crystal:hover:after{left:130%}.red-crystal:hover{transform:perspective(700px) rotateX(-3deg) rotateY(7deg) translateY(-6px)}.red-crystal b,.red-crystal span{position:relative;z-index:3}.red-crystal b{font:900 22px Inter,sans-serif;letter-spacing:.2em}.red-crystal span{position:absolute;right:24px;bottom:20px;font:800 10px Inter,sans-serif;opacity:.65}.red-crystal i{position:absolute;width:28px;height:55px;clip-path:polygon(50% 0,100% 45%,65% 100%,15% 74%,0 25%);background:#fff3;right:28px;top:17px;animation:red-shard 3s ease-in-out infinite}@keyframes red-shard{50%{transform:translateY(-8px) rotate(8deg)}}`,
    ['card', 'crystal', 'prism', 'glass', '3d'],
  ),
  seed(
    'black-hole',
    'Pocket Black Hole',
    'Loaders',
    'A miniature black hole bends three luminous orbital particles around a dark core.',
    `<div class="red-hole"><b></b><i></i><i></i><i></i></div>`,
    `.red-hole{position:relative;width:125px;height:125px;display:grid;place-items:center;border-radius:50%;background:radial-gradient(circle,#000 0 25%,#3b2b8460 28%,transparent 58%);filter:drop-shadow(0 0 20px #6f67ff55)}.red-hole b{width:42px;height:42px;border-radius:50%;background:#000;box-shadow:0 0 0 4px #171225,0 0 28px 9px #6f67ff66}.red-hole i{position:absolute;inset:8px;border-radius:50%;border:1px solid #756cff44;animation:red-hole-orbit 2.6s linear infinite}.red-hole i:after{content:"";position:absolute;left:50%;top:-4px;width:8px;height:8px;border-radius:50%;background:#22d3ee;box-shadow:0 0 12px #22d3ee}.red-hole i:nth-of-type(2){inset:20px;animation-duration:1.8s;animation-direction:reverse;transform:rotateX(65deg)}.red-hole i:nth-of-type(2):after{background:#f472b6;box-shadow:0 0 12px #f472b6}.red-hole i:nth-of-type(3){inset:-2px;animation-duration:3.7s;transform:rotateY(62deg)}@keyframes red-hole-orbit{to{rotate:360deg}}`,
    ['loader', 'black-hole', 'orbit', 'space', 'glow'],
  ),
  seed(
    'arcade-smash',
    'Arcade Smash',
    'Buttons',
    'A chunky arcade control with real travel distance and a glowing red dome.',
    `<button class="red-arcade" aria-label="Smash"><span>SMASH</span></button>`,
    `.red-arcade{position:relative;width:130px;height:78px;border:0;border-radius:50%;background:linear-gradient(#30343d,#16181e);cursor:pointer;box-shadow:0 12px 0 #07080b,0 22px 28px #0008,inset 0 3px #fff2;transition:transform .1s,box-shadow .1s}.red-arcade span{position:absolute;left:50%;top:44%;transform:translate(-50%,-50%);width:90px;height:52px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 50% 18%,#ffb2bf,#ff4565 52%,#9b0b2a);color:white;font:1000 11px Inter,sans-serif;letter-spacing:.08em;text-shadow:0 2px 3px #64091b;box-shadow:inset 0 5px 7px #fff5,inset 0 -9px 12px #65091c88,0 0 22px #ff456544}.red-arcade:hover span{filter:brightness(1.12)}.red-arcade:active{transform:translateY(10px);box-shadow:0 2px 0 #07080b,0 8px 12px #0006}`,
    ['button', 'arcade', 'physical', 'press', '3d'],
  ),
  seed(
    'book-pop',
    'Pop-Up Book',
    '3D Toys',
    'A miniature book whose cover opens and reveals a floating inner page.',
    `<div class="red-book"><div class="red-book-back">UI<br/>KIT</div><div class="red-book-page">HELLO</div><div class="red-book-cover">RED</div></div>`,
    `.red-book{position:relative;width:150px;height:105px;perspective:800px;transform-style:preserve-3d}.red-book-back,.red-book-page,.red-book-cover{position:absolute;inset:0;border-radius:8px 14px 14px 8px;transform-origin:left center;transition:transform .7s cubic-bezier(.2,.8,.2,1);display:grid;place-items:center}.red-book-back{background:#372f82;color:#9f98ff;font:900 18px/1.5 Inter,sans-serif;box-shadow:0 20px 35px #0006}.red-book-page{inset:6px;background:#f4f0df;color:#2a2b32;font:900 13px Inter,sans-serif;transform:translateZ(3px)}.red-book-cover{background:linear-gradient(145deg,#756cff,#4b42bd);color:white;font:1000 24px Inter,sans-serif;letter-spacing:.15em;box-shadow:inset -5px 0 #0002,inset 0 2px #fff3}.red-book:hover .red-book-cover{transform:rotateY(-145deg)}.red-book:hover .red-book-page{transform:rotateY(-28deg) translateZ(18px)}.red-book:hover{filter:drop-shadow(0 20px 20px #0005)}`,
    ['3d', 'book', 'flip', 'object', 'hover'],
  ),
  seed(
    'star-crack',
    'Cracked Star',
    'Loaders',
    'Layered star fragments rotate at different depths like a tiny crystalline portal.',
    `<div class="red-star"><i></i><i></i><i></i><i></i><i></i></div>`,
    `.red-star{position:relative;width:110px;height:110px;display:grid;place-items:center;transform-style:preserve-3d}.red-star i{position:absolute;width:92px;height:92px;clip-path:polygon(50% 0,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%);background:linear-gradient(145deg,#ffffff,#9f98ff);opacity:.13;animation:red-star-spin 5s linear infinite;filter:drop-shadow(0 0 10px #756cff)}.red-star i:nth-child(2){width:76px;height:76px;opacity:.22;animation-duration:4s;animation-direction:reverse}.red-star i:nth-child(3){width:59px;height:59px;opacity:.35;animation-duration:3s}.red-star i:nth-child(4){width:42px;height:42px;opacity:.55;animation-duration:2s;animation-direction:reverse}.red-star i:nth-child(5){width:24px;height:24px;opacity:1;background:#fff;box-shadow:0 0 20px #fff,0 0 40px #756cff}@keyframes red-star-spin{50%{filter:hue-rotate(80deg) drop-shadow(0 0 12px #22d3ee)}to{transform:rotate(360deg)}}`,
    ['loader', 'star', 'crystal', 'layers', 'animated'],
  ),
  seed(
    'slinky-loader',
    'Neon Slinky',
    'Loaders',
    'Seven glowing rings bounce through depth like a compressed neon spring.',
    `<div class="red-slinky">${Array.from({ length: 7 }, (_, i) => `<i style="--i:${i}"></i>`).join('')}</div>`,
    `.red-slinky{position:relative;width:120px;height:100px;perspective:600px;transform-style:preserve-3d}.red-slinky i{position:absolute;left:20px;top:38px;width:80px;height:25px;border:3px solid #756cff;border-radius:50%;box-shadow:0 0 12px #756cff88,inset 0 0 8px #756cff66;animation:red-slinky 1.45s ease-in-out infinite;animation-delay:calc(var(--i)*-.11s)}.red-slinky i:nth-child(even){border-color:#22d3ee;box-shadow:0 0 12px #22d3ee88,inset 0 0 8px #22d3ee66}@keyframes red-slinky{0%,100%{transform:translateY(-24px) rotateX(62deg) scale(.68);opacity:.28}50%{transform:translateY(25px) rotateX(62deg) scale(1.08);opacity:1}}`,
    ['loader', 'slinky', 'spring', '3d', 'neon'],
  ),
  seed(
    'eye-button',
    'Blinking Eye Button',
    'Buttons',
    'A weird little eye button that looks sideways on hover and blinks when pressed.',
    `<button class="red-eye"><i></i><span>LOOK</span></button>`,
    `.red-eye{position:relative;width:150px;height:64px;border:0;border-radius:56% 44% 55% 45%/66% 66% 34% 34%;background:#f7f7fa;color:#161820;cursor:pointer;box-shadow:0 18px 28px #0005,inset 0 -8px 15px #cfd1da;overflow:hidden;transition:.25s}.red-eye i{position:absolute;left:19px;top:16px;width:32px;height:32px;border-radius:50%;background:#756cff;box-shadow:inset 0 0 0 8px #262933,0 0 15px #756cff66;transition:left .28s cubic-bezier(.2,.8,.2,1),transform .16s}.red-eye i:after{content:"";position:absolute;left:12px;top:8px;width:5px;height:5px;border-radius:50%;background:white}.red-eye span{position:absolute;right:24px;top:24px;font:1000 11px Inter,sans-serif;letter-spacing:.12em}.red-eye:hover i{left:93px}.red-eye:hover span{right:84px}.red-eye:active i{transform:scaleY(.12)}.red-eye:active{transform:scale(.96)}`,
    ['button', 'eye', 'character', 'blink', 'playful'],
  ),
  seed(
    'data-depth-card',
    'Data Depth Card',
    'Cards',
    'A compact stat card where lines, labels and the action orb sit on different Z planes.',
    `<article class="red-depth"><header>LIVE NODE <b>●</b></header><h2>12,847</h2><div><i></i><i></i><i></i><i></i><i></i></div><footer>+18.4% / week</footer></article>`,
    `.red-depth{position:relative;width:225px;height:160px;padding:20px;border-radius:22px;color:white;background:radial-gradient(circle at 50% 0,#343744,#15171d 68%);border:1px solid #ffffff1f;box-shadow:0 24px 50px #0007,inset 0 2px #fff2;transform:perspective(700px) rotateX(5deg) rotateY(-6deg);transform-style:preserve-3d;transition:.35s}.red-depth:hover{transform:perspective(700px) rotateX(-3deg) rotateY(5deg) translateY(-5px)}.red-depth header{font:800 9px Inter,sans-serif;letter-spacing:.13em;color:#9299a7;transform:translateZ(24px)}.red-depth header b{float:right;color:#2dd4bf;text-shadow:0 0 10px #2dd4bf}.red-depth h2{margin:16px 0 12px;font:900 32px Inter,sans-serif;transform:translateZ(35px)}.red-depth div{height:34px;display:flex;align-items:end;gap:7px;transform:translateZ(22px)}.red-depth div i{display:block;width:24px;border-radius:5px 5px 2px 2px;background:linear-gradient(#756cff,#4038a8);animation:red-bars 2s ease-in-out infinite}.red-depth div i:nth-child(1){height:35%}.red-depth div i:nth-child(2){height:62%;animation-delay:.1s}.red-depth div i:nth-child(3){height:45%;animation-delay:.2s}.red-depth div i:nth-child(4){height:86%;animation-delay:.3s}.red-depth div i:nth-child(5){height:70%;animation-delay:.4s}.red-depth footer{margin-top:9px;font:700 9px Inter,sans-serif;color:#2dd4bf;transform:translateZ(28px)}@keyframes red-bars{50%{filter:brightness(1.5);transform:scaleY(1.12)}}`,
    ['card', 'data', 'depth', '3d', 'stats'],
  ),
  seed(
    'bubble-switch',
    'Bubble Switch',
    'Toggles',
    'An organic toggle where the knob morphs from a purple bubble into a mint bubble.',
    `<label class="red-bubble-switch"><input type="checkbox"/><span><i></i></span></label>`,
    `.red-bubble-switch{display:block;width:82px;height:42px;cursor:pointer}.red-bubble-switch input{position:absolute;opacity:0}.red-bubble-switch span{position:relative;display:block;width:100%;height:100%;border-radius:999px;background:#171922;border:1px solid #ffffff1f;box-shadow:inset 0 5px 12px #0008;transition:.4s}.red-bubble-switch i{position:absolute;left:4px;top:4px;width:34px;height:34px;border-radius:48% 52% 55% 45%;background:linear-gradient(145deg,#9f8cff,#6654dd);box-shadow:inset 5px 6px 8px #fff3,0 5px 10px #0006,0 0 14px #756cff44;transition:left .45s cubic-bezier(.2,1.2,.3,1),border-radius .4s,background .4s}.red-bubble-switch input:checked+span{background:#102421}.red-bubble-switch input:checked+span i{left:43px;border-radius:55% 45% 42% 58%;background:linear-gradient(145deg,#6ee7c8,#20b79e);box-shadow:inset 5px 6px 8px #fff3,0 5px 10px #0006,0 0 14px #2dd4bf66}`,
    ['toggle', 'bubble', 'organic', 'morph', 'soft'],
  ),
]
